/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCheckoutFormsFromDiscriminatorValue, type CheckoutForms } from '../../models/index.js';
// @ts-ignore
import { CheckoutFormsItemRequestBuilderNavigationMetadata, CheckoutFormsItemRequestBuilderRequestsMetadata, type CheckoutFormsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /order/checkout-forms
 */
export interface CheckoutFormsRequestBuilder extends BaseRequestBuilder<CheckoutFormsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.order.checkoutForms.item collection
     * @param id Checkout form identifier.
     * @returns {CheckoutFormsItemRequestBuilder}
     */
     byId(id: Guid) : CheckoutFormsItemRequestBuilder;
    /**
     * Use this resource to get an order list. Read more: <a href="../../tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#lista-zamowien" target="_blank">PL</a> / <a href="../../tutorials/process-orders-PgPMlWDr8Cv#order-list" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CheckoutForms>}
     */
     get(requestConfiguration?: RequestConfiguration<CheckoutFormsRequestBuilderGetQueryParameters> | undefined) : Promise<CheckoutForms | undefined>;
    /**
     * Use this resource to get an order list. Read more: <a href="../../tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#lista-zamowien" target="_blank">PL</a> / <a href="../../tutorials/process-orders-PgPMlWDr8Cv#order-list" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<CheckoutFormsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Use this resource to get an order list. Read more: <a href="../../tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#lista-zamowien" target="_blank">PL</a> / <a href="../../tutorials/process-orders-PgPMlWDr8Cv#order-list" target="_blank">EN</a>.
 */
export interface CheckoutFormsRequestBuilderGetQueryParameters {
    /**
     * Find checkout-forms having specified buyer login.
     */
    buyerLogin?: string;
    /**
     * Find checkout-forms having specified delivery method id.
     */
    deliveryMethodId?: string;
    /**
     * Specify filter for order management provider. Allowed values are:  * `SELLER`: for orders managed directly by seller  * `ALLEGRO`: for orders managed by Allegro warehouse (One Fulfillment).
     */
    fulfillmentProviderId?: string;
    /**
     * Specify filter for line items sending status. Allowed values are:  * `NONE`: none of line items have tracking number specified  * `SOME`: some of line items have tracking number specified  * `ALL`: all of line items have tracking number specified.
     */
    fulfillmentShipmentSummaryLineItemsSent?: string;
    /**
     * Specify seller status value that checkout-forms must have to be included in the output. Allowed values are:  * `NEW`  * `PROCESSING`  * `READY_FOR_SHIPMENT`  * `READY_FOR_PICKUP`  * `SENT`  * `PICKED_UP`  * `CANCELLED`  * `SUSPENDED`  * `RETURNED`.
     */
    fulfillmentStatus?: string;
    /**
     * Maximum number of checkout-forms in response.
     */
    limit?: number;
    /**
     * Latest line item bought date. The lower bound of date time range from which checkout forms will be taken.
     */
    lineItemsBoughtAtGte?: Date;
    /**
     * Latest line item bought date. The upper bound of date time range from which checkout forms will be taken.
     */
    lineItemsBoughtAtLte?: Date;
    /**
     * Find checkout-forms of orders purchased on specified marketplace.
     */
    marketplaceId?: string;
    /**
     * Index of first returned checkout-form from all search results.
     */
    offset?: number;
    /**
     * Find checkout-forms having specified payment id.
     */
    paymentId?: string;
    /**
     * The results' sorting order. No prefix in the value means ascending order. `-` prefix means descending order. If you don't provide the sort parameter, the list is sorted by line item boughtAt date, descending.
     */
    sort?: GetSortQueryParameterType;
    /**
     * Specify status value that checkout-forms must have to be included in the output. Allowed values are:  * `BOUGHT`: purchase without checkout form filled in.  * `FILLED_IN`: checkout form filled in but payment is not completed yet so data could still change.  * `READY_FOR_PROCESSING`: payment completed. Purchase is ready for processing.  * `CANCELLED`: purchase cancelled by buyer.
     */
    status?: string;
    /**
     * Find checkout-forms having specified surcharge id.
     */
    surchargesId?: string;
    /**
     * Checkout form last modification date. The lower bound of date time range from which checkout forms will be taken.
     */
    updatedAtGte?: Date;
    /**
     * Checkout form last modification date. The upper bound of date time range from which checkout forms will be taken.
     */
    updatedAtLte?: Date;
}
export type GetSortQueryParameterType = (typeof GetSortQueryParameterTypeObject)[keyof typeof GetSortQueryParameterTypeObject];
/**
 * Uri template for the request builder.
 */
export const CheckoutFormsRequestBuilderUriTemplate = "{+baseurl}/order/checkout-forms{?buyer%2Elogin*,delivery%2Emethod%2Eid*,fulfillment%2Eprovider%2Eid*,fulfillment%2EshipmentSummary%2ElineItemsSent*,fulfillment%2Estatus*,limit*,lineItems%2EboughtAt%2Egte*,lineItems%2EboughtAt%2Elte*,marketplace%2Eid*,offset*,payment%2Eid*,sort*,status*,surcharges%2Eid*,updatedAt%2Egte*,updatedAt%2Elte*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const CheckoutFormsRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "buyerLogin": "buyer%2Elogin",
    "deliveryMethodId": "delivery%2Emethod%2Eid",
    "fulfillmentProviderId": "fulfillment%2Eprovider%2Eid",
    "fulfillmentShipmentSummaryLineItemsSent": "fulfillment%2EshipmentSummary%2ElineItemsSent",
    "fulfillmentStatus": "fulfillment%2Estatus",
    "lineItemsBoughtAtGte": "lineItems%2EboughtAt%2Egte",
    "lineItemsBoughtAtLte": "lineItems%2EboughtAt%2Elte",
    "marketplaceId": "marketplace%2Eid",
    "paymentId": "payment%2Eid",
    "surchargesId": "surcharges%2Eid",
    "updatedAtGte": "updatedAt%2Egte",
    "updatedAtLte": "updatedAt%2Elte",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CheckoutFormsRequestBuilderNavigationMetadata: Record<Exclude<keyof CheckoutFormsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: CheckoutFormsItemRequestBuilderRequestsMetadata,
        navigationMetadata: CheckoutFormsItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const CheckoutFormsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: CheckoutFormsRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        adapterMethodName: "send",
        responseBodyFactory:  createCheckoutFormsFromDiscriminatorValue,
        queryParametersMapper: CheckoutFormsRequestBuilderGetQueryParametersMapper,
    },
};
export const GetSortQueryParameterTypeObject = {
    LineItemsBoughtAt: "lineItems.boughtAt",
    Minus_lineItemsBoughtAt: "-lineItems.boughtAt",
    UpdatedAt: "updatedAt",
    Minus_updatedAt: "-updatedAt",
} as const;
/* tslint:enable */
/* eslint-enable */
