/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAuthErrorFromDiscriminatorValue, createErrorsHolderFromDiscriminatorValue, createFulfillmentRemovalPreferenceFromDiscriminatorValue, serializeFulfillmentRemovalPreference, type AuthError, type ErrorsHolder, type FulfillmentRemovalPreference } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /fulfillment/removal/preferences
 */
export interface PreferencesRequestBuilder extends BaseRequestBuilder<PreferencesRequestBuilder> {
    /**
     * Use this resource to read your current removal preference. Removal preference is associated with system removal order at the moment of removal order is created. It means there can be not yet fulfilled removal orders associated with previously set removal preference. Read more: <a href="../../tutorials/one-fulfillment-by-allegro-0ADwgOLqWSw#pobierz-aktualne-ustawienia-sposobu-usuniecia-towaru-z-magazynu" target="_blank">PL</a> / <a href="../../tutorials/one-fulfillment-by-allegro-4R9dXyMPlc9#retrieve-current-settings-for-how-to-remove-goods-from-the-warehouse" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FulfillmentRemovalPreference>}
     * @throws {AuthError} error when the service returns a 401 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FulfillmentRemovalPreference | undefined>;
    /**
     * Use this resource to create new active removal preference. From the moment the preference is set, it becomes the active one, and all new system removal orders will be associated with this preference. Removal preference is associated with system removal order at the moment of removal order is created. It means there can be not yet fulfilled removal orders associated with previously set removal preference. Read more: <a href="../../tutorials/one-fulfillment-by-allegro-0ADwgOLqWSw#utworz-lub-edytuj-ustawienia-sposobu-usuniecia-towaru-z-magazynu" target="_blank">PL</a> / <a href="../../tutorials/one-fulfillment-by-allegro-4R9dXyMPlc9#create-or-edit-settings-for-how-to-remove-goods-from-the-warehouse" target="_blank">EN</a>.
     * @param body Represents seller preference how to handle goods that should be removed from 1F warehouse.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FulfillmentRemovalPreference>}
     * @throws {AuthError} error when the service returns a 401 status code
     * @throws {ErrorsHolder} error when the service returns a 422 status code
     */
     put(body: FulfillmentRemovalPreference, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FulfillmentRemovalPreference | undefined>;
    /**
     * Use this resource to read your current removal preference. Removal preference is associated with system removal order at the moment of removal order is created. It means there can be not yet fulfilled removal orders associated with previously set removal preference. Read more: <a href="../../tutorials/one-fulfillment-by-allegro-0ADwgOLqWSw#pobierz-aktualne-ustawienia-sposobu-usuniecia-towaru-z-magazynu" target="_blank">PL</a> / <a href="../../tutorials/one-fulfillment-by-allegro-4R9dXyMPlc9#retrieve-current-settings-for-how-to-remove-goods-from-the-warehouse" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Use this resource to create new active removal preference. From the moment the preference is set, it becomes the active one, and all new system removal orders will be associated with this preference. Removal preference is associated with system removal order at the moment of removal order is created. It means there can be not yet fulfilled removal orders associated with previously set removal preference. Read more: <a href="../../tutorials/one-fulfillment-by-allegro-0ADwgOLqWSw#utworz-lub-edytuj-ustawienia-sposobu-usuniecia-towaru-z-magazynu" target="_blank">PL</a> / <a href="../../tutorials/one-fulfillment-by-allegro-4R9dXyMPlc9#create-or-edit-settings-for-how-to-remove-goods-from-the-warehouse" target="_blank">EN</a>.
     * @param body Represents seller preference how to handle goods that should be removed from 1F warehouse.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: FulfillmentRemovalPreference, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PreferencesRequestBuilderUriTemplate = "{+baseurl}/fulfillment/removal/preferences";
/**
 * Metadata for all the requests in the request builder.
 */
export const PreferencesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PreferencesRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            401: createAuthErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFulfillmentRemovalPreferenceFromDiscriminatorValue,
    },
    put: {
        uriTemplate: PreferencesRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            401: createAuthErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFulfillmentRemovalPreferenceFromDiscriminatorValue,
        requestBodyContentType: "application/vnd.allegro.public.v1+json",
        requestBodySerializer: serializeFulfillmentRemovalPreference,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
