/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAvailabilityResponseFromDiscriminatorValue, createBadRequestResponseFromDiscriminatorValue, createErrorApiResponseFromDiscriminatorValue, type AvailabilityResponse, type BadRequestResponse, type ErrorApiResponse } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/user/orders/{id}/documents
 */
export interface DocumentsRequestBuilder extends BaseRequestBuilder<DocumentsRequestBuilder> {
    /**
     * Metoda służy do zwrócenia informacji, które dokumenty są dostępne dla wybranego zamówienia.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AvailabilityResponse>}
     * @throws {BadRequestResponse} error when the service returns a 400 status code
     * @throws {ErrorApiResponse} error when the service returns a 403 status code
     * @throws {ErrorApiResponse} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AvailabilityResponse | undefined>;
    /**
     * Metoda służy do zwrócenia informacji, które dokumenty są dostępne dla wybranego zamówienia.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DocumentsRequestBuilderUriTemplate = "{+baseurl}/v1/user/orders/{id}/documents";
/**
 * Metadata for all the requests in the request builder.
 */
export const DocumentsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DocumentsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBadRequestResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAvailabilityResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
