/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBadRequestResponseFromDiscriminatorValue, createErrorApiResponseFromDiscriminatorValue, createInvoiceUrlFromDiscriminatorValue, type BadRequestResponse, type ErrorApiResponse, type InvoiceUrl } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/user/invoices/{id}/invoice
 */
export interface InvoiceRequestBuilder extends BaseRequestBuilder<InvoiceRequestBuilder> {
    /**
     * Metoda zwraca link do pobrania faktury z systemu epaka.pl
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<InvoiceUrl>}
     * @throws {BadRequestResponse} error when the service returns a 400 status code
     * @throws {ErrorApiResponse} error when the service returns a 403 status code
     * @throws {ErrorApiResponse} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<InvoiceUrl | undefined>;
    /**
     * Metoda zwraca link do pobrania faktury z systemu epaka.pl
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const InvoiceRequestBuilderUriTemplate = "{+baseurl}/v1/user/invoices/{id}/invoice";
/**
 * Metadata for all the requests in the request builder.
 */
export const InvoiceRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: InvoiceRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBadRequestResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createInvoiceUrlFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
