/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBadRequestResponseFromDiscriminatorValue, createErrorApiResponseFromDiscriminatorValue, createInsurancePriceResponseFromDiscriminatorValue, type BadRequestResponse, type ErrorApiResponse, type InsurancePriceResponse } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/order/services/insurance/price
 */
export interface PriceRequestBuilder extends BaseRequestBuilder<PriceRequestBuilder> {
    /**
     * Metoda służy do wyceny usługi ubezpieczenia, dla podanej kwoty ubezpieczenia.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<InsurancePriceResponse>}
     * @throws {BadRequestResponse} error when the service returns a 400 status code
     * @throws {ErrorApiResponse} error when the service returns a 403 status code
     */
     get(requestConfiguration?: RequestConfiguration<PriceRequestBuilderGetQueryParameters> | undefined) : Promise<InsurancePriceResponse | undefined>;
    /**
     * Metoda służy do wyceny usługi ubezpieczenia, dla podanej kwoty ubezpieczenia.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<PriceRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Metoda służy do wyceny usługi ubezpieczenia, dla podanej kwoty ubezpieczenia.
 */
export interface PriceRequestBuilderGetQueryParameters {
    /**
     * Id kuriera
     */
    courierId?: number;
    /**
     * Wartość ubezpieczenia
     */
    declaredValue?: number;
    /**
     * Maksymalna waga przesyłek (DHL)
     */
    maxWeight?: number;
    /**
     * Kraj odbioru
     */
    receiverCountry?: string;
    /**
     * Kraj nadania
     */
    senderCountry?: string;
}
/**
 * Uri template for the request builder.
 */
export const PriceRequestBuilderUriTemplate = "{+baseurl}/v1/order/services/insurance/price?courierId={courierId}&declaredValue={declaredValue}{&maxWeight*,receiverCountry*,senderCountry*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const PriceRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PriceRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBadRequestResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createInsurancePriceResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
