/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCourierDataFromDiscriminatorValue, createErrorApiResponseFromDiscriminatorValue, type CourierData, type ErrorApiResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/couriers/{id}
 */
export interface CouriersItemRequestBuilder extends BaseRequestBuilder<CouriersItemRequestBuilder> {
    /**
     * Metoda służy do pobrania danych wybranego kuriera.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CourierData>}
     * @throws {ErrorApiResponse} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CourierData | undefined>;
    /**
     * Metoda służy do pobrania danych wybranego kuriera.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CouriersItemRequestBuilderUriTemplate = "{+baseurl}/v1/couriers/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const CouriersItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: CouriersItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            404: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCourierDataFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
