/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createWebhookFromDiscriminatorValue, serializeWebhook, type Webhook } from '../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WebhooksPostRequestBody}
 */
// @ts-ignore
export function createWebhooksPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWebhooksPostRequestBody;
}
/**
 * The deserialization information for the current model
 * @param WebhooksPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWebhooksPostRequestBody(webhooksPostRequestBody: Partial<WebhooksPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "webhook": n => { webhooksPostRequestBody.webhook = n.getObjectValue<Webhook>(createWebhookFromDiscriminatorValue); },
    }
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WebhooksPostRequestBody The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWebhooksPostRequestBody(writer: SerializationWriter, webhooksPostRequestBody: Partial<WebhooksPostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!webhooksPostRequestBody || isSerializingDerivedType) { return; }
    writer.writeObjectValue<Webhook>("webhook", webhooksPostRequestBody.webhook, serializeWebhook);
    writer.writeAdditionalData(webhooksPostRequestBody.additionalData);
}
/**
 * Builds and executes requests for operations under /webhooks.json
 */
export interface WebhooksJsonRequestBuilder extends BaseRequestBuilder<WebhooksJsonRequestBuilder> {
    /**
     * List webhooks
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Webhook[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Webhook[] | undefined>;
    /**
     * Create webhook
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Webhook>}
     */
     post(body: WebhooksPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Webhook | undefined>;
    /**
     * List webhooks
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Create webhook
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: WebhooksPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface WebhooksPostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The webhook property
     */
    webhook?: Webhook | null;
}
/**
 * Uri template for the request builder.
 */
export const WebhooksJsonRequestBuilderUriTemplate = "{+baseurl}/webhooks.json";
/**
 * Metadata for all the requests in the request builder.
 */
export const WebhooksJsonRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WebhooksJsonRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createWebhookFromDiscriminatorValue,
    },
    post: {
        uriTemplate: WebhooksJsonRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createWebhookFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeWebhooksPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
