/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorsHolderFromDiscriminatorValue, createStockProductListFromDiscriminatorValue, type ErrorsHolder, type StockProductList } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

export type GetAsnStatusQueryParameterType = (typeof GetAsnStatusQueryParameterTypeObject)[keyof typeof GetAsnStatusQueryParameterTypeObject];
export type GetProductAvailabilityQueryParameterType = (typeof GetProductAvailabilityQueryParameterTypeObject)[keyof typeof GetProductAvailabilityQueryParameterTypeObject];
export type GetProductStatusQueryParameterType = (typeof GetProductStatusQueryParameterTypeObject)[keyof typeof GetProductStatusQueryParameterTypeObject];
export type GetSortQueryParameterType = (typeof GetSortQueryParameterTypeObject)[keyof typeof GetSortQueryParameterTypeObject];
/**
 * Builds and executes requests for operations under /fulfillment/stock
 */
export interface StockRequestBuilder extends BaseRequestBuilder<StockRequestBuilder> {
    /**
     * Use this resource to get a list of the products belonging to the seller, which are in Allegro Warehouse. Read more: <a href="../../tutorials/one-fulfillment-by-allegro-0ADwgOLqWSw#jak-pobrac-aktualne-stany-magazynowe" target="_blank">PL</a> / <a href="../../tutorials/one-fulfillment-by-allegro-4R9dXyMPlc9#get-available-stock" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<StockProductList>}
     * @throws {ErrorsHolder} error when the service returns a 422 status code
     */
     get(requestConfiguration?: RequestConfiguration<StockRequestBuilderGetQueryParameters> | undefined) : Promise<StockProductList | undefined>;
    /**
     * Use this resource to get a list of the products belonging to the seller, which are in Allegro Warehouse. Read more: <a href="../../tutorials/one-fulfillment-by-allegro-0ADwgOLqWSw#jak-pobrac-aktualne-stany-magazynowe" target="_blank">PL</a> / <a href="../../tutorials/one-fulfillment-by-allegro-4R9dXyMPlc9#get-available-stock" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<StockRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Use this resource to get a list of the products belonging to the seller, which are in Allegro Warehouse. Read more: <a href="../../tutorials/one-fulfillment-by-allegro-0ADwgOLqWSw#jak-pobrac-aktualne-stany-magazynowe" target="_blank">PL</a> / <a href="../../tutorials/one-fulfillment-by-allegro-4R9dXyMPlc9#get-available-stock" target="_blank">EN</a>.
 */
export interface StockRequestBuilderGetQueryParameters {
    /**
     * Filtering search results by ASN status. Following values are allowed: SUBMITTED - Advanced Ship Notice document has been submitted and it contains a particular product. Only the products that have ASN with products on it are returned. NOT_FOUND - Advanced Ship Notice that contains a particular product was not found. It has not been submitted, may be expired, or products have already been delivered to the warehouse. Only the products that don't have related ASN with products on it are returned.
     */
    asnStatus?: GetAsnStatusQueryParameterType;
    /**
     * Maximum number of elements in response. Ignored for text/csv content type.
     */
    limit?: number;
    /**
     * The offset of elements in the response. Ignored for text/csv content type.
     */
    offset?: number;
    /**
     * Filter by products with outOfStockIn greater than or equal.
     */
    outOfStockInFrom?: number;
    /**
     * Filter by products with outOfStockIn less than or equal.
     */
    outOfStockInTo?: number;
    /**
     * Filtering search results by product name.
     */
    phrase?: string;
    /**
     * Filtering search results by availability.
     */
    productAvailability?: GetProductAvailabilityQueryParameterType[];
    /**
     * Filtering search results by fulfillment product identifier. Ignored for text/csv content type.
     */
    productId?: Guid;
    /**
     * Filtering search results by status.
     */
    productStatus?: GetProductStatusQueryParameterType;
    /**
     * Defines how elements are sorted in response. Minus sign can be added to imply descending sort order. Ignored for text/csv content type.Possible values for the "sort" parameter:  * -available - sorting by quantity of available products (descending)  * available - sorting by quantity of available products (ascending)  * -unfulfillable - sorting by quantity of unfulfillable products (descending)  * unfulfillable - sorting by quantity of unfulfillable products (ascending)  * -name - sorting by product’s name (descending)  * name - sorting by product’s name (ascending)  * lastFourteenDaysSalesAverage - sorting by product last fourteen days average sales (ascending)  * -lastFourteenDaysSalesAverage - sorting by product last fourteen days average sales (descending)  * reserve - sorting by reserve.outOfStockIn field (ascending)  * -reserve - sorting by reserve.outOfStockIn field (descending)  * lastThirtyDaysSalesSum - sorting by product last month sum sales (ascending)  * -lastThirtyDaysSalesSum - sorting by product last month sum sales (descending)  * storageFee - sorting by storage fee (ascending). The order by fee status is: NOT_APPLICABLE, then CHARGED ordered by amountGross ascending.  * -storageFee - sorting by storage fee (descending). The order by fee status is: CHARGED ordered by amountGross descending, then NOT_APPLICABLE.
     */
    sort?: GetSortQueryParameterType;
}
/**
 * Uri template for the request builder.
 */
export const StockRequestBuilderUriTemplate = "{+baseurl}/fulfillment/stock{?asnStatus*,limit*,offset*,outOfStockInFrom*,outOfStockInTo*,phrase*,productAvailability*,productId*,productStatus*,sort*}";
export const GetAsnStatusQueryParameterTypeObject = {
    SUBMITTED: "SUBMITTED",
    NOT_FOUND: "NOT_FOUND",
} as const;
export const GetProductAvailabilityQueryParameterTypeObject = {
    SUFFICIENT: "SUFFICIENT",
    UNAVAILABLE: "UNAVAILABLE",
    LOW: "LOW",
} as const;
export const GetProductStatusQueryParameterTypeObject = {
    UNFULFILLABLE: "UNFULFILLABLE",
} as const;
export const GetSortQueryParameterTypeObject = {
    Available: "available",
    Minus_available: "-available",
    Unfulfillable: "unfulfillable",
    Minus_unfulfillable: "-unfulfillable",
    Name: "name",
    Minus_name: "-name",
    LastFourteenDaysSalesAverage: "lastFourteenDaysSalesAverage",
    Minus_lastFourteenDaysSalesAverage: "-lastFourteenDaysSalesAverage",
    Reserve: "reserve",
    Minus_reserve: "-reserve",
    LastThirtyDaysSalesSum: "lastThirtyDaysSalesSum",
    Minus_lastThirtyDaysSalesSum: "-lastThirtyDaysSalesSum",
    StorageFee: "storageFee",
    Minus_storageFee: "-storageFee",
} as const;
/**
 * Metadata for all the requests in the request builder.
 */
export const StockRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: StockRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            422: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createStockProductListFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
