/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAuthErrorFromDiscriminatorValue, createErrorsHolderFromDiscriminatorValue, createSellerOfferEventsResponseFromDiscriminatorValue, type AuthError, type ErrorsHolder, type SellerOfferEventsResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

export type GetTypeQueryParameterType = (typeof GetTypeQueryParameterTypeObject)[keyof typeof GetTypeQueryParameterTypeObject];
/**
 * Builds and executes requests for operations under /sale/offer-events
 */
export interface OfferEventsRequestBuilder extends BaseRequestBuilder<OfferEventsRequestBuilder> {
    /**
     * Use this endpoint to get events from the last 24 hours concerning changes in the authorized seller's offers.At present we support the following events:  - OFFER_ACTIVATED - offer is visible on site and available for purchase, occurs when offer status changes from ACTIVATING to ACTIVE.  - OFFER_CHANGED - occurs when offer's fields has been changed e.g. description or photos.  - OFFER_ENDED - offer is no longer available for purchase, occurs when offer status changes from ACTIVE to ENDED.  - OFFER_STOCK_CHANGED - stock in an offer was changed either via purchase or by seller.  - OFFER_PRICE_CHANGED - occurs when price in an offer was changed.  - OFFER_ARCHIVED - offer is no longer available on listing and has been archived.  - OFFER_BID_PLACED - bid was placed on the offer.  - OFFER_BID_CANCELED - bid for offer was canceled.  - OFFER_TRANSLATION_UPDATED - translation of offer was updated.  - OFFER_VISIBILITY_CHANGED - visibility of offer was changed on marketplaces.  - OFFER_DELIVERY_COUNTRIES_BLOCKED - the offer has been blocked in selected countries.Returned events may occur by actions made via browser or API. The resource allows you to get events concerning active offers and offers scheduled for activation (status ACTIVE and ACTIVATING). Returned events do not concern offers in INACTIVE and ENDED status (the exception is OFFER_ARCHIVED event). External id is returned for all event types except OFFER_BID_PLACED and OFFER_BID_CANCELED. Please note that one change may result in more than one event. Read more: <a href="../../tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#dziennik-zdarzen-w-ofertach-sprzedawcy" target="_blank">PL</a> / <a href="../../tutorials/how-to-process-list-of-offers-m09BKA5v8H3#event-journal-concerning-changes-in-seller-s-offers" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SellerOfferEventsResponse>}
     * @throws {ErrorsHolder} error when the service returns a 400 status code
     * @throws {AuthError} error when the service returns a 401 status code
     */
     get(requestConfiguration?: RequestConfiguration<OfferEventsRequestBuilderGetQueryParameters> | undefined) : Promise<SellerOfferEventsResponse | undefined>;
    /**
     * Use this endpoint to get events from the last 24 hours concerning changes in the authorized seller's offers.At present we support the following events:  - OFFER_ACTIVATED - offer is visible on site and available for purchase, occurs when offer status changes from ACTIVATING to ACTIVE.  - OFFER_CHANGED - occurs when offer's fields has been changed e.g. description or photos.  - OFFER_ENDED - offer is no longer available for purchase, occurs when offer status changes from ACTIVE to ENDED.  - OFFER_STOCK_CHANGED - stock in an offer was changed either via purchase or by seller.  - OFFER_PRICE_CHANGED - occurs when price in an offer was changed.  - OFFER_ARCHIVED - offer is no longer available on listing and has been archived.  - OFFER_BID_PLACED - bid was placed on the offer.  - OFFER_BID_CANCELED - bid for offer was canceled.  - OFFER_TRANSLATION_UPDATED - translation of offer was updated.  - OFFER_VISIBILITY_CHANGED - visibility of offer was changed on marketplaces.  - OFFER_DELIVERY_COUNTRIES_BLOCKED - the offer has been blocked in selected countries.Returned events may occur by actions made via browser or API. The resource allows you to get events concerning active offers and offers scheduled for activation (status ACTIVE and ACTIVATING). Returned events do not concern offers in INACTIVE and ENDED status (the exception is OFFER_ARCHIVED event). External id is returned for all event types except OFFER_BID_PLACED and OFFER_BID_CANCELED. Please note that one change may result in more than one event. Read more: <a href="../../tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#dziennik-zdarzen-w-ofertach-sprzedawcy" target="_blank">PL</a> / <a href="../../tutorials/how-to-process-list-of-offers-m09BKA5v8H3#event-journal-concerning-changes-in-seller-s-offers" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<OfferEventsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Use this endpoint to get events from the last 24 hours concerning changes in the authorized seller's offers.At present we support the following events:  - OFFER_ACTIVATED - offer is visible on site and available for purchase, occurs when offer status changes from ACTIVATING to ACTIVE.  - OFFER_CHANGED - occurs when offer's fields has been changed e.g. description or photos.  - OFFER_ENDED - offer is no longer available for purchase, occurs when offer status changes from ACTIVE to ENDED.  - OFFER_STOCK_CHANGED - stock in an offer was changed either via purchase or by seller.  - OFFER_PRICE_CHANGED - occurs when price in an offer was changed.  - OFFER_ARCHIVED - offer is no longer available on listing and has been archived.  - OFFER_BID_PLACED - bid was placed on the offer.  - OFFER_BID_CANCELED - bid for offer was canceled.  - OFFER_TRANSLATION_UPDATED - translation of offer was updated.  - OFFER_VISIBILITY_CHANGED - visibility of offer was changed on marketplaces.  - OFFER_DELIVERY_COUNTRIES_BLOCKED - the offer has been blocked in selected countries.Returned events may occur by actions made via browser or API. The resource allows you to get events concerning active offers and offers scheduled for activation (status ACTIVE and ACTIVATING). Returned events do not concern offers in INACTIVE and ENDED status (the exception is OFFER_ARCHIVED event). External id is returned for all event types except OFFER_BID_PLACED and OFFER_BID_CANCELED. Please note that one change may result in more than one event. Read more: <a href="../../tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#dziennik-zdarzen-w-ofertach-sprzedawcy" target="_blank">PL</a> / <a href="../../tutorials/how-to-process-list-of-offers-m09BKA5v8H3#event-journal-concerning-changes-in-seller-s-offers" target="_blank">EN</a>.
 */
export interface OfferEventsRequestBuilderGetQueryParameters {
    /**
     * The ID of the last seen event. Events that occured after the given event will be returned.
     */
    from?: string;
    /**
     * The number of events that will be returned in the response.
     */
    limit?: number;
    /**
     * The types of events that will be returned in the response. All types of events are returned by default.
     */
    type?: GetTypeQueryParameterType[];
}
/**
 * Uri template for the request builder.
 */
export const OfferEventsRequestBuilderUriTemplate = "{+baseurl}/sale/offer-events{?from*,limit*,type*}";
export const GetTypeQueryParameterTypeObject = {
    OFFER_ACTIVATED: "OFFER_ACTIVATED",
    OFFER_CHANGED: "OFFER_CHANGED",
    OFFER_ENDED: "OFFER_ENDED",
    OFFER_STOCK_CHANGED: "OFFER_STOCK_CHANGED",
    OFFER_PRICE_CHANGED: "OFFER_PRICE_CHANGED",
    OFFER_ARCHIVED: "OFFER_ARCHIVED",
    OFFER_BID_PLACED: "OFFER_BID_PLACED",
    OFFER_BID_CANCELED: "OFFER_BID_CANCELED",
    OFFER_TRANSLATION_UPDATED: "OFFER_TRANSLATION_UPDATED",
    OFFER_VISIBILITY_CHANGED: "OFFER_VISIBILITY_CHANGED",
    OFFER_DELIVERY_COUNTRIES_BLOCKED: "OFFER_DELIVERY_COUNTRIES_BLOCKED",
} as const;
/**
 * Metadata for all the requests in the request builder.
 */
export const OfferEventsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: OfferEventsRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            400: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAuthErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSellerOfferEventsResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
