export const getStatusColor = (status: string) => {
  return status === "NEW"
    ? "blue"
    : status === "UNDER_REVIEW"
      ? "yellow"
      : status === "IN_PROGRESS"
        ? "orange"
        : status === "WAITING_FOR_MATERIALS"
          ? "purple"
          : status === "DELAYED"
            ? "red"
            : status === "READY"
              ? "green"
              : status === "FULFILLED"
                ? "gray"
                : status === "SHIPPED"
                  ? "green"
                  : status === "PICKED_UP"
                    ? "green"
                    : status === "DELIVERED"
                      ? "green"
                      : status === "COMPLETED"
                        ? "green"
                        : status === "REFUNDED"
                          ? "green"
                          : status === "ALLEGRO"
                            ? "green"
                            : status === "PENDING"
                              ? "orange"
                              : status === "CANCELED"
                                ? "red"
                                : status === "DRAFT"
                                  ? "gray"
                                  : undefined;
};
