/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createWarehouseFromDiscriminatorValue, serializeWarehouse, type Warehouse } from '../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WarehousesPostRequestBody}
 */
// @ts-ignore
export function createWarehousesPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWarehousesPostRequestBody;
}
/**
 * The deserialization information for the current model
 * @param WarehousesPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWarehousesPostRequestBody(warehousesPostRequestBody: Partial<WarehousesPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "warehouse": n => { warehousesPostRequestBody.warehouse = n.getObjectValue<Warehouse>(createWarehouseFromDiscriminatorValue); },
    }
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WarehousesPostRequestBody The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWarehousesPostRequestBody(writer: SerializationWriter, warehousesPostRequestBody: Partial<WarehousesPostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!warehousesPostRequestBody || isSerializingDerivedType) { return; }
    writer.writeObjectValue<Warehouse>("warehouse", warehousesPostRequestBody.warehouse, serializeWarehouse);
    writer.writeAdditionalData(warehousesPostRequestBody.additionalData);
}
/**
 * Builds and executes requests for operations under /warehouses.json
 */
export interface WarehousesJsonRequestBuilder extends BaseRequestBuilder<WarehousesJsonRequestBuilder> {
    /**
     * List warehouses
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Warehouse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Warehouse[] | undefined>;
    /**
     * Create warehouse
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Warehouse>}
     */
     post(body: WarehousesPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Warehouse | undefined>;
    /**
     * List warehouses
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Create warehouse
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: WarehousesPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface WarehousesPostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The warehouse property
     */
    warehouse?: Warehouse | null;
}
/**
 * Uri template for the request builder.
 */
export const WarehousesJsonRequestBuilderUriTemplate = "{+baseurl}/warehouses.json";
/**
 * Metadata for all the requests in the request builder.
 */
export const WarehousesJsonRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WarehousesJsonRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createWarehouseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: WarehousesJsonRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createWarehouseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeWarehousesPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
