/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBadRequestResponseFromDiscriminatorValue, createErrorApiResponseFromDiscriminatorValue, createPricesResponseFromDiscriminatorValue, serializePricesPayload, serializePricesResponse, type BadRequestResponse, type ErrorApiResponse, type PricesPayload, type PricesResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/order/prices
 */
export interface PricesRequestBuilder extends BaseRequestBuilder<PricesRequestBuilder> {
    /**
     * Metoda służy do wykonania, wstępnej wyceny przesyłki, dla podanych parametrów przesyłki. Zwraca listę dostępnych kurierów, wraz z cenami.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PricesResponse>}
     * @throws {BadRequestResponse} error when the service returns a 400 status code
     * @throws {ErrorApiResponse} error when the service returns a 403 status code
     */
     post(body: PricesPayload, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PricesResponse | undefined>;
    /**
     * Metoda służy do wykonania, wstępnej wyceny przesyłki, dla podanych parametrów przesyłki. Zwraca listę dostępnych kurierów, wraz z cenami.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: PricesPayload, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PricesRequestBuilderUriTemplate = "{+baseurl}/v1/order/prices";
/**
 * Metadata for all the requests in the request builder.
 */
export const PricesRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: PricesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBadRequestResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPricesResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializePricesPayload,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
