/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createGeneralReportFromDiscriminatorValue, serializeGeneralReport, serializeOfferAutomaticPricingCommand, type GeneralReport, type OfferAutomaticPricingCommand } from '../../models/index.js';
// @ts-ignore
import { type WithCommandItemRequestBuilder, WithCommandItemRequestBuilderNavigationMetadata, WithCommandItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /sale/offer-price-automation-commands
 */
export interface OfferPriceAutomationCommandsRequestBuilder extends BaseRequestBuilder<OfferPriceAutomationCommandsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.sale.offerPriceAutomationCommands.item collection
     * @param commandId Command identifier.
     * @returns {WithCommandItemRequestBuilder}
     */
     byCommandId(commandId: string) : WithCommandItemRequestBuilder;
    /**
     * Use this resource to modify the automatic pricing rules of multiple offers at the same time. Read more: <a href="../../tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#reguly-cenowe" target="_blank">PL</a> / <a href="../../tutorials/how-to-process-list-of-offers-m09BKA5v8H3#pricing-rules" target="_blank">EN</a>. This resource is rate limited to 150 000 offer changes per hour or 9000 offer changes per minute - limit applies to a single user of the application.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GeneralReport>}
     */
     post(body: OfferAutomaticPricingCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<GeneralReport | undefined>;
    /**
     * Use this resource to modify the automatic pricing rules of multiple offers at the same time. Read more: <a href="../../tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#reguly-cenowe" target="_blank">PL</a> / <a href="../../tutorials/how-to-process-list-of-offers-m09BKA5v8H3#pricing-rules" target="_blank">EN</a>. This resource is rate limited to 150 000 offer changes per hour or 9000 offer changes per minute - limit applies to a single user of the application.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: OfferAutomaticPricingCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const OfferPriceAutomationCommandsRequestBuilderUriTemplate = "{+baseurl}/sale/offer-price-automation-commands";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OfferPriceAutomationCommandsRequestBuilderNavigationMetadata: Record<Exclude<keyof OfferPriceAutomationCommandsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byCommandId: {
        requestsMetadata: WithCommandItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithCommandItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["commandId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const OfferPriceAutomationCommandsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: OfferPriceAutomationCommandsRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        adapterMethodName: "send",
        responseBodyFactory:  createGeneralReportFromDiscriminatorValue,
        requestBodyContentType: "application/vnd.allegro.public.v1+json",
        requestBodySerializer: serializeOfferAutomaticPricingCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
