/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAfterSalesServicesAttachmentFromDiscriminatorValue, serializeAfterSalesServicesAttachment, type AfterSalesServicesAttachment } from '../../models/index.js';
// @ts-ignore
import { type WithAttachmentItemRequestBuilder, WithAttachmentItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface AttachmentsPostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The name property
     */
    name?: string | null;
}
/**
 * Builds and executes requests for operations under /after-sales-service-conditions/attachments
 */
export interface AttachmentsRequestBuilder extends BaseRequestBuilder<AttachmentsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.afterSalesServiceConditions.attachments.item collection
     * @param attachmentId The ID of the attachment.
     * @returns {WithAttachmentItemRequestBuilder}
     */
     byAttachmentId(attachmentId: string) : WithAttachmentItemRequestBuilder;
    /**
     * You can attach PDF files to warranties.Uploading attachments flow:  1. Create an attachment object to receive an upload URL (*POST /after-sales-service-conditions/attachments*),  2. Use the upload URL to submit the PDF file (*PUT /after-sales-service-conditions/attachments/{attachmentId}*),  3. Create (or update) warranty with attachment (*POST /after-sales-service-conditions/warranties*).  Read more: <a href="../../tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-dodac-zalacznik-do-informacji-o-gwarancjach" target="_blank">PL</a> / <a href="../../tutorials/how-to-process-list-of-offers-m09BKA5v8H3#how-to-add-attachment-to-warranty-information" target="_blank">EN</a>.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AfterSalesServicesAttachment>}
     */
     post(body: AttachmentsPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AfterSalesServicesAttachment | undefined>;
    /**
     * You can attach PDF files to warranties.Uploading attachments flow:  1. Create an attachment object to receive an upload URL (*POST /after-sales-service-conditions/attachments*),  2. Use the upload URL to submit the PDF file (*PUT /after-sales-service-conditions/attachments/{attachmentId}*),  3. Create (or update) warranty with attachment (*POST /after-sales-service-conditions/warranties*).  Read more: <a href="../../tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-dodac-zalacznik-do-informacji-o-gwarancjach" target="_blank">PL</a> / <a href="../../tutorials/how-to-process-list-of-offers-m09BKA5v8H3#how-to-add-attachment-to-warranty-information" target="_blank">EN</a>.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: AttachmentsPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AttachmentsPostRequestBody}
 */
// @ts-ignore
export function createAttachmentsPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAttachmentsPostRequestBody;
}
/**
 * The deserialization information for the current model
 * @param AttachmentsPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAttachmentsPostRequestBody(attachmentsPostRequestBody: Partial<AttachmentsPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { attachmentsPostRequestBody.name = n.getStringValue(); },
    }
}
/**
 * Serializes information the current object
 * @param AttachmentsPostRequestBody The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAttachmentsPostRequestBody(writer: SerializationWriter, attachmentsPostRequestBody: Partial<AttachmentsPostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!attachmentsPostRequestBody || isSerializingDerivedType) { return; }
    writer.writeStringValue("name", attachmentsPostRequestBody.name);
    writer.writeAdditionalData(attachmentsPostRequestBody.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const AttachmentsRequestBuilderUriTemplate = "{+baseurl}/after-sales-service-conditions/attachments";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AttachmentsRequestBuilderNavigationMetadata: Record<Exclude<keyof AttachmentsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byAttachmentId: {
        requestsMetadata: WithAttachmentItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["attachmentId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const AttachmentsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: AttachmentsRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        adapterMethodName: "send",
        responseBodyFactory:  createAfterSalesServicesAttachmentFromDiscriminatorValue,
        requestBodyContentType: "application/vnd.allegro.public.v1+json",
        requestBodySerializer: serializeAttachmentsPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
