/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAllegroPricesAccountParticipationResponseFromDiscriminatorValue, createAuthErrorFromDiscriminatorValue, createErrorsHolderFromDiscriminatorValue, serializeAllegroPricesAccountParticipationRequest, serializeAllegroPricesAccountParticipationResponse, type AllegroPricesAccountParticipationRequest, type AllegroPricesAccountParticipationResponse, type AuthError, type ErrorsHolder } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /sale/allegro-prices/accounts/participations
 */
export interface ParticipationsRequestBuilder extends BaseRequestBuilder<ParticipationsRequestBuilder> {
    /**
     * Use this resource to retrieve the account participation status for all supported marketplaces in the Allegro Prices program.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AllegroPricesAccountParticipationResponse>}
     * @throws {AuthError} error when the service returns a 401 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AllegroPricesAccountParticipationResponse | undefined>;
    /**
     * Use this resource to update the account participation status for one or more marketplaces in the Allegro Prices program.
     * @param body Request to update account participation for one or more marketplaces
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AllegroPricesAccountParticipationResponse>}
     * @throws {ErrorsHolder} error when the service returns a 400 status code
     * @throws {AuthError} error when the service returns a 401 status code
     * @throws {ErrorsHolder} error when the service returns a 422 status code
     */
     patch(body: AllegroPricesAccountParticipationRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AllegroPricesAccountParticipationResponse | undefined>;
    /**
     * Use this resource to retrieve the account participation status for all supported marketplaces in the Allegro Prices program.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Use this resource to update the account participation status for one or more marketplaces in the Allegro Prices program.
     * @param body Request to update account participation for one or more marketplaces
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: AllegroPricesAccountParticipationRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ParticipationsRequestBuilderUriTemplate = "{+baseurl}/sale/allegro-prices/accounts/participations";
/**
 * Metadata for all the requests in the request builder.
 */
export const ParticipationsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ParticipationsRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            401: createAuthErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAllegroPricesAccountParticipationResponseFromDiscriminatorValue,
    },
    patch: {
        uriTemplate: ParticipationsRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            400: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAuthErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAllegroPricesAccountParticipationResponseFromDiscriminatorValue,
        requestBodyContentType: "application/vnd.allegro.public.v1+json",
        requestBodySerializer: serializeAllegroPricesAccountParticipationRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
