/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAuthErrorFromDiscriminatorValue, createCancelShipmentCommandStatusDtoFromDiscriminatorValue, createError400FromDiscriminatorValue, createError403FromDiscriminatorValue, createError504FromDiscriminatorValue, serializeError400, serializeError403, serializeError504, type AuthError, type CancelShipmentCommandStatusDto, type Error400, type Error403, type Error504 } from '../../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface CancelShipmentCommandStatusDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Array of errors.
     */
    errors?: Error400[] | null;
}
export interface CancelShipmentCommandStatusDto403Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Array of errors.
     */
    errors?: Error403[] | null;
}
export interface CancelShipmentCommandStatusDto504Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Array of errors.
     */
    errors?: Error504[] | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CancelShipmentCommandStatusDto400Error}
 */
// @ts-ignore
export function createCancelShipmentCommandStatusDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCancelShipmentCommandStatusDto400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CancelShipmentCommandStatusDto403Error}
 */
// @ts-ignore
export function createCancelShipmentCommandStatusDto403ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCancelShipmentCommandStatusDto403Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CancelShipmentCommandStatusDto504Error}
 */
// @ts-ignore
export function createCancelShipmentCommandStatusDto504ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCancelShipmentCommandStatusDto504Error;
}
/**
 * The deserialization information for the current model
 * @param CancelShipmentCommandStatusDto400Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCancelShipmentCommandStatusDto400Error(cancelShipmentCommandStatusDto400Error: Partial<CancelShipmentCommandStatusDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "errors": n => { cancelShipmentCommandStatusDto400Error.errors = n.getCollectionOfObjectValues<Error400>(createError400FromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param CancelShipmentCommandStatusDto403Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCancelShipmentCommandStatusDto403Error(cancelShipmentCommandStatusDto403Error: Partial<CancelShipmentCommandStatusDto403Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "errors": n => { cancelShipmentCommandStatusDto403Error.errors = n.getCollectionOfObjectValues<Error403>(createError403FromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param CancelShipmentCommandStatusDto504Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCancelShipmentCommandStatusDto504Error(cancelShipmentCommandStatusDto504Error: Partial<CancelShipmentCommandStatusDto504Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "errors": n => { cancelShipmentCommandStatusDto504Error.errors = n.getCollectionOfObjectValues<Error504>(createError504FromDiscriminatorValue); },
    }
}
/**
 * Serializes information the current object
 * @param CancelShipmentCommandStatusDto400Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCancelShipmentCommandStatusDto400Error(writer: SerializationWriter, cancelShipmentCommandStatusDto400Error: Partial<CancelShipmentCommandStatusDto400Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!cancelShipmentCommandStatusDto400Error || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<Error400>("errors", cancelShipmentCommandStatusDto400Error.errors, serializeError400);
    writer.writeAdditionalData(cancelShipmentCommandStatusDto400Error.additionalData);
}
/**
 * Serializes information the current object
 * @param CancelShipmentCommandStatusDto403Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCancelShipmentCommandStatusDto403Error(writer: SerializationWriter, cancelShipmentCommandStatusDto403Error: Partial<CancelShipmentCommandStatusDto403Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!cancelShipmentCommandStatusDto403Error || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<Error403>("errors", cancelShipmentCommandStatusDto403Error.errors, serializeError403);
    writer.writeAdditionalData(cancelShipmentCommandStatusDto403Error.additionalData);
}
/**
 * Serializes information the current object
 * @param CancelShipmentCommandStatusDto504Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCancelShipmentCommandStatusDto504Error(writer: SerializationWriter, cancelShipmentCommandStatusDto504Error: Partial<CancelShipmentCommandStatusDto504Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!cancelShipmentCommandStatusDto504Error || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<Error504>("errors", cancelShipmentCommandStatusDto504Error.errors, serializeError504);
    writer.writeAdditionalData(cancelShipmentCommandStatusDto504Error.additionalData);
}
/**
 * Builds and executes requests for operations under /shipment-management/shipments/cancel-commands/{commandId}
 */
export interface WithCommandItemRequestBuilder extends BaseRequestBuilder<WithCommandItemRequestBuilder> {
    /**
     * Use this resource to get parcel cancellation status. Read more: <a href="../../tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-sprawdzic-status-anulowania-paczki" target="_blank">PL</a> / <a href="../../tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV#how-to-check-shipment-cancellation-status" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CancelShipmentCommandStatusDto>}
     * @throws {CancelShipmentCommandStatusDto400Error} error when the service returns a 400 status code
     * @throws {AuthError} error when the service returns a 401 status code
     * @throws {CancelShipmentCommandStatusDto403Error} error when the service returns a 403 status code
     * @throws {CancelShipmentCommandStatusDto504Error} error when the service returns a 504 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CancelShipmentCommandStatusDto | undefined>;
    /**
     * Use this resource to get parcel cancellation status. Read more: <a href="../../tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-sprawdzic-status-anulowania-paczki" target="_blank">PL</a> / <a href="../../tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV#how-to-check-shipment-cancellation-status" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithCommandItemRequestBuilderUriTemplate = "{+baseurl}/shipment-management/shipments/cancel-commands/{commandId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithCommandItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithCommandItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            400: createCancelShipmentCommandStatusDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAuthErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createCancelShipmentCommandStatusDto403ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            504: createCancelShipmentCommandStatusDto504ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCancelShipmentCommandStatusDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
