/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorsHolderFromDiscriminatorValue, createOffersSearchResultDtoFromDiscriminatorValue, type ErrorsHolder, type OffersSearchResultDto } from '../../models/index.js';
// @ts-ignore
import { type WithOfferItemRequestBuilder, WithOfferItemRequestBuilderNavigationMetadata, WithOfferItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { PromoOptionsRequestBuilderRequestsMetadata, type PromoOptionsRequestBuilder } from './promoOptions/index.js';
// @ts-ignore
import { PromoOptionsCommandsRequestBuilderNavigationMetadata, type PromoOptionsCommandsRequestBuilder } from './promoOptionsCommands/index.js';
// @ts-ignore
import { type UnfilledParametersRequestBuilder, UnfilledParametersRequestBuilderRequestsMetadata } from './unfilledParameters/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

export type GetPublicationStatusQueryParameterType = (typeof GetPublicationStatusQueryParameterTypeObject)[keyof typeof GetPublicationStatusQueryParameterTypeObject];
export type GetSellingModeFormatQueryParameterType = (typeof GetSellingModeFormatQueryParameterTypeObject)[keyof typeof GetSellingModeFormatQueryParameterTypeObject];
export type GetSortQueryParameterType = (typeof GetSortQueryParameterTypeObject)[keyof typeof GetSortQueryParameterTypeObject];
/**
 * Builds and executes requests for operations under /sale/offers
 */
export interface OffersRequestBuilder extends BaseRequestBuilder<OffersRequestBuilder> {
    /**
     * The promoOptions property
     */
    get promoOptions(): PromoOptionsRequestBuilder;
    /**
     * The promoOptionsCommands property
     */
    get promoOptionsCommands(): PromoOptionsCommandsRequestBuilder;
    /**
     * The unfilledParameters property
     */
    get unfilledParameters(): UnfilledParametersRequestBuilder;
    /**
     * Gets an item from the ApiSdk.sale.offers.item collection
     * @param offerId Offer identifier.
     * @returns {WithOfferItemRequestBuilder}
     */
     byOfferId(offerId: string) : WithOfferItemRequestBuilder;
    /**
     * Use this resource to get the list of the seller's offers. You can use different query parameters to filter the list. Read more: <a href="../../tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-pobrac-moje-oferty-w-rest-api" target="_blank">PL</a> / <a href="../../tutorials/how-to-process-list-of-offers-m09BKA5v8H3#list-of-offers" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<OffersSearchResultDto>}
     * @throws {ErrorsHolder} error when the service returns a 400 status code
     * @throws {ErrorsHolder} error when the service returns a 403 status code
     */
     get(requestConfiguration?: RequestConfiguration<OffersRequestBuilderGetQueryParameters> | undefined) : Promise<OffersSearchResultDto | undefined>;
    /**
     * Use this resource to get the list of the seller's offers. You can use different query parameters to filter the list. Read more: <a href="../../tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-pobrac-moje-oferty-w-rest-api" target="_blank">PL</a> / <a href="../../tutorials/how-to-process-list-of-offers-m09BKA5v8H3#list-of-offers" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<OffersRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Use this resource to get the list of the seller's offers. You can use different query parameters to filter the list. Read more: <a href="../../tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-pobrac-moje-oferty-w-rest-api" target="_blank">PL</a> / <a href="../../tutorials/how-to-process-list-of-offers-m09BKA5v8H3#list-of-offers" target="_blank">EN</a>.
 */
export interface OffersRequestBuilderGetQueryParameters {
    /**
     * The ID of return policy. Returns offers with given return policy ID.
     */
    afterSalesServicesReturnPolicyId?: Guid;
    /**
     * Allows to search for offers buyable only by businesses.
     */
    b2bBuyableOnlyByBusiness?: boolean;
    /**
     * The identifier of the category, where you want to search for offers.
     */
    categoryId?: string;
    /**
     * The ID of shipping rates. Returns offers with given shipping rates ID.
     */
    deliveryShippingRatesId?: Guid;
    /**
     * Allows to filter offers by existence of shipping rates ID.
     */
    deliveryShippingRatesIdEmpty?: boolean;
    /**
     * The ID from the client's external system. Passing more than one value will search for offers with any of the given IDs. By default no ID is included. Example: `external.id=1233&external.id=1234` - returns offers with ID `1233` or `1234`. Single ID length shouldn't exceed 100 characters.
     */
    externalId?: string[];
    /**
     * ID of the charity fundraising campaign that benefits from this offer.
     */
    fundraisingCampaignId?: Guid;
    /**
     * Allows to search for charity or commercial offers.
     */
    fundraisingCampaignIdEmpty?: boolean;
    /**
     * Allows to search for offers handled by the Allegro Warehouse (One Fulfillment).
     */
    isFulfillment?: boolean;
    /**
     * The maximum number of offers returned in the response.
     */
    limit?: number;
    /**
     * The text to search in the offer title.
     */
    name?: string;
    /**
     * Offer ID.
     */
    offerId?: string[];
    /**
     * Index of the first returned offer from all search results. Maximum sum of offset and limit is 10 000 000.
     */
    offset?: number;
    /**
     * Allows to filter offers by existence of product ID.
     */
    productIdEmpty?: boolean;
    /**
     * Allows to search for offers from categories where productization is required.
     */
    productizationRequired?: boolean;
    /**
     * Either the base marketplace or an additional marketplace of the offer.When passing the parameter `publication.marketplace`, searches for offers with the given marketplace as either its base marketplace or one of its additional marketplaces. When the parameter is omitted, searches for offers with all marketplaces.In addition to searching, passing the parameter also influences the functionality of other query parameter by searching and sorting by data (e.g. price) on the given marketplace.
     */
    publicationMarketplace?: string;
    /**
     * The publication status of the offer. Passing more than one value will search for offers with any of the given statuses. By default all statuses are included. Example: `publication.status=INACTIVE&publication.status=ACTIVE` - returns offers with status `INACTIVE` or `ACTIVE`.
     */
    publicationStatus?: GetPublicationStatusQueryParameterType[];
    /**
     * The offer's selling format. Passing more than one value will search for offers with any of the given formats. By default all formats are included. Example: `sellingMode.format=BUY_NOW&sellingMode.format=ADVERTISEMENT` - returns offers with with format `BUY_NOW` or `ADVERTISEMENT`.
     */
    sellingModeFormat?: GetSellingModeFormatQueryParameterType[];
    /**
     * The lower threshold of price.If additionally a `publication.marketplace` is provided, searches using the price on the given marketplace.
     */
    sellingModePriceAmountGte?: number;
    /**
     * The upper threshold of price.If additionally a `publication.marketplace` is provided, searches using the price on the given marketplace.
     */
    sellingModePriceAmountLte?: number;
    /**
     * The ID of price automation rule. Returns offers with given price automation rule ID.If additionally a `publication.marketplace` is provided, searches using the price automation rule on the given marketplace.
     */
    sellingModePriceAutomationRuleId?: string;
    /**
     * Allows to filter offers by existence of price automation rule ID. Passing 'false' will return offers with any price automation rule, passing 'true' will return offers without any price automation rules.If additionally a `publication.marketplace` is provided, searches using the price automation rule on the given marketplace.
     */
    sellingModePriceAutomationRuleIdEmpty?: boolean;
    /**
     * The results' sorting order. No prefix in the value means ascending order. `-` prefix means descending order. If you don't provide the sort parameter, the list is sorted by offer creation time, descending.If additionally a `publication.marketplace` is provided, sorts by price and `stock.sold` using the data on the given marketplace.
     */
    sort?: GetSortQueryParameterType;
}
/**
 * Uri template for the request builder.
 */
export const OffersRequestBuilderUriTemplate = "{+baseurl}/sale/offers{?afterSalesServices%2EreturnPolicy%2Eid*,b2b%2EbuyableOnlyByBusiness*,category%2Eid*,delivery%2EshippingRates%2Eid*,delivery%2EshippingRates%2Eid%2Eempty*,external%2Eid*,fundraisingCampaign%2Eid*,fundraisingCampaign%2Eid%2Eempty*,isFulfillment*,limit*,name*,offer%2Eid*,offset*,product%2Eid%2Eempty*,productizationRequired*,publication%2Emarketplace*,publication%2Estatus*,sellingMode%2Eformat*,sellingMode%2Eprice%2Eamount%2Egte*,sellingMode%2Eprice%2Eamount%2Elte*,sellingMode%2EpriceAutomation%2Erule%2Eid*,sellingMode%2EpriceAutomation%2Erule%2Eid%2Eempty*,sort*}";
export const GetPublicationStatusQueryParameterTypeObject = {
    INACTIVE: "INACTIVE",
    ACTIVE: "ACTIVE",
    ACTIVATING: "ACTIVATING",
    ENDED: "ENDED",
} as const;
export const GetSellingModeFormatQueryParameterTypeObject = {
    BUY_NOW: "BUY_NOW",
    ADVERTISEMENT: "ADVERTISEMENT",
    AUCTION: "AUCTION",
} as const;
export const GetSortQueryParameterTypeObject = {
    SellingModePriceAmount: "sellingMode.price.amount",
    Minus_sellingModePriceAmount: "-sellingMode.price.amount",
    StockSold: "stock.sold",
    Minus_stockSold: "-stock.sold",
    StockAvailable: "stock.available",
    Minus_stockAvailable: "-stock.available",
} as const;
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const OffersRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "afterSalesServicesReturnPolicyId": "afterSalesServices%2EreturnPolicy%2Eid",
    "b2bBuyableOnlyByBusiness": "b2b%2EbuyableOnlyByBusiness",
    "categoryId": "category%2Eid",
    "deliveryShippingRatesId": "delivery%2EshippingRates%2Eid",
    "deliveryShippingRatesIdEmpty": "delivery%2EshippingRates%2Eid%2Eempty",
    "externalId": "external%2Eid",
    "fundraisingCampaignId": "fundraisingCampaign%2Eid",
    "fundraisingCampaignIdEmpty": "fundraisingCampaign%2Eid%2Eempty",
    "offerId": "offer%2Eid",
    "productIdEmpty": "product%2Eid%2Eempty",
    "publicationMarketplace": "publication%2Emarketplace",
    "publicationStatus": "publication%2Estatus",
    "sellingModeFormat": "sellingMode%2Eformat",
    "sellingModePriceAmountGte": "sellingMode%2Eprice%2Eamount%2Egte",
    "sellingModePriceAmountLte": "sellingMode%2Eprice%2Eamount%2Elte",
    "sellingModePriceAutomationRuleId": "sellingMode%2EpriceAutomation%2Erule%2Eid",
    "sellingModePriceAutomationRuleIdEmpty": "sellingMode%2EpriceAutomation%2Erule%2Eid%2Eempty",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OffersRequestBuilderNavigationMetadata: Record<Exclude<keyof OffersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byOfferId: {
        requestsMetadata: WithOfferItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithOfferItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["offerId"],
    },
    promoOptions: {
        requestsMetadata: PromoOptionsRequestBuilderRequestsMetadata,
    },
    promoOptionsCommands: {
        navigationMetadata: PromoOptionsCommandsRequestBuilderNavigationMetadata,
    },
    unfilledParameters: {
        requestsMetadata: UnfilledParametersRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const OffersRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: OffersRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            400: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createOffersSearchResultDtoFromDiscriminatorValue,
        queryParametersMapper: OffersRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
