/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCategoryFromDiscriminatorValue, serializeCategory, type Category } from '../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WithIdPutRequestBody}
 */
// @ts-ignore
export function createWithIdPutRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWithIdPutRequestBody;
}
/**
 * The deserialization information for the current model
 * @param WithIdPutRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWithIdPutRequestBody(withIdPutRequestBody: Partial<WithIdPutRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "category": n => { withIdPutRequestBody.category = n.getObjectValue<Category>(createCategoryFromDiscriminatorValue); },
    }
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WithIdPutRequestBody The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWithIdPutRequestBody(writer: SerializationWriter, withIdPutRequestBody: Partial<WithIdPutRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!withIdPutRequestBody || isSerializingDerivedType) { return; }
    writer.writeObjectValue<Category>("category", withIdPutRequestBody.category, serializeCategory);
    writer.writeAdditionalData(withIdPutRequestBody.additionalData);
}
/**
 * Builds and executes requests for operations under /categories/{id}.json
 */
export interface WithIdJsonItemRequestBuilder extends BaseRequestBuilder<WithIdJsonItemRequestBuilder> {
    /**
     * Delete category
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Get category
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Category>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Category | undefined>;
    /**
     * Update category
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Category>}
     */
     put(body: WithIdPutRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Category | undefined>;
    /**
     * Delete category
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Get category
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Update category
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: WithIdPutRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface WithIdPutRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The category property
     */
    category?: Category | null;
}
/**
 * Uri template for the request builder.
 */
export const WithIdJsonItemRequestBuilderUriTemplate = "{+baseurl}/categories/{id}.json";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithIdJsonItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithIdJsonItemRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: WithIdJsonItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createCategoryFromDiscriminatorValue,
    },
    put: {
        uriTemplate: WithIdJsonItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createCategoryFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeWithIdPutRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
