/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFakturowniaGusLookupResponseFromDiscriminatorValue, serializeFakturowniaGusLookupRequest, serializeFakturowniaGusLookupResponse, type FakturowniaGusLookupRequest, type FakturowniaGusLookupResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /clients/gus_data.json
 */
export interface Gus_dataJsonRequestBuilder extends BaseRequestBuilder<Gus_dataJsonRequestBuilder> {
    /**
     * Undocumented endpoint used by the Fakturownia UI to fetch client datafrom the GUS/REGON registry by NIP, REGON, or KRS.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FakturowniaGusLookupResponse>}
     */
     post(body: FakturowniaGusLookupRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FakturowniaGusLookupResponse | undefined>;
    /**
     * Undocumented endpoint used by the Fakturownia UI to fetch client datafrom the GUS/REGON registry by NIP, REGON, or KRS.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: FakturowniaGusLookupRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Gus_dataJsonRequestBuilderUriTemplate = "{+baseurl}/clients/gus_data.json";
/**
 * Metadata for all the requests in the request builder.
 */
export const Gus_dataJsonRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Gus_dataJsonRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createFakturowniaGusLookupResponseFromDiscriminatorValue,
        requestBodyContentType: "application/x-www-form-urlencoded",
        requestBodySerializer: serializeFakturowniaGusLookupRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
