/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAuthErrorFromDiscriminatorValue, createError400FromDiscriminatorValue, createError403FromDiscriminatorValue, createError404FromDiscriminatorValue, createError504FromDiscriminatorValue, createPickupDtoFromDiscriminatorValue, serializeError400, serializeError403, serializeError404, serializeError504, type AuthError, type Error400, type Error403, type Error404, type Error504, type PickupDto } from '../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PickupDto400Error}
 */
// @ts-ignore
export function createPickupDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPickupDto400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PickupDto403Error}
 */
// @ts-ignore
export function createPickupDto403ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPickupDto403Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PickupDto404Error}
 */
// @ts-ignore
export function createPickupDto404ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPickupDto404Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PickupDto504Error}
 */
// @ts-ignore
export function createPickupDto504ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPickupDto504Error;
}
/**
 * The deserialization information for the current model
 * @param PickupDto400Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPickupDto400Error(pickupDto400Error: Partial<PickupDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "errors": n => { pickupDto400Error.errors = n.getCollectionOfObjectValues<Error400>(createError400FromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param PickupDto403Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPickupDto403Error(pickupDto403Error: Partial<PickupDto403Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "errors": n => { pickupDto403Error.errors = n.getCollectionOfObjectValues<Error403>(createError403FromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param PickupDto404Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPickupDto404Error(pickupDto404Error: Partial<PickupDto404Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "errors": n => { pickupDto404Error.errors = n.getCollectionOfObjectValues<Error404>(createError404FromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param PickupDto504Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPickupDto504Error(pickupDto504Error: Partial<PickupDto504Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "errors": n => { pickupDto504Error.errors = n.getCollectionOfObjectValues<Error504>(createError504FromDiscriminatorValue); },
    }
}
export interface PickupDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Array of errors.
     */
    errors?: Error400[] | null;
}
export interface PickupDto403Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Array of errors.
     */
    errors?: Error403[] | null;
}
export interface PickupDto404Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Array of errors.
     */
    errors?: Error404[] | null;
}
export interface PickupDto504Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Array of errors.
     */
    errors?: Error504[] | null;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PickupDto400Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePickupDto400Error(writer: SerializationWriter, pickupDto400Error: Partial<PickupDto400Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!pickupDto400Error || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<Error400>("errors", pickupDto400Error.errors, serializeError400);
    writer.writeAdditionalData(pickupDto400Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PickupDto403Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePickupDto403Error(writer: SerializationWriter, pickupDto403Error: Partial<PickupDto403Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!pickupDto403Error || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<Error403>("errors", pickupDto403Error.errors, serializeError403);
    writer.writeAdditionalData(pickupDto403Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PickupDto404Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePickupDto404Error(writer: SerializationWriter, pickupDto404Error: Partial<PickupDto404Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!pickupDto404Error || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<Error404>("errors", pickupDto404Error.errors, serializeError404);
    writer.writeAdditionalData(pickupDto404Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PickupDto504Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePickupDto504Error(writer: SerializationWriter, pickupDto504Error: Partial<PickupDto504Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!pickupDto504Error || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<Error504>("errors", pickupDto504Error.errors, serializeError504);
    writer.writeAdditionalData(pickupDto504Error.additionalData);
}
/**
 * Builds and executes requests for operations under /shipment-management/pickups/{pickupId}
 */
export interface WithPickupItemRequestBuilder extends BaseRequestBuilder<WithPickupItemRequestBuilder> {
    /**
     * Use this resource to get pickup details. Read more: <a href="../../tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-sprawdzic-status-zamowienia-odbioru-paczek" target="_blank">PL</a> / <a href="../../tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV#how-to-check-shipment-pickup-request-status" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PickupDto>}
     * @throws {PickupDto400Error} error when the service returns a 400 status code
     * @throws {AuthError} error when the service returns a 401 status code
     * @throws {PickupDto403Error} error when the service returns a 403 status code
     * @throws {PickupDto404Error} error when the service returns a 404 status code
     * @throws {PickupDto504Error} error when the service returns a 504 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PickupDto | undefined>;
    /**
     * Use this resource to get pickup details. Read more: <a href="../../tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-sprawdzic-status-zamowienia-odbioru-paczek" target="_blank">PL</a> / <a href="../../tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV#how-to-check-shipment-pickup-request-status" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithPickupItemRequestBuilderUriTemplate = "{+baseurl}/shipment-management/pickups/{pickupId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithPickupItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithPickupItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            400: createPickupDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAuthErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createPickupDto403ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createPickupDto404ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            504: createPickupDto504ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPickupDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
