/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ChangePriceCommandsRequestBuilderNavigationMetadata, type ChangePriceCommandsRequestBuilder } from './changePriceCommands/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /offers/{offerId}
 */
export interface WithOfferItemRequestBuilder extends BaseRequestBuilder<WithOfferItemRequestBuilder> {
    /**
     * The changePriceCommands property
     */
    get changePriceCommands(): ChangePriceCommandsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithOfferItemRequestBuilderUriTemplate = "{+baseurl}/offers/{offerId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithOfferItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithOfferItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    changePriceCommands: {
        navigationMetadata: ChangePriceCommandsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
