/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AdvanceShipNoticesRequestBuilderNavigationMetadata, AdvanceShipNoticesRequestBuilderRequestsMetadata, type AdvanceShipNoticesRequestBuilder } from './advanceShipNotices/index.js';
// @ts-ignore
import { AvailableProductsRequestBuilderRequestsMetadata, type AvailableProductsRequestBuilder } from './availableProducts/index.js';
// @ts-ignore
import { OrdersRequestBuilderNavigationMetadata, type OrdersRequestBuilder } from './orders/index.js';
// @ts-ignore
import { RemovalRequestBuilderNavigationMetadata, type RemovalRequestBuilder } from './removal/index.js';
// @ts-ignore
import { StockRequestBuilderRequestsMetadata, type StockRequestBuilder } from './stock/index.js';
// @ts-ignore
import { SubmitCommandsRequestBuilderNavigationMetadata, type SubmitCommandsRequestBuilder } from './submitCommands/index.js';
// @ts-ignore
import { TaxIdRequestBuilderRequestsMetadata, type TaxIdRequestBuilder } from './taxId/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /fulfillment
 */
export interface FulfillmentRequestBuilder extends BaseRequestBuilder<FulfillmentRequestBuilder> {
    /**
     * The advanceShipNotices property
     */
    get advanceShipNotices(): AdvanceShipNoticesRequestBuilder;
    /**
     * The availableProducts property
     */
    get availableProducts(): AvailableProductsRequestBuilder;
    /**
     * The orders property
     */
    get orders(): OrdersRequestBuilder;
    /**
     * The removal property
     */
    get removal(): RemovalRequestBuilder;
    /**
     * The stock property
     */
    get stock(): StockRequestBuilder;
    /**
     * The submitCommands property
     */
    get submitCommands(): SubmitCommandsRequestBuilder;
    /**
     * The taxId property
     */
    get taxId(): TaxIdRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const FulfillmentRequestBuilderUriTemplate = "{+baseurl}/fulfillment";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const FulfillmentRequestBuilderNavigationMetadata: Record<Exclude<keyof FulfillmentRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    advanceShipNotices: {
        requestsMetadata: AdvanceShipNoticesRequestBuilderRequestsMetadata,
        navigationMetadata: AdvanceShipNoticesRequestBuilderNavigationMetadata,
    },
    availableProducts: {
        requestsMetadata: AvailableProductsRequestBuilderRequestsMetadata,
    },
    orders: {
        navigationMetadata: OrdersRequestBuilderNavigationMetadata,
    },
    removal: {
        navigationMetadata: RemovalRequestBuilderNavigationMetadata,
    },
    stock: {
        requestsMetadata: StockRequestBuilderRequestsMetadata,
    },
    submitCommands: {
        navigationMetadata: SubmitCommandsRequestBuilderNavigationMetadata,
    },
    taxId: {
        requestsMetadata: TaxIdRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
