/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithOperationItemRequestBuilder, WithOperationItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /sale/product-offers/{offerId}/operations
 */
export interface OperationsRequestBuilder extends BaseRequestBuilder<OperationsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.sale.productOffers.item.operations.item collection
     * @param operationId Operation identifier provided in location header of POST or PATCH request.
     * @returns {WithOperationItemRequestBuilder}
     */
     byOperationId(operationId: string) : WithOperationItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const OperationsRequestBuilderUriTemplate = "{+baseurl}/sale/product-offers/{offerId}/operations";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OperationsRequestBuilderNavigationMetadata: Record<Exclude<keyof OperationsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byOperationId: {
        requestsMetadata: WithOperationItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["operationId"],
    },
};
/* tslint:enable */
/* eslint-enable */
