/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAuthErrorFromDiscriminatorValue, createErrorsHolderFromDiscriminatorValue, createOfferBundleDTOFromDiscriminatorValue, serializeOfferBundleDTO, serializeUpdateOfferBundleDiscountDTO, type AuthError, type ErrorsHolder, type OfferBundleDTO, type UpdateOfferBundleDiscountDTO } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /sale/bundles/{bundleId}/discount
 */
export interface DiscountRequestBuilder extends BaseRequestBuilder<DiscountRequestBuilder> {
    /**
     * Use this resource to update discount per marketplaces associated with bundle specified by its unique identifier. This will override currently set discounts for all marketplaces, so the unchanged discounts also must be specified in request. In case discount for marketplace is not specified in request it will be deleted. Read more: <a href="../../tutorials/jak-zarzadzac-rabatami-promocjami-yPya2mj6zUP#zmien-rabat-przypisany-do-wybranego-zestawu" target="_blank">PL</a> / <a href="../../tutorials/how-to-manage-rebates-and-promotions-g05avdL0vT4#change-the-discount-for-the-selected-offer-bundle" target="_blank">EN</a>.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<OfferBundleDTO>}
     * @throws {ErrorsHolder} error when the service returns a 400 status code
     * @throws {AuthError} error when the service returns a 401 status code
     * @throws {ErrorsHolder} error when the service returns a 403 status code
     * @throws {ErrorsHolder} error when the service returns a 422 status code
     */
     put(body: UpdateOfferBundleDiscountDTO, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<OfferBundleDTO | undefined>;
    /**
     * Use this resource to update discount per marketplaces associated with bundle specified by its unique identifier. This will override currently set discounts for all marketplaces, so the unchanged discounts also must be specified in request. In case discount for marketplace is not specified in request it will be deleted. Read more: <a href="../../tutorials/jak-zarzadzac-rabatami-promocjami-yPya2mj6zUP#zmien-rabat-przypisany-do-wybranego-zestawu" target="_blank">PL</a> / <a href="../../tutorials/how-to-manage-rebates-and-promotions-g05avdL0vT4#change-the-discount-for-the-selected-offer-bundle" target="_blank">EN</a>.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UpdateOfferBundleDiscountDTO, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DiscountRequestBuilderUriTemplate = "{+baseurl}/sale/bundles/{bundleId}/discount";
/**
 * Metadata for all the requests in the request builder.
 */
export const DiscountRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: DiscountRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            400: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAuthErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createOfferBundleDTOFromDiscriminatorValue,
        requestBodyContentType: "application/vnd.allegro.public.v1+json",
        requestBodySerializer: serializeUpdateOfferBundleDiscountDTO,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
