import type { LucideIcon } from "lucide-react";
import {
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  BadgeQuestionMark,
  BadgeDollarSign,
  BadgePlus,
  Ban,
  Banknote,
  ArrowUpDown,
  Bike,
  Beaker,
  Bell,
  BellRing,
  Blocks,
  Bolt,
  BookCheck,
  BookMarked,
  BookmarkPlus,
  Box,
  Brain,
  Braces,
  Brush,
  Bug,
  Building2,
  Calculator,
  Calendar1,
  CalendarCheck,
  CalendarDays,
  ChartColumn,
  ChartScatter,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsDown,
  ChevronsDownUp,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleMinus,
  CirclePlus,
  CloudDownload,
  CloudUpload,
  Clipboard,
  ClipboardCheck,
  ClipboardPenLine,
  Contact,
  CornerDownRight,
  Copy,
  CreditCard,
  Crop,
  Cuboid,
  Database,
  Delete,
  DollarSign,
  Download,
  DraftingCompass,
  ExternalLink,
  Eye,
  EyeOff,
  Factory,
  File,
  FileBadge,
  FileBox,
  FilePen,
  FilePenLine,
  FileQuestionMark,
  FileSearch,
  FileText,
  Filter,
  Flag,
  FlaskConical,
  FlipHorizontal2,
  Folder,
  FolderKanban,
  FolderOpen,
  Fullscreen,
  FunnelX,
  Gavel,
  GitBranch,
  Globe,
  Grip,
  Headset,
  Heart,
  History,
  Home,
  House,
  Image,
  Images,
  Inbox,
  Info,
  Languages,
  Landmark,
  Layers,
  Layers2,
  LayoutGrid,
  LayoutList,
  Leaf,
  Lightbulb,
  Link,
  List,
  ListChecks,
  ListFilter,
  ListPlus,
  ListTodo,
  LoaderCircle,
  Lock,
  LockOpen,
  LogIn,
  LogOut,
  Mail,
  MailOpen,
  Map,
  MapPin,
  MailPlus,
  Megaphone,
  Menu,
  MessageCircle,
  MessageCircleWarning,
  MessageSquareQuote,
  Monitor,
  Moon,
  MoreVertical,
  Network,
  Newspaper,
  Minus,
  Package,
  PackageCheck,
  PaintbrushVertical,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  Paperclip,
  Play,
  Plus,
  Printer,
  Proportions,
  QrCode,
  Ratio,
  Receipt,
  RefreshCcw,
  RefreshCw,
  Repeat,
  Route,
  Ruler,
  Save,
  ScanEye,
  ScanBarcode,
  ScanLine,
  ScanSearch,
  Scale,
  Scissors,
  Scroll,
  Search,
  SearchX,
  Send,
  Settings,
  Settings2,
  Share,
  Share2,
  ShieldAlert,
  ShieldCheck,
  ShieldQuestionMark,
  ShieldUser,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Spline,
  Square,
  SquareDashed,
  SquareKanban,
  SquarePen,
  SquarePlus,
  Star,
  StepForward,
  StickyNote,
  Sun,
  TableProperties,
  Tag,
  ThumbsDown,
  ThumbsUp,
  Timer,
  TimerOff,
  ToggleRight,
  Trash,
  TriangleAlert,
  TrendingDown,
  TrendingUp,
  Truck,
  TruckElectric,
  Undo2,
  Upload,
  User,
  UserCog,
  UserPlus,
  UserSearch,
  Users,
  Video,
  Volume2,
  VolumeOff,
  WandSparkles,
  Warehouse,
  Wallet,
  Workflow,
  X,
  ZoomIn,
  ZoomOut,
  BanknoteArrowUp,
} from "lucide-react";
import { AiIcon } from "./AiIcon";

const MATERIAL_SYMBOL_TO_LUCIDE: Record<string, LucideIcon> = {
  outgoing_mail: MailOpen,
  paid: BanknoteArrowUp,
  group_add: Users,
  psychology_alt: Database,
  psychology: Brain,
  construction: Blocks,
  format_paint: PaintbrushVertical,
  currency_exchange: DollarSign,
  photo_library: Images,
  auto_fix_high: Layers2,
  thumb_up: ThumbsUp,
  thumb_down: ThumbsDown,
  event_upcoming: Calendar1,
  collapse_content: ChevronsDownUp,
  travel_explore: Globe,
  brush: Brush,
  admin_panel_settings: ShieldUser,
  replay: Repeat,
  fact_check: BookCheck,
  view_list: TableProperties,
  add_circle: CirclePlus,
  ios_share: Share2,
  publish: Share,
  data_object: Braces,
  polyline: Spline,
  progress_activity: LoaderCircle,
  fullscreen: Fullscreen,
  eye: Eye,
  workflow: Workflow,
  flask_conical: FlaskConical,
  add_business: Building2,
  account_circle: User,
  account_balance_wallet: Wallet,
  add: Plus,
  add_link: Link,
  add_photo_alternate: Image,
  add_shopping_cart: ShoppingCart,
  analytics: ChartColumn,
  approval: CheckCircle,
  archive: Archive,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_outward: ArrowUpRight,
  arrow_upward: ArrowUp,
  article: FileText,
  article_shortcut: FileText,
  aspect_ratio: Ratio,
  assignment_add: ListPlus,
  attach_file: Paperclip,
  attach_money: Banknote,
  attachment: Paperclip,
  auto_awesome: AiIcon,
  automation: LayoutList,
  autorenew: RefreshCw,
  backspace: Delete,
  badge: Contact,
  block: Ban,
  bolt: Bolt,
  box_add: Package,
  bug_report: Bug,
  build: Settings,
  calculate: Calculator,
  calendar_month: CalendarDays,
  calendar_today: CalendarDays,
  campaign: Megaphone,
  cancel: X,
  category: Tag,
  chat: MessageCircle,
  chat_add_on: MessageCircle,
  chat_bubble_outline: MessageCircle,
  check: Check,
  check_circle: CheckCircle,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  circle: Circle,
  close: X,
  cloud_download: CloudDownload,
  cloud_upload: CloudUpload,
  contacts: Users,
  content_copy: Copy,
  conversion_path: Link,
  create: SquarePen,
  crop: Crop,
  crop_square: SquareDashed,
  dark_mode: Moon,
  database: Database,
  date_range: CalendarDays,
  delete: Trash,
  delivery_truck_speed: TruckElectric,
  deployed_code: Cuboid,
  description: FileText,
  desktop_windows: Monitor,
  design_services: DraftingCompass,
  done_all: CheckCircle,
  download: Download,
  draft: FilePen,
  drafts: MailOpen,
  drag_indicator: Grip,
  draw: SquarePen,
  eco: Leaf,
  edit: SquarePen,
  edit_square: SquarePen,
  email: Mail,
  error: CircleAlert,
  event: CalendarDays,
  expand_content: LayoutGrid,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  file_present: Paperclip,
  files_present: FileText,
  filter_list: Filter,
  filter_alt: ListFilter,
  filter_alt_off: FunnelX,
  feedback: MessageCircleWarning,
  fiber_new: BadgePlus,
  flip_to_back: FlipHorizontal2,
  flag: Flag,
  folder: Folder,
  folder_open: FolderOpen,
  format_list_bulleted: List,
  format_quote: MessageSquareQuote,
  forum: MessageCircle,
  grid_view: LayoutGrid,
  groups: Users,
  high_quality: Proportions,
  history: History,
  home: Home,
  https: ShieldCheck,
  image: Image,
  image_search: FileSearch,
  inbox: Inbox,
  info: Info,
  insert_drive_file: File,
  insights: ChartColumn,
  inventory: Box,
  inventory_2: FileBox,
  keyboard_arrow_up: ChevronUp,
  keyboard_arrow_down: ChevronDown,
  keyboard_double_arrow_left: ChevronsLeft,
  keyboard_double_arrow_right: ChevronsRight,
  label: Tag,
  layers: Layers,
  left_panel_close: PanelLeftClose,
  left_panel_open: PanelLeftOpen,
  light_mode: Sun,
  lightbulb: Lightbulb,
  linear_scale: Ruler,
  link: Link,
  link_off: Ban,
  list: List,
  local_shipping: Truck,
  location_on: MapPin,
  lock: Lock,
  lock_open: LockOpen,
  login: LogIn,
  low_priority: ChevronsDown,
  logout: LogOut,
  mail: Mail,
  manufacturing: Factory,
  map: Map,
  menu: Menu,
  menu_open: Menu,
  model_training: AiIcon,
  money: Banknote,
  more_vert: MoreVertical,
  move_location: MapPin,
  network_intelligence: AiIcon,
  note: FilePen,
  note_add: FilePen,
  notifications: Bell,
  notification_important: BellRing,
  open_in_new: ExternalLink,
  orders: Package,
  package: Package,
  payment: CreditCard,
  payments: CreditCard,
  pending: Timer,
  pending_actions: List,
  person: User,
  person_add: UserPlus,
  person_alert: UserCog,
  person_check: User,
  person_edit: User,
  person_off: User,
  person_search: UserSearch,
  picture_as_pdf: FileText,
  pin_drop: MapPin,
  play_arrow: Play,
  playlist_add: List,
  preview: Eye,
  price_change: Banknote,
  print: Printer,
  priority_high: TriangleAlert,
  problem: CircleAlert,
  qr_code_scanner: QrCode,
  rate_review: ClipboardPenLine,
  receipt: Receipt,
  receipt_long: FileBadge,
  refresh: RefreshCw,
  remove_shopping_cart: ShoppingCart,
  request_quote: Receipt,
  restart_alt: RefreshCcw,
  right_panel_close: PanelRightClose,
  route: Route,
  rule: Settings,
  save: Save,
  schedule: Timer,
  science: Beaker,
  scale: Scale,
  search: Search,
  security: ShieldCheck,
  sell: Tag,
  send: Send,
  settings: Settings,
  shopping_bag: ShoppingBag,
  shopping_cart: ShoppingCart,
  shopping_cart_checkout: ShoppingCart,
  smartphone: Smartphone,
  square_foot: Ruler,
  star: Star,
  star_border: Star,
  steps: StepForward,
  straighten: Ruler,
  sticky_note_2: StickyNote,
  stop: Square,
  storefront: ShoppingBag,
  support_agent: Headset,
  summarize: FileText,
  swap_horiz: ArrowLeftRight,
  swap_vert: ArrowUpDown,
  sync: RefreshCw,
  sync_alt: RefreshCw,
  system_update_alt: Download,
  tag: Tag,
  task: ClipboardCheck,
  task_alt: CheckCircle,
  timer: Timer,
  timer_off: TimerOff,
  today: CalendarDays,
  toggle_on: ToggleRight,
  transform: RefreshCw,
  translate: Languages,
  trending_down: TrendingDown,
  trending_up: TrendingUp,
  tune: Settings,
  unfold_less: ChevronsUp,
  unfold_more: ChevronsDown,
  update: RefreshCw,
  upload: Upload,
  upload_file: Upload,
  verified: CheckCircle,
  verified_user: ShieldCheck,
  videocam: Video,
  view_in_ar: Cuboid,
  view_kanban: SquareKanban,
  view_module: LayoutGrid,
  visibility: Eye,
  visibility_off: EyeOff,
  volume_off: VolumeOff,
  volume_up: Volume2,
  wallet: Wallet,
  warning: TriangleAlert,
  zoom_in: ZoomIn,
  zoom_out: ZoomOut,
  wand_sparkles: WandSparkles,
  warehouse: Warehouse,
  edit_attributes: Settings2,
  token: FolderKanban,
  group: Users,
  account_tree: GitBranch,
  account_balance: Landmark,
  add_box: SquarePlus,
  add_card: CreditCard,
  amp_stories: Newspaper,
  barcode_scanner: ScanBarcode,
  share: Share2,
  assignment_return: PackageCheck,
  balance: Scale,
  bookmark_add: BookmarkPlus,
  bookmarks: BookMarked,
  domain: Globe,
  edit_note: StickyNote,
  favorite: Heart,
  forward_to_inbox: MailPlus,
  help: BadgeQuestionMark,
  help_outline: BadgeQuestionMark,
  home_max: House,
  palette: Palette,
  precision_manufacturing: Factory,
  remove: Minus,
  remove_circle_outline: CircleMinus,
  schema: Network,
  search_off: SearchX,
  subdirectory_arrow_right: CornerDownRight,
  undo: Undo2,
  quiz: BadgeQuestionMark,
  file_question_mark: FileQuestionMark,
  fluorescent: Sparkles,
  privacy_tip: ShieldAlert,
  gavel: Gavel,
  shield_question: ShieldQuestionMark,
  contact_page: Contact,
  content_cut: Scissors,
  credit_card: CreditCard,
  edit_document: FilePenLine,
  event_available: CalendarCheck,
  grain: Scroll,
  assignment: Clipboard,
  package_2: Package,
  pedal_bike: Bike,
  point_of_sale: BadgeDollarSign,
  checklist: ListChecks,
  checklist_rtl: ListChecks,
  library_add_check: ListTodo,
  scatter_plot: ChartScatter,
  stylus_laser_pointer: ScanLine,
  laundry: Shirt,
  images: Images,
  scan_eye: ScanEye,
  scan_search: ScanSearch,
};

const warnedMissingIcons = new Set<string>();

function normalizeMaterialSymbolName(name: string) {
  return name
    .trim()
    .toLowerCase()
    .replace(/[\s-]+/g, "_");
}

export function getLucideIconForMaterialSymbol(
  name: string | undefined,
): LucideIcon {
  const normalizedName = normalizeMaterialSymbolName(name ?? "");

  if (!normalizedName) {
    return CircleAlert;
  }

  const icon = MATERIAL_SYMBOL_TO_LUCIDE[normalizedName];

  if (icon) {
    return icon;
  }

  if (!warnedMissingIcons.has(normalizedName)) {
    warnedMissingIcons.add(normalizedName);
    console.warn(
      `[MaterialSymbol] No Lucide mapping found for "${name}". Falling back to CircleAlert.`,
    );
  }

  return CircleAlert;
}
