/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBadRequestResponseFromDiscriminatorValue, createErrorApiResponseFromDiscriminatorValue, createTemplatesResponseFromDiscriminatorValue, serializeTemplatePayload, type BadRequestResponse, type ErrorApiResponse, type TemplatePayload, type TemplatesResponse } from '../../../models/index.js';
// @ts-ignore
import { TemplatesItemRequestBuilderRequestsMetadata, type TemplatesItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

export type GetShippingTypeQueryParameterType = (typeof GetShippingTypeQueryParameterTypeObject)[keyof typeof GetShippingTypeQueryParameterTypeObject];
/**
 * Builds and executes requests for operations under /v1/user/templates
 */
export interface TemplatesRequestBuilder extends BaseRequestBuilder<TemplatesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.v1.user.templates.item collection
     * @param id Identyfikator szablonu.
     * @returns {TemplatesItemRequestBuilder}
     */
     byId(id: number) : TemplatesItemRequestBuilder;
    /**
     * Metoda służy do zwracania listy szablonów.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TemplatesResponse>}
     * @throws {BadRequestResponse} error when the service returns a 400 status code
     * @throws {ErrorApiResponse} error when the service returns a 403 status code
     */
     get(requestConfiguration?: RequestConfiguration<TemplatesRequestBuilderGetQueryParameters> | undefined) : Promise<TemplatesResponse | undefined>;
    /**
     * Dodawanie nowego szablonu
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ErrorApiResponse} error when the service returns a 403 status code
     */
     post(body: TemplatePayload, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Metoda służy do zwracania listy szablonów.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<TemplatesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Dodawanie nowego szablonu
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: TemplatePayload, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Metoda służy do zwracania listy szablonów.
 */
export interface TemplatesRequestBuilderGetQueryParameters {
    /**
     * Identyfikator kuriera
     */
    courierId?: number;
    /**
     * Identyfikator szablonu
     */
    id?: number;
    /**
     * Limit zwracanych płatności
     */
    limit?: number;
    /**
     * Offset do paginacji
     */
    offset?: number;
    /**
     * Tekst do do wyszukania w szablonie
     */
    query?: string;
    /**
     * Rodzaj wysyłki:<br/><strong>envelope</strong> - Koperta<br/><strong>package</strong> - Paczka<br/><strong>pallet</strong> - Paleta<br/><strong>tires</strong> - Opony<br/>
     */
    shippingType?: GetShippingTypeQueryParameterType;
}
/**
 * Uri template for the request builder.
 */
export const TemplatesRequestBuilderUriTemplate = "{+baseurl}/v1/user/templates{?courierId*,id*,limit*,offset*,query*,shippingType*}";
export const GetShippingTypeQueryParameterTypeObject = {
    Envelope: "envelope",
    PackageEscaped: "package",
    Pallet: "pallet",
    Tires: "tires",
} as const;
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TemplatesRequestBuilderNavigationMetadata: Record<Exclude<keyof TemplatesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: TemplatesItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const TemplatesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: TemplatesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBadRequestResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createTemplatesResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: TemplatesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            403: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeTemplatePayload,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
