/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AccountsRequestBuilderNavigationMetadata, type AccountsRequestBuilder } from './accounts/index.js';
// @ts-ignore
import { OffersRequestBuilderNavigationMetadata, type OffersRequestBuilder } from './offers/index.js';
// @ts-ignore
import { OffersQueriesRequestBuilderRequestsMetadata, type OffersQueriesRequestBuilder } from './offersQueries/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /sale/allegro-prices
 */
export interface AllegroPricesRequestBuilder extends BaseRequestBuilder<AllegroPricesRequestBuilder> {
    /**
     * The accounts property
     */
    get accounts(): AccountsRequestBuilder;
    /**
     * The offers property
     */
    get offers(): OffersRequestBuilder;
    /**
     * The offersQueries property
     */
    get offersQueries(): OffersQueriesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AllegroPricesRequestBuilderUriTemplate = "{+baseurl}/sale/allegro-prices";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AllegroPricesRequestBuilderNavigationMetadata: Record<Exclude<keyof AllegroPricesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    accounts: {
        navigationMetadata: AccountsRequestBuilderNavigationMetadata,
    },
    offers: {
        navigationMetadata: OffersRequestBuilderNavigationMetadata,
    },
    offersQueries: {
        requestsMetadata: OffersQueriesRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
