/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CreateCommandsRequestBuilderNavigationMetadata, CreateCommandsRequestBuilderRequestsMetadata, type CreateCommandsRequestBuilder } from './createCommands/index.js';
// @ts-ignore
import { type WithPickupItemRequestBuilder, WithPickupItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /shipment-management/pickups
 */
export interface PickupsRequestBuilder extends BaseRequestBuilder<PickupsRequestBuilder> {
    /**
     * The createCommands property
     */
    get createCommands(): CreateCommandsRequestBuilder;
    /**
     * Gets an item from the ApiSdk.shipmentManagement.pickups.item collection
     * @param pickupId Pickup ID.
     * @returns {WithPickupItemRequestBuilder}
     */
     byPickupId(pickupId: string) : WithPickupItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PickupsRequestBuilderUriTemplate = "{+baseurl}/shipment-management/pickups";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PickupsRequestBuilderNavigationMetadata: Record<Exclude<keyof PickupsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byPickupId: {
        requestsMetadata: WithPickupItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["pickupId"],
    },
    createCommands: {
        requestsMetadata: CreateCommandsRequestBuilderRequestsMetadata,
        navigationMetadata: CreateCommandsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
