/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ParcelsRequestBuilderRequestsMetadata, type ParcelsRequestBuilder } from './parcels/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /fulfillment/orders/{orderId}
 */
export interface WithOrderItemRequestBuilder extends BaseRequestBuilder<WithOrderItemRequestBuilder> {
    /**
     * The parcels property
     */
    get parcels(): ParcelsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithOrderItemRequestBuilderUriTemplate = "{+baseurl}/fulfillment/orders/{orderId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithOrderItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithOrderItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    parcels: {
        requestsMetadata: ParcelsRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
