/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBadRequestResponseFromDiscriminatorValue, createErrorApiResponseFromDiscriminatorValue, createPaymentDataFromDiscriminatorValue, type BadRequestResponse, type ErrorApiResponse, type PaymentData } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/user/orders/{id}/payment
 */
export interface PaymentRequestBuilder extends BaseRequestBuilder<PaymentRequestBuilder> {
    /**
     * Metoda służy do zwracania danych płatności za zamówienie.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PaymentData>}
     * @throws {BadRequestResponse} error when the service returns a 400 status code
     * @throws {ErrorApiResponse} error when the service returns a 403 status code
     * @throws {ErrorApiResponse} error when the service returns a 404 status code
     * @throws {ErrorApiResponse} error when the service returns a 409 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PaymentData | undefined>;
    /**
     * Metoda służy do zwracania danych płatności za zamówienie.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PaymentRequestBuilderUriTemplate = "{+baseurl}/v1/user/orders/{id}/payment";
/**
 * Metadata for all the requests in the request builder.
 */
export const PaymentRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PaymentRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBadRequestResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPaymentDataFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
