/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithIdJsonItemRequestBuilder, WithIdJsonItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /departments
 */
export interface DepartmentsRequestBuilder extends BaseRequestBuilder<DepartmentsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.departments.item collection
     * @param idJson Unique identifier of the item
     * @returns {WithIdJsonItemRequestBuilder}
     */
     byIdJson(idJson: string) : WithIdJsonItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const DepartmentsRequestBuilderUriTemplate = "{+baseurl}/departments";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DepartmentsRequestBuilderNavigationMetadata: Record<Exclude<keyof DepartmentsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byIdJson: {
        requestsMetadata: WithIdJsonItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/* tslint:enable */
/* eslint-enable */
