/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CancelCommandsRequestBuilderNavigationMetadata, CancelCommandsRequestBuilderRequestsMetadata, type CancelCommandsRequestBuilder } from './cancelCommands/index.js';
// @ts-ignore
import { CreateCommandsRequestBuilderNavigationMetadata, CreateCommandsRequestBuilderRequestsMetadata, type CreateCommandsRequestBuilder } from './createCommands/index.js';
// @ts-ignore
import { type WithShipmentItemRequestBuilder, WithShipmentItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /shipment-management/shipments
 */
export interface ShipmentsRequestBuilder extends BaseRequestBuilder<ShipmentsRequestBuilder> {
    /**
     * The cancelCommands property
     */
    get cancelCommands(): CancelCommandsRequestBuilder;
    /**
     * The createCommands property
     */
    get createCommands(): CreateCommandsRequestBuilder;
    /**
     * Gets an item from the ApiSdk.shipmentManagement.shipments.item collection
     * @param shipmentId Shipment id.
     * @returns {WithShipmentItemRequestBuilder}
     */
     byShipmentId(shipmentId: string) : WithShipmentItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ShipmentsRequestBuilderUriTemplate = "{+baseurl}/shipment-management/shipments";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ShipmentsRequestBuilderNavigationMetadata: Record<Exclude<keyof ShipmentsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byShipmentId: {
        requestsMetadata: WithShipmentItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["shipmentId"],
    },
    cancelCommands: {
        requestsMetadata: CancelCommandsRequestBuilderRequestsMetadata,
        navigationMetadata: CancelCommandsRequestBuilderNavigationMetadata,
    },
    createCommands: {
        requestsMetadata: CreateCommandsRequestBuilderRequestsMetadata,
        navigationMetadata: CreateCommandsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
