/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAuthErrorFromDiscriminatorValue, createErrorsHolderFromDiscriminatorValue, createMaxPriceFromDiscriminatorValue, createMyBidResponseFromDiscriminatorValue, serializeMaxPrice, serializeMyBidResponse, type AuthError, type ErrorsHolder, type MaxPrice, type MyBidResponse } from '../../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * The bid request.
 */
export interface BidPutRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * Maximum amount that user is willing to pay for the auction.
     */
    maxAmount?: MaxPrice | null;
}
/**
 * Builds and executes requests for operations under /bidding/offers/{offerId}/bid
 */
export interface BidRequestBuilder extends BaseRequestBuilder<BidRequestBuilder> {
    /**
     * Get current user's bid information. Read more: <a href="../../news/nowe-zasoby-zloz-oferte-kupna-w-licytacji-q018m02vDT1" target="_blank">PL</a> / <a href="../../news/new-resources-place-a-bid-in-an-auction-rjWwEj1e7sG" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MyBidResponse>}
     * @throws {ErrorsHolder} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MyBidResponse | undefined>;
    /**
     * Place a bid in an auction. Read more: <a href="../../news/nowe-zasoby-zloz-oferte-kupna-w-licytacji-q018m02vDT1" target="_blank">PL</a> / <a href="../../news/new-resources-place-a-bid-in-an-auction-rjWwEj1e7sG" target="_blank">EN</a>.
     * @param body The bid request.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MyBidResponse>}
     * @throws {ErrorsHolder} error when the service returns a 400 status code
     * @throws {AuthError} error when the service returns a 401 status code
     * @throws {ErrorsHolder} error when the service returns a 404 status code
     * @throws {ErrorsHolder} error when the service returns a 422 status code
     */
     put(body: BidPutRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MyBidResponse | undefined>;
    /**
     * Get current user's bid information. Read more: <a href="../../news/nowe-zasoby-zloz-oferte-kupna-w-licytacji-q018m02vDT1" target="_blank">PL</a> / <a href="../../news/new-resources-place-a-bid-in-an-auction-rjWwEj1e7sG" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Place a bid in an auction. Read more: <a href="../../news/nowe-zasoby-zloz-oferte-kupna-w-licytacji-q018m02vDT1" target="_blank">PL</a> / <a href="../../news/new-resources-place-a-bid-in-an-auction-rjWwEj1e7sG" target="_blank">EN</a>.
     * @param body The bid request.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: BidPutRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {BidPutRequestBody}
 */
// @ts-ignore
export function createBidPutRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoBidPutRequestBody;
}
/**
 * The deserialization information for the current model
 * @param BidPutRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoBidPutRequestBody(bidPutRequestBody: Partial<BidPutRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "maxAmount": n => { bidPutRequestBody.maxAmount = n.getObjectValue<MaxPrice>(createMaxPriceFromDiscriminatorValue); },
    }
}
/**
 * Serializes information the current object
 * @param BidPutRequestBody The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeBidPutRequestBody(writer: SerializationWriter, bidPutRequestBody: Partial<BidPutRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!bidPutRequestBody || isSerializingDerivedType) { return; }
    writer.writeObjectValue<MaxPrice>("maxAmount", bidPutRequestBody.maxAmount, serializeMaxPrice);
    writer.writeAdditionalData(bidPutRequestBody.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const BidRequestBuilderUriTemplate = "{+baseurl}/bidding/offers/{offerId}/bid";
/**
 * Metadata for all the requests in the request builder.
 */
export const BidRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: BidRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            404: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createMyBidResponseFromDiscriminatorValue,
    },
    put: {
        uriTemplate: BidRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            400: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAuthErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createMyBidResponseFromDiscriminatorValue,
        requestBodyContentType: "application/vnd.allegro.public.v1+json",
        requestBodySerializer: serializeBidPutRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
