/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { PromoOptionsRequestBuilderRequestsMetadata, type PromoOptionsRequestBuilder } from './promoOptions/index.js';
// @ts-ignore
import { PromoOptionsModificationRequestBuilderRequestsMetadata, type PromoOptionsModificationRequestBuilder } from './promoOptionsModification/index.js';
// @ts-ignore
import { RatingRequestBuilderRequestsMetadata, type RatingRequestBuilder } from './rating/index.js';
// @ts-ignore
import { SmartRequestBuilderRequestsMetadata, type SmartRequestBuilder } from './smart/index.js';
// @ts-ignore
import { TagsRequestBuilderRequestsMetadata, type TagsRequestBuilder } from './tags/index.js';
// @ts-ignore
import { TranslationsRequestBuilderNavigationMetadata, TranslationsRequestBuilderRequestsMetadata, type TranslationsRequestBuilder } from './translations/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /sale/offers/{offerId}
 */
export interface WithOfferItemRequestBuilder extends BaseRequestBuilder<WithOfferItemRequestBuilder> {
    /**
     * The promoOptions property
     */
    get promoOptions(): PromoOptionsRequestBuilder;
    /**
     * The promoOptionsModification property
     */
    get promoOptionsModification(): PromoOptionsModificationRequestBuilder;
    /**
     * The rating property
     */
    get rating(): RatingRequestBuilder;
    /**
     * The smart property
     */
    get smart(): SmartRequestBuilder;
    /**
     * The tags property
     */
    get tags(): TagsRequestBuilder;
    /**
     * The translations property
     */
    get translations(): TranslationsRequestBuilder;
    /**
     * Use this resource to delete a draft offer. Read more: <a href="../../tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#szkic-oferty" target="_blank">PL</a> / <a href="../../tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#inactive-status" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Use this resource to delete a draft offer. Read more: <a href="../../tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#szkic-oferty" target="_blank">PL</a> / <a href="../../tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#inactive-status" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithOfferItemRequestBuilderUriTemplate = "{+baseurl}/sale/offers/{offerId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithOfferItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithOfferItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    promoOptions: {
        requestsMetadata: PromoOptionsRequestBuilderRequestsMetadata,
    },
    promoOptionsModification: {
        requestsMetadata: PromoOptionsModificationRequestBuilderRequestsMetadata,
    },
    rating: {
        requestsMetadata: RatingRequestBuilderRequestsMetadata,
    },
    smart: {
        requestsMetadata: SmartRequestBuilderRequestsMetadata,
    },
    tags: {
        requestsMetadata: TagsRequestBuilderRequestsMetadata,
    },
    translations: {
        requestsMetadata: TranslationsRequestBuilderRequestsMetadata,
        navigationMetadata: TranslationsRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithOfferItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithOfferItemRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
    },
};
/* tslint:enable */
/* eslint-enable */
