/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBadRequestResponseFromDiscriminatorValue, createCodTypesResponseFromDiscriminatorValue, createErrorApiResponseFromDiscriminatorValue, type BadRequestResponse, type CodTypesResponse, type ErrorApiResponse } from '../../../../models/index.js';
// @ts-ignore
import { PricesRequestBuilderRequestsMetadata, type PricesRequestBuilder } from './prices/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/order/services/cod
 */
export interface CodRequestBuilder extends BaseRequestBuilder<CodRequestBuilder> {
    /**
     * The prices property
     */
    get prices(): PricesRequestBuilder;
    /**
     * Metoda służy do pobrania listy dostępnych rodzajów pobrania, dla użytkownika.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CodTypesResponse>}
     * @throws {BadRequestResponse} error when the service returns a 400 status code
     * @throws {ErrorApiResponse} error when the service returns a 403 status code
     */
     get(requestConfiguration?: RequestConfiguration<CodRequestBuilderGetQueryParameters> | undefined) : Promise<CodTypesResponse | undefined>;
    /**
     * Metoda służy do pobrania listy dostępnych rodzajów pobrania, dla użytkownika.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<CodRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Metoda służy do pobrania listy dostępnych rodzajów pobrania, dla użytkownika.
 */
export interface CodRequestBuilderGetQueryParameters {
    /**
     * Id kuriera
     */
    courierId?: number;
    /**
     * Rodzaj pobrania:<br/><strong>account</strong> - Zwrot pobrania na konto bankowe lub saldo<br/><strong>cash</strong> - Zwrot pobrania w punkcie epaka.pl<br/>
     */
    returnType?: GetReturnTypeQueryParameterType;
}
export type GetReturnTypeQueryParameterType = (typeof GetReturnTypeQueryParameterTypeObject)[keyof typeof GetReturnTypeQueryParameterTypeObject];
/**
 * Uri template for the request builder.
 */
export const CodRequestBuilderUriTemplate = "{+baseurl}/v1/order/services/cod?courierId={courierId}{&returnType*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CodRequestBuilderNavigationMetadata: Record<Exclude<keyof CodRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    prices: {
        requestsMetadata: PricesRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const CodRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: CodRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBadRequestResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCodTypesResponseFromDiscriminatorValue,
    },
};
export const GetReturnTypeQueryParameterTypeObject = {
    Account: "account",
    Cash: "cash",
} as const;
/* tslint:enable */
/* eslint-enable */
