/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAuthErrorFromDiscriminatorValue, createErrorsHolderFromDiscriminatorValue, createOfferTranslationsFromDiscriminatorValue, type AuthError, type ErrorsHolder, type OfferTranslations } from '../../../../models/index.js';
// @ts-ignore
import { type WithLanguageItemRequestBuilder, WithLanguageItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /sale/offers/{offerId}/translations
 */
export interface TranslationsRequestBuilder extends BaseRequestBuilder<TranslationsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.sale.offers.item.translations.item collection
     * @param language Language of the provided translation.
     * @returns {WithLanguageItemRequestBuilder}
     */
     byLanguage(language: string) : WithLanguageItemRequestBuilder;
    /**
     * Get offer translation for given language or all present. Read more: <a href="../../tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#tlumaczenia-ofert" target="_blank">PL</a> / <a href="../../tutorials/how-to-process-list-of-offers-m09BKA5v8H3#offer-translations" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<OfferTranslations>}
     * @throws {AuthError} error when the service returns a 401 status code
     * @throws {ErrorsHolder} error when the service returns a 403 status code
     * @throws {ErrorsHolder} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<TranslationsRequestBuilderGetQueryParameters> | undefined) : Promise<OfferTranslations | undefined>;
    /**
     * Get offer translation for given language or all present. Read more: <a href="../../tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#tlumaczenia-ofert" target="_blank">PL</a> / <a href="../../tutorials/how-to-process-list-of-offers-m09BKA5v8H3#offer-translations" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<TranslationsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Get offer translation for given language or all present. Read more: <a href="../../tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#tlumaczenia-ofert" target="_blank">PL</a> / <a href="../../tutorials/how-to-process-list-of-offers-m09BKA5v8H3#offer-translations" target="_blank">EN</a>.
 */
export interface TranslationsRequestBuilderGetQueryParameters {
    /**
     * Language for translation to retrieve. If not provided, all translations as well as base content for offer will be returned.
     */
    language?: string;
}
/**
 * Uri template for the request builder.
 */
export const TranslationsRequestBuilderUriTemplate = "{+baseurl}/sale/offers/{offerId}/translations{?language*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TranslationsRequestBuilderNavigationMetadata: Record<Exclude<keyof TranslationsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byLanguage: {
        requestsMetadata: WithLanguageItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["language"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const TranslationsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: TranslationsRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            401: createAuthErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createOfferTranslationsFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
