/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAuthErrorFromDiscriminatorValue, createCustomerReturnFromDiscriminatorValue, createErrorsHolderFromDiscriminatorValue, type AuthError, type CustomerReturn, type ErrorsHolder } from '../../../models/index.js';
// @ts-ignore
import { RejectionRequestBuilderRequestsMetadata, type RejectionRequestBuilder } from './rejection/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /order/customer-returns/{customerReturnId}
 */
export interface WithCustomerReturnItemRequestBuilder extends BaseRequestBuilder<WithCustomerReturnItemRequestBuilder> {
    /**
     * The rejection property
     */
    get rejection(): RejectionRequestBuilder;
    /**
     * Use this resource to get customer returns by its identifier. Read more: <a href="../../tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#jak-pobrac-szczegolowe-informacje-o-zwrocie" target="_blank">PL</a> / <a href="../../tutorials/process-orders-PgPMlWDr8Cv#how-to-retrieve-detailed-information-about-customer-return" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CustomerReturn>}
     * @throws {ErrorsHolder} error when the service returns a 400 status code
     * @throws {AuthError} error when the service returns a 401 status code
     * @throws {ErrorsHolder} error when the service returns a 403 status code
     * @throws {ErrorsHolder} error when the service returns a 404 status code
     * @throws {ErrorsHolder} error when the service returns a 406 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CustomerReturn | undefined>;
    /**
     * Use this resource to get customer returns by its identifier. Read more: <a href="../../tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#jak-pobrac-szczegolowe-informacje-o-zwrocie" target="_blank">PL</a> / <a href="../../tutorials/process-orders-PgPMlWDr8Cv#how-to-retrieve-detailed-information-about-customer-return" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithCustomerReturnItemRequestBuilderUriTemplate = "{+baseurl}/order/customer-returns/{customerReturnId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithCustomerReturnItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithCustomerReturnItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    rejection: {
        requestsMetadata: RejectionRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithCustomerReturnItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithCustomerReturnItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.beta.v1+json",
        errorMappings: {
            400: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAuthErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            406: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCustomerReturnFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
