/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPostPurchaseIssueListResponseFromDiscriminatorValue, PostPurchaseIssueStatus, type PostPurchaseIssueListResponse } from '../../models/index.js';
// @ts-ignore
import { AttachmentsRequestBuilderNavigationMetadata, AttachmentsRequestBuilderRequestsMetadata, type AttachmentsRequestBuilder } from './attachments/index.js';
// @ts-ignore
import { type WithIssueItemRequestBuilder, WithIssueItemRequestBuilderNavigationMetadata, WithIssueItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /sale/issues
 */
export interface IssuesRequestBuilder extends BaseRequestBuilder<IssuesRequestBuilder> {
    /**
     * The attachments property
     */
    get attachments(): AttachmentsRequestBuilder;
    /**
     * Gets an item from the ApiSdk.sale.issues.item collection
     * @param issueId Dispute or claim identifier.
     * @returns {WithIssueItemRequestBuilder}
     */
     byIssueId(issueId: Guid) : WithIssueItemRequestBuilder;
    /**
     * Use this resource to get the list of your disputes and claims ordered by descending opened date. Read more: <a href="../../tutorials/jak-zarzadzac-dyskusjami-E7Zj6gK7ysE#lista-dyskusji-i-reklamacji-na-koncie" target="_blank">PL</a> / <a href="../../tutorials/how-to-manage-discussions-VL6Yr40e5t5#all-disputes-and-claims" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PostPurchaseIssueListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<IssuesRequestBuilderGetQueryParameters> | undefined) : Promise<PostPurchaseIssueListResponse | undefined>;
    /**
     * Use this resource to get the list of your disputes and claims ordered by descending opened date. Read more: <a href="../../tutorials/jak-zarzadzac-dyskusjami-E7Zj6gK7ysE#lista-dyskusji-i-reklamacji-na-koncie" target="_blank">PL</a> / <a href="../../tutorials/how-to-manage-discussions-VL6Yr40e5t5#all-disputes-and-claims" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<IssuesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Use this resource to get the list of your disputes and claims ordered by descending opened date. Read more: <a href="../../tutorials/jak-zarzadzac-dyskusjami-E7Zj6gK7ysE#lista-dyskusji-i-reklamacji-na-koncie" target="_blank">PL</a> / <a href="../../tutorials/how-to-manage-discussions-VL6Yr40e5t5#all-disputes-and-claims" target="_blank">EN</a>.
 */
export interface IssuesRequestBuilderGetQueryParameters {
    /**
     * Checkout form identifier.
     */
    checkoutFormId?: Guid;
    /**
     * The maximum number of issues in a response.
     */
    limit?: number;
    /**
     * Index of first returned issue.
     */
    offset?: number;
    /**
     * Filter issues with given set of statuses.
     */
    status?: PostPurchaseIssueStatus[];
}
/**
 * Uri template for the request builder.
 */
export const IssuesRequestBuilderUriTemplate = "{+baseurl}/sale/issues{?checkoutForm%2Eid*,limit*,offset*,status*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const IssuesRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "checkoutFormId": "checkoutForm%2Eid",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const IssuesRequestBuilderNavigationMetadata: Record<Exclude<keyof IssuesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byIssueId: {
        requestsMetadata: WithIssueItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithIssueItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["issueId"],
    },
    attachments: {
        requestsMetadata: AttachmentsRequestBuilderRequestsMetadata,
        navigationMetadata: AttachmentsRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const IssuesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: IssuesRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.beta.v1+json",
        adapterMethodName: "send",
        responseBodyFactory:  createPostPurchaseIssueListResponseFromDiscriminatorValue,
        queryParametersMapper: IssuesRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
