/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAuthErrorFromDiscriminatorValue, createBadgeOperationFromDiscriminatorValue, createErrorsHolderFromDiscriminatorValue, type AuthError, type BadgeOperation, type ErrorsHolder } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /sale/badge-operations/{operationId}
 */
export interface WithOperationItemRequestBuilder extends BaseRequestBuilder<WithOperationItemRequestBuilder> {
    /**
     * Use this resource to get badge operation details. Read more: <a href="../../tutorials/jak-przypisac-oferte-kampanii-GRaj0q6Gwuy#zmiana-ceny-i-zakonczenie-oznaczenia" target="_blank">PL</a> / <a href="../../tutorials/how-to-submit-offers-to-campaigns-AgGjd6EmyH4#change-price-and-finish-badge" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BadgeOperation>}
     * @throws {AuthError} error when the service returns a 401 status code
     * @throws {ErrorsHolder} error when the service returns a 403 status code
     * @throws {ErrorsHolder} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<BadgeOperation | undefined>;
    /**
     * Use this resource to get badge operation details. Read more: <a href="../../tutorials/jak-przypisac-oferte-kampanii-GRaj0q6Gwuy#zmiana-ceny-i-zakonczenie-oznaczenia" target="_blank">PL</a> / <a href="../../tutorials/how-to-submit-offers-to-campaigns-AgGjd6EmyH4#change-price-and-finish-badge" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithOperationItemRequestBuilderUriTemplate = "{+baseurl}/sale/badge-operations/{operationId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithOperationItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithOperationItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            401: createAuthErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createBadgeOperationFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
