/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createVariantSetResponseFromDiscriminatorValue, createVariantSetsFromDiscriminatorValue, serializeVariantSet, serializeVariantSetResponse, type VariantSet, type VariantSetResponse, type VariantSets } from '../../models/index.js';
// @ts-ignore
import { type WithSetItemRequestBuilder, WithSetItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /sale/offer-variants
 */
export interface OfferVariantsRequestBuilder extends BaseRequestBuilder<OfferVariantsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.sale.offerVariants.item collection
     * @param setId Variant set identifier.
     * @returns {WithSetItemRequestBuilder}
     * @deprecated 
     */
     bySetId(setId: string) : WithSetItemRequestBuilder;
    /**
     * Use this resource to get created variant sets. The returned variant sets are ordered by name. Read more: <a href="../../tutorials/jak-utworzyc-oferte-wielowariantowa-oA6ZYBg5XFo#pobierz-liste-ofert-wielowariantowych" target="_blank">PL</a> / <a href="../../tutorials/how-to-create-a-multi-variant-offer-nn9DOL3nXs2#retrieve-a-multi-variant-offer" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<VariantSets>}
     * @deprecated 
     */
     get(requestConfiguration?: RequestConfiguration<OfferVariantsRequestBuilderGetQueryParameters> | undefined) : Promise<VariantSets | undefined>;
    /**
     * Use this resource to create variant set. A valid variant set must consist of three required elements: - name:   - it can't be blank and must not be longer than 75 characters - parameters:   - it should contain parameter identifiers used for offer grouping   - parameter identifiers from the offers and special `color/pattern` value (for grouping via image) are permitted   - it must contain at least one element (up to 2) - offers:   - it must contain at least 2 offers (500 at most)   - `colorPattern` value must be set for every offer if `color/pattern` parameter is used   - `colorPattern` value can't be blank and must not be longer than 50 characters   - `colorPattern` can take arbitrary string value like `red`, `b323592c-522f-4ec1-b9ea-3764538e0ac4` (UUID), etc.   - offers having the same image should have identical `colorPattern` value   - offers must have `publication.marketplaces.base` equal to `allegro-pl` Let's assume we have 4 offers:   - offer with id 2 having an image of a red t-shirt and S as a value of parameter with id 21   - offer with id 3 having an image of a red t-shirt and M as a value of parameter with id 21   - offer with id 4 having an image of a blue t-shirt and S as a value of parameter with id 21   - offer with id 5 having an image of a blue t-shirt and M as a value of parameter with id 21 You can build a variant set by grouping offers using combination of available parameters - examples are available in <i>Request samples</i>. More general information about variant sets can be found [here](https://allegro.pl/pomoc/faq/wielowariantowosc-jak-polaczyc-oferty-xGgaOByGgTb#dodatkowe-informacje). Read more: <a href="../../tutorials/jak-utworzyc-oferte-wielowariantowa-oA6ZYBg5XFo#utworz-oferte-wielowariantowa" target="_blank">PL</a> / <a href="../../tutorials/how-to-create-a-multi-variant-offer-nn9DOL3nXs2#create-a-multi-variant-offer" target="_blank">EN</a>.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<VariantSetResponse>}
     * @deprecated 
     */
     post(body: VariantSet, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<VariantSetResponse | undefined>;
    /**
     * Use this resource to get created variant sets. The returned variant sets are ordered by name. Read more: <a href="../../tutorials/jak-utworzyc-oferte-wielowariantowa-oA6ZYBg5XFo#pobierz-liste-ofert-wielowariantowych" target="_blank">PL</a> / <a href="../../tutorials/how-to-create-a-multi-variant-offer-nn9DOL3nXs2#retrieve-a-multi-variant-offer" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     * @deprecated 
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<OfferVariantsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Use this resource to create variant set. A valid variant set must consist of three required elements: - name:   - it can't be blank and must not be longer than 75 characters - parameters:   - it should contain parameter identifiers used for offer grouping   - parameter identifiers from the offers and special `color/pattern` value (for grouping via image) are permitted   - it must contain at least one element (up to 2) - offers:   - it must contain at least 2 offers (500 at most)   - `colorPattern` value must be set for every offer if `color/pattern` parameter is used   - `colorPattern` value can't be blank and must not be longer than 50 characters   - `colorPattern` can take arbitrary string value like `red`, `b323592c-522f-4ec1-b9ea-3764538e0ac4` (UUID), etc.   - offers having the same image should have identical `colorPattern` value   - offers must have `publication.marketplaces.base` equal to `allegro-pl` Let's assume we have 4 offers:   - offer with id 2 having an image of a red t-shirt and S as a value of parameter with id 21   - offer with id 3 having an image of a red t-shirt and M as a value of parameter with id 21   - offer with id 4 having an image of a blue t-shirt and S as a value of parameter with id 21   - offer with id 5 having an image of a blue t-shirt and M as a value of parameter with id 21 You can build a variant set by grouping offers using combination of available parameters - examples are available in <i>Request samples</i>. More general information about variant sets can be found [here](https://allegro.pl/pomoc/faq/wielowariantowosc-jak-polaczyc-oferty-xGgaOByGgTb#dodatkowe-informacje). Read more: <a href="../../tutorials/jak-utworzyc-oferte-wielowariantowa-oA6ZYBg5XFo#utworz-oferte-wielowariantowa" target="_blank">PL</a> / <a href="../../tutorials/how-to-create-a-multi-variant-offer-nn9DOL3nXs2#create-a-multi-variant-offer" target="_blank">EN</a>.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     * @deprecated 
     */
     toPostRequestInformation(body: VariantSet, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Use this resource to get created variant sets. The returned variant sets are ordered by name. Read more: <a href="../../tutorials/jak-utworzyc-oferte-wielowariantowa-oA6ZYBg5XFo#pobierz-liste-ofert-wielowariantowych" target="_blank">PL</a> / <a href="../../tutorials/how-to-create-a-multi-variant-offer-nn9DOL3nXs2#retrieve-a-multi-variant-offer" target="_blank">EN</a>.
 */
export interface OfferVariantsRequestBuilderGetQueryParameters {
    /**
     * Maximum number of returned variant sets.
     */
    limit?: number;
    /**
     * Index of first returned variant set.
     */
    offset?: number;
    /**
     * Filter variant sets by name or offer id.
     */
    query?: string;
}
/**
 * Uri template for the request builder.
 */
export const OfferVariantsRequestBuilderUriTemplate = "{+baseurl}/sale/offer-variants{?limit*,offset*,query*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OfferVariantsRequestBuilderNavigationMetadata: Record<Exclude<keyof OfferVariantsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    bySetId: {
        requestsMetadata: WithSetItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["setId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const OfferVariantsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: OfferVariantsRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        adapterMethodName: "send",
        responseBodyFactory:  createVariantSetsFromDiscriminatorValue,
    },
    post: {
        uriTemplate: OfferVariantsRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        adapterMethodName: "send",
        responseBodyFactory:  createVariantSetResponseFromDiscriminatorValue,
        requestBodyContentType: "application/vnd.allegro.public.v1+json",
        requestBodySerializer: serializeVariantSet,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
