/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSalesQualityHistoryResponseFromDiscriminatorValue, type SalesQualityHistoryResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /sale/quality
 */
export interface QualityRequestBuilder extends BaseRequestBuilder<QualityRequestBuilder> {
    /**
     * Use this resource to get current sales quality with at most 30 days history. Read more: <a href="../../tutorials/jak-zarzadzac-kontem-danymi-uzytkownika-ZM9YAKgPgi2#jakosc-sprzedazy" target="_blank">PL</a> / <a href="../../tutorials/account-and-user-data-management-jn9vBjqjnsw#sales-quality" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SalesQualityHistoryResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SalesQualityHistoryResponse | undefined>;
    /**
     * Use this resource to get current sales quality with at most 30 days history. Read more: <a href="../../tutorials/jak-zarzadzac-kontem-danymi-uzytkownika-ZM9YAKgPgi2#jakosc-sprzedazy" target="_blank">PL</a> / <a href="../../tutorials/account-and-user-data-management-jn9vBjqjnsw#sales-quality" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QualityRequestBuilderUriTemplate = "{+baseurl}/sale/quality";
/**
 * Metadata for all the requests in the request builder.
 */
export const QualityRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: QualityRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        adapterMethodName: "send",
        responseBodyFactory:  createSalesQualityHistoryResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
