/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAlleDiscountListCampaignsResponseFromDiscriminatorValue, createErrorsHolderFromDiscriminatorValue, type AlleDiscountListCampaignsResponse, type ErrorsHolder } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /sale/alle-discount/campaigns
 */
export interface CampaignsRequestBuilder extends BaseRequestBuilder<CampaignsRequestBuilder> {
    /**
     * List current AlleDiscount campaigns. Each campaign has its own list of goods (products) that indicate which offers can be submitted to it. Read more: <a href="../../tutorials/jak-przypisac-oferte-kampanii-GRaj0q6Gwuy#lista-dostepnych-kampanii-alleobnizka" target="_blank">PL</a> / <a href="../../tutorials/how-to-submit-offers-to-campaigns-AgGjd6EmyH4#list-of-available-allediscount-campaigns" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AlleDiscountListCampaignsResponse>}
     * @throws {ErrorsHolder} error when the service returns a 400 status code
     * @throws {ErrorsHolder} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<CampaignsRequestBuilderGetQueryParameters> | undefined) : Promise<AlleDiscountListCampaignsResponse | undefined>;
    /**
     * List current AlleDiscount campaigns. Each campaign has its own list of goods (products) that indicate which offers can be submitted to it. Read more: <a href="../../tutorials/jak-przypisac-oferte-kampanii-GRaj0q6Gwuy#lista-dostepnych-kampanii-alleobnizka" target="_blank">PL</a> / <a href="../../tutorials/how-to-submit-offers-to-campaigns-AgGjd6EmyH4#list-of-available-allediscount-campaigns" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<CampaignsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * List current AlleDiscount campaigns. Each campaign has its own list of goods (products) that indicate which offers can be submitted to it. Read more: <a href="../../tutorials/jak-przypisac-oferte-kampanii-GRaj0q6Gwuy#lista-dostepnych-kampanii-alleobnizka" target="_blank">PL</a> / <a href="../../tutorials/how-to-submit-offers-to-campaigns-AgGjd6EmyH4#list-of-available-allediscount-campaigns" target="_blank">EN</a>.
 */
export interface CampaignsRequestBuilderGetQueryParameters {
    /**
     * Id of the searched campaign. If present, returns at most one entry.
     */
    campaignId?: string;
}
/**
 * Uri template for the request builder.
 */
export const CampaignsRequestBuilderUriTemplate = "{+baseurl}/sale/alle-discount/campaigns{?campaignId*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const CampaignsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: CampaignsRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            400: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAlleDiscountListCampaignsResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
