/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAdvanceShipNoticeResponseFromDiscriminatorValue, createErrorsHolderFromDiscriminatorValue, serializeAdvanceShipNotice, serializeAdvanceShipNoticeResponse, type AdvanceShipNotice, type AdvanceShipNoticeResponse, type ErrorsHolder } from '../../../models/index.js';
// @ts-ignore
import { CancelRequestBuilderRequestsMetadata, type CancelRequestBuilder } from './cancel/index.js';
// @ts-ignore
import { LabelsRequestBuilderRequestsMetadata, type LabelsRequestBuilder } from './labels/index.js';
// @ts-ignore
import { ReceivingStateRequestBuilderRequestsMetadata, type ReceivingStateRequestBuilder } from './receivingState/index.js';
// @ts-ignore
import { SubmittedRequestBuilderRequestsMetadata, type SubmittedRequestBuilder } from './submitted/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /fulfillment/advance-ship-notices/{id}
 */
export interface AdvanceShipNoticesItemRequestBuilder extends BaseRequestBuilder<AdvanceShipNoticesItemRequestBuilder> {
    /**
     * The cancel property
     */
    get cancel(): CancelRequestBuilder;
    /**
     * The labels property
     */
    get labels(): LabelsRequestBuilder;
    /**
     * The receivingState property
     */
    get receivingState(): ReceivingStateRequestBuilder;
    /**
     * The submitted property
     */
    get submitted(): SubmittedRequestBuilder;
    /**
     * Use this resource to delete an Advance Ship Notice. Read more: <a href="../../tutorials/one-fulfillment-by-allegro-0ADwgOLqWSw#jak-usunac-awizo" target="_blank">PL</a> / <a href="../../tutorials/one-fulfillment-by-allegro-4R9dXyMPlc9#how-to-delete-advance-ship-notice" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Use this resource to get an Advance Ship Notice. Read more: <a href="../../tutorials/one-fulfillment-by-allegro-0ADwgOLqWSw#jak-przegladac-utworzone-awizo" target="_blank">PL</a> / <a href="../../tutorials/one-fulfillment-by-allegro-4R9dXyMPlc9#how-to-get-created-advance-ship-notices" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AdvanceShipNoticeResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AdvanceShipNoticeResponse | undefined>;
    /**
     * Use this resource to update an Advance Ship Notice. Any content property update will clear labels property. Use Create labels command to create new labels for provided content.If a client wants to update read-only property, an error is returned (only in cases when sent value will be different than actual on the server). Read more: <a href="../../tutorials/one-fulfillment-by-allegro-0ADwgOLqWSw#uzupelnij-dane-o-awizo" target="_blank">PL</a> / <a href="../../one-fulfillment-by-allegro-4R9dXyMPlc9#complete-the-data-of-advance-ship-notice" target="_blank">EN</a>.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AdvanceShipNoticeResponse>}
     * @throws {ErrorsHolder} error when the service returns a 422 status code
     */
     put(body: AdvanceShipNotice, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AdvanceShipNoticeResponse | undefined>;
    /**
     * Use this resource to delete an Advance Ship Notice. Read more: <a href="../../tutorials/one-fulfillment-by-allegro-0ADwgOLqWSw#jak-usunac-awizo" target="_blank">PL</a> / <a href="../../tutorials/one-fulfillment-by-allegro-4R9dXyMPlc9#how-to-delete-advance-ship-notice" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Use this resource to get an Advance Ship Notice. Read more: <a href="../../tutorials/one-fulfillment-by-allegro-0ADwgOLqWSw#jak-przegladac-utworzone-awizo" target="_blank">PL</a> / <a href="../../tutorials/one-fulfillment-by-allegro-4R9dXyMPlc9#how-to-get-created-advance-ship-notices" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Use this resource to update an Advance Ship Notice. Any content property update will clear labels property. Use Create labels command to create new labels for provided content.If a client wants to update read-only property, an error is returned (only in cases when sent value will be different than actual on the server). Read more: <a href="../../tutorials/one-fulfillment-by-allegro-0ADwgOLqWSw#uzupelnij-dane-o-awizo" target="_blank">PL</a> / <a href="../../one-fulfillment-by-allegro-4R9dXyMPlc9#complete-the-data-of-advance-ship-notice" target="_blank">EN</a>.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: AdvanceShipNotice, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AdvanceShipNoticesItemRequestBuilderUriTemplate = "{+baseurl}/fulfillment/advance-ship-notices/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AdvanceShipNoticesItemRequestBuilderNavigationMetadata: Record<Exclude<keyof AdvanceShipNoticesItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    cancel: {
        requestsMetadata: CancelRequestBuilderRequestsMetadata,
    },
    labels: {
        requestsMetadata: LabelsRequestBuilderRequestsMetadata,
    },
    receivingState: {
        requestsMetadata: ReceivingStateRequestBuilderRequestsMetadata,
    },
    submitted: {
        requestsMetadata: SubmittedRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const AdvanceShipNoticesItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: AdvanceShipNoticesItemRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: AdvanceShipNoticesItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        adapterMethodName: "send",
        responseBodyFactory:  createAdvanceShipNoticeResponseFromDiscriminatorValue,
    },
    put: {
        uriTemplate: AdvanceShipNoticesItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            422: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAdvanceShipNoticeResponseFromDiscriminatorValue,
        requestBodyContentType: "application/vnd.allegro.public.v1+json",
        requestBodySerializer: serializeAdvanceShipNotice,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
