/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBadRequestResponseFromDiscriminatorValue, createErrorApiResponseFromDiscriminatorValue, createOrderDetailsResponseFromDiscriminatorValue, type BadRequestResponse, type ErrorApiResponse, type OrderDetailsResponse } from '../../../../models/index.js';
// @ts-ignore
import { CancelRequestBuilderRequestsMetadata, type CancelRequestBuilder } from './cancel/index.js';
// @ts-ignore
import { DocumentsRequestBuilderRequestsMetadata, type DocumentsRequestBuilder } from './documents/index.js';
// @ts-ignore
import { type WithTypeItemRequestBuilder, WithTypeItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { PaymentRequestBuilderRequestsMetadata, type PaymentRequestBuilder } from './payment/index.js';
// @ts-ignore
import { PaymentStatusRequestBuilderRequestsMetadata, type PaymentStatusRequestBuilder } from './paymentStatus/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/user/orders/{id}
 */
export interface OrdersItemRequestBuilder extends BaseRequestBuilder<OrdersItemRequestBuilder> {
    /**
     * The cancel property
     */
    get cancel(): CancelRequestBuilder;
    /**
     * The documents property
     */
    get documents(): DocumentsRequestBuilder;
    /**
     * The payment property
     */
    get payment(): PaymentRequestBuilder;
    /**
     * The paymentStatus property
     */
    get paymentStatus(): PaymentStatusRequestBuilder;
    /**
     * Gets an item from the ApiSdk.v1.user.orders.item.item collection
     * @param type Rodzaj dokumentu do pobrania.
     * @returns {WithTypeItemRequestBuilder}
     */
     byType(type: string) : WithTypeItemRequestBuilder;
    /**
     * Metoda służy do pobierania szczegółów wybranego zamówienia.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<OrderDetailsResponse>}
     * @throws {BadRequestResponse} error when the service returns a 400 status code
     * @throws {ErrorApiResponse} error when the service returns a 403 status code
     * @throws {ErrorApiResponse} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<OrderDetailsResponse | undefined>;
    /**
     * Metoda służy do pobierania szczegółów wybranego zamówienia.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const OrdersItemRequestBuilderUriTemplate = "{+baseurl}/v1/user/orders/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OrdersItemRequestBuilderNavigationMetadata: Record<Exclude<keyof OrdersItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byType: {
        requestsMetadata: WithTypeItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["type"],
    },
    cancel: {
        requestsMetadata: CancelRequestBuilderRequestsMetadata,
    },
    documents: {
        requestsMetadata: DocumentsRequestBuilderRequestsMetadata,
    },
    payment: {
        requestsMetadata: PaymentRequestBuilderRequestsMetadata,
    },
    paymentStatus: {
        requestsMetadata: PaymentStatusRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const OrdersItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: OrdersItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBadRequestResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createOrderDetailsResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
