/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAuthErrorFromDiscriminatorValue, createError400FromDiscriminatorValue, createError403FromDiscriminatorValue, createShipmentCancelCommandDtoFromDiscriminatorValue, serializeError400, serializeError403, serializeShipmentCancelCommandDto, type AuthError, type Error400, type Error403, type ShipmentCancelCommandDto } from '../../../models/index.js';
// @ts-ignore
import { type WithCommandItemRequestBuilder, WithCommandItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /shipment-management/shipments/cancel-commands
 */
export interface CancelCommandsRequestBuilder extends BaseRequestBuilder<CancelCommandsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.shipmentManagement.shipments.cancelCommands.item collection
     * @param commandId Command UUID.
     * @returns {WithCommandItemRequestBuilder}
     */
     byCommandId(commandId: string) : WithCommandItemRequestBuilder;
    /**
     * Use this resource to cancel parcel. Read more: <a href="../../tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-anulowac-paczke" target="_blank">PL</a> / <a href="../../tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV#how-to-cancel-a-shipment" target="_blank">EN</a>.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ShipmentCancelCommandDto>}
     * @throws {ShipmentCancelCommandDto400Error} error when the service returns a 400 status code
     * @throws {AuthError} error when the service returns a 401 status code
     * @throws {ShipmentCancelCommandDto403Error} error when the service returns a 403 status code
     */
     post(body: ShipmentCancelCommandDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ShipmentCancelCommandDto | undefined>;
    /**
     * Use this resource to cancel parcel. Read more: <a href="../../tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-anulowac-paczke" target="_blank">PL</a> / <a href="../../tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV#how-to-cancel-a-shipment" target="_blank">EN</a>.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ShipmentCancelCommandDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ShipmentCancelCommandDto400Error}
 */
// @ts-ignore
export function createShipmentCancelCommandDto400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoShipmentCancelCommandDto400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ShipmentCancelCommandDto403Error}
 */
// @ts-ignore
export function createShipmentCancelCommandDto403ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoShipmentCancelCommandDto403Error;
}
/**
 * The deserialization information for the current model
 * @param ShipmentCancelCommandDto400Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoShipmentCancelCommandDto400Error(shipmentCancelCommandDto400Error: Partial<ShipmentCancelCommandDto400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "errors": n => { shipmentCancelCommandDto400Error.errors = n.getCollectionOfObjectValues<Error400>(createError400FromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param ShipmentCancelCommandDto403Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoShipmentCancelCommandDto403Error(shipmentCancelCommandDto403Error: Partial<ShipmentCancelCommandDto403Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "errors": n => { shipmentCancelCommandDto403Error.errors = n.getCollectionOfObjectValues<Error403>(createError403FromDiscriminatorValue); },
    }
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ShipmentCancelCommandDto400Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeShipmentCancelCommandDto400Error(writer: SerializationWriter, shipmentCancelCommandDto400Error: Partial<ShipmentCancelCommandDto400Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!shipmentCancelCommandDto400Error || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<Error400>("errors", shipmentCancelCommandDto400Error.errors, serializeError400);
    writer.writeAdditionalData(shipmentCancelCommandDto400Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ShipmentCancelCommandDto403Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeShipmentCancelCommandDto403Error(writer: SerializationWriter, shipmentCancelCommandDto403Error: Partial<ShipmentCancelCommandDto403Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!shipmentCancelCommandDto403Error || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<Error403>("errors", shipmentCancelCommandDto403Error.errors, serializeError403);
    writer.writeAdditionalData(shipmentCancelCommandDto403Error.additionalData);
}
export interface ShipmentCancelCommandDto400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Array of errors.
     */
    errors?: Error400[] | null;
}
export interface ShipmentCancelCommandDto403Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Array of errors.
     */
    errors?: Error403[] | null;
}
/**
 * Uri template for the request builder.
 */
export const CancelCommandsRequestBuilderUriTemplate = "{+baseurl}/shipment-management/shipments/cancel-commands";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CancelCommandsRequestBuilderNavigationMetadata: Record<Exclude<keyof CancelCommandsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byCommandId: {
        requestsMetadata: WithCommandItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["commandId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const CancelCommandsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: CancelCommandsRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            400: createShipmentCancelCommandDto400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAuthErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createShipmentCancelCommandDto403ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createShipmentCancelCommandDtoFromDiscriminatorValue,
        requestBodyContentType: "application/vnd.allegro.public.v1+json",
        requestBodySerializer: serializeShipmentCancelCommandDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
