/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAuthErrorFromDiscriminatorValue, createErrorsHolderFromDiscriminatorValue, createSubsidyManageOffersCommandResultFromDiscriminatorValue, serializeSubsidyExcludeOffersCommand, serializeSubsidyManageOffersCommandResult, type AuthError, type ErrorsHolder, type SubsidyExcludeOffersCommand, type SubsidyManageOffersCommandResult } from '../../../../models/index.js';
// @ts-ignore
import { type WithCommandItemRequestBuilder, WithCommandItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /sale/allegro-prices/offers/exclusion-commands
 */
export interface ExclusionCommandsRequestBuilder extends BaseRequestBuilder<ExclusionCommandsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.sale.allegroPrices.offers.exclusionCommands.item collection
     * @param commandId The unique identifier of the command.
     * @returns {WithCommandItemRequestBuilder}
     */
     byCommandId(commandId: Guid) : WithCommandItemRequestBuilder;
    /**
     * Use this resource to submit a command to exclude offers from the Allegro Prices program. Returns a command ID that can be used to track the processing status.
     * @param body Command to exclude offers from the Allegro Prices program
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SubsidyManageOffersCommandResult>}
     * @throws {ErrorsHolder} error when the service returns a 400 status code
     * @throws {AuthError} error when the service returns a 401 status code
     * @throws {ErrorsHolder} error when the service returns a 409 status code
     * @throws {ErrorsHolder} error when the service returns a 422 status code
     */
     post(body: SubsidyExcludeOffersCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SubsidyManageOffersCommandResult | undefined>;
    /**
     * Use this resource to submit a command to exclude offers from the Allegro Prices program. Returns a command ID that can be used to track the processing status.
     * @param body Command to exclude offers from the Allegro Prices program
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SubsidyExcludeOffersCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ExclusionCommandsRequestBuilderUriTemplate = "{+baseurl}/sale/allegro-prices/offers/exclusion-commands";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ExclusionCommandsRequestBuilderNavigationMetadata: Record<Exclude<keyof ExclusionCommandsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byCommandId: {
        requestsMetadata: WithCommandItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["commandId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ExclusionCommandsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ExclusionCommandsRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            400: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAuthErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSubsidyManageOffersCommandResultFromDiscriminatorValue,
        requestBodyContentType: "application/vnd.allegro.public.v1+json",
        requestBodySerializer: serializeSubsidyExcludeOffersCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
