/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProductFromDiscriminatorValue, createUnauthorizedErrorResponseFromDiscriminatorValue, createValidationErrorResponseFromDiscriminatorValue, serializeProduct, type Product, type UnauthorizedErrorResponse, type ValidationErrorResponse } from '../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProductsPostRequestBody}
 */
// @ts-ignore
export function createProductsPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProductsPostRequestBody;
}
/**
 * The deserialization information for the current model
 * @param ProductsPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProductsPostRequestBody(productsPostRequestBody: Partial<ProductsPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "product": n => { productsPostRequestBody.product = n.getObjectValue<Product>(createProductFromDiscriminatorValue); },
    }
}
/**
 * Builds and executes requests for operations under /products.json
 */
export interface ProductsJsonRequestBuilder extends BaseRequestBuilder<ProductsJsonRequestBuilder> {
    /**
     * List products
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Product[]>}
     */
     get(requestConfiguration?: RequestConfiguration<ProductsJsonRequestBuilderGetQueryParameters> | undefined) : Promise<Product[] | undefined>;
    /**
     * Create product
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Product>}
     * @throws {UnauthorizedErrorResponse} error when the service returns a 401 status code
     * @throws {ValidationErrorResponse} error when the service returns a 422 status code
     */
     post(body: ProductsPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Product | undefined>;
    /**
     * List products
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<ProductsJsonRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Create product
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ProductsPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * List products
 */
export interface ProductsJsonRequestBuilderGetQueryParameters {
    /**
     * Filter products by category ID
     */
    categoryId?: number;
    /**
     * Page number for pagination
     */
    page?: number;
    /**
     * Search term to filter results by name, code, or other fields
     */
    query?: string;
    /**
     * Warehouse filter
     */
    warehouseId?: number;
}
export interface ProductsPostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The product property
     */
    product?: Product | null;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProductsPostRequestBody The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProductsPostRequestBody(writer: SerializationWriter, productsPostRequestBody: Partial<ProductsPostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!productsPostRequestBody || isSerializingDerivedType) { return; }
    writer.writeObjectValue<Product>("product", productsPostRequestBody.product, serializeProduct);
    writer.writeAdditionalData(productsPostRequestBody.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const ProductsJsonRequestBuilderUriTemplate = "{+baseurl}/products.json{?category_id*,page*,query*,warehouse_id*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const ProductsJsonRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "categoryId": "category_id",
    "warehouseId": "warehouse_id",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ProductsJsonRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ProductsJsonRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createProductFromDiscriminatorValue,
        queryParametersMapper: ProductsJsonRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: ProductsJsonRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createUnauthorizedErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createValidationErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createProductFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeProductsPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
