/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAuthErrorFromDiscriminatorValue, createErrorEscapedFromDiscriminatorValue, createErrorsHolderFromDiscriminatorValue, createSaleProductOfferResponseV1FromDiscriminatorValue, serializeErrorEscaped, serializeSaleProductOfferRequestV1, serializeSaleProductOfferResponseV1, type AuthError, type ErrorEscaped, type ErrorsHolder, type SaleProductOfferRequestV1, type SaleProductOfferResponseV1 } from '../../models/index.js';
// @ts-ignore
import { type WithOfferItemRequestBuilder, WithOfferItemRequestBuilderNavigationMetadata, WithOfferItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SaleProductOfferResponseV1422Error}
 */
// @ts-ignore
export function createSaleProductOfferResponseV1422ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSaleProductOfferResponseV1422Error;
}
/**
 * The deserialization information for the current model
 * @param SaleProductOfferResponseV1422Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSaleProductOfferResponseV1422Error(saleProductOfferResponseV1422Error: Partial<SaleProductOfferResponseV1422Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "errors": n => { saleProductOfferResponseV1422Error.errors = n.getCollectionOfObjectValues<ErrorEscaped>(createErrorEscapedFromDiscriminatorValue); },
    }
}
/**
 * Builds and executes requests for operations under /sale/product-offers
 */
export interface ProductOffersRequestBuilder extends BaseRequestBuilder<ProductOffersRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.sale.productOffers.item collection
     * @param offerId The offer identifier.
     * @returns {WithOfferItemRequestBuilder}
     */
     byOfferId(offerId: string) : WithOfferItemRequestBuilder;
    /**
     * Use this resource to create offer based on product. Read more: <a href="../../tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-produktem-za-pomoca-zasobu-sale-product-offers" target="_blank">PL</a> / <a href="../../tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-list-an-offer-with-a-product-via-sale-product-offers-resource" target="_blank">EN</a>. Note that requests may be limited.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SaleProductOfferResponseV1>}
     * @throws {ErrorsHolder} error when the service returns a 400 status code
     * @throws {AuthError} error when the service returns a 401 status code
     * @throws {ErrorsHolder} error when the service returns a 403 status code
     * @throws {SaleProductOfferResponseV1422Error} error when the service returns a 422 status code
     */
     post(body: SaleProductOfferRequestV1, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SaleProductOfferResponseV1 | undefined>;
    /**
     * Use this resource to create offer based on product. Read more: <a href="../../tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-produktem-za-pomoca-zasobu-sale-product-offers" target="_blank">PL</a> / <a href="../../tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-list-an-offer-with-a-product-via-sale-product-offers-resource" target="_blank">EN</a>. Note that requests may be limited.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SaleProductOfferRequestV1, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface SaleProductOfferResponseV1422Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The errors property
     */
    errors?: ErrorEscaped[] | null;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SaleProductOfferResponseV1422Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSaleProductOfferResponseV1422Error(writer: SerializationWriter, saleProductOfferResponseV1422Error: Partial<SaleProductOfferResponseV1422Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!saleProductOfferResponseV1422Error || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<ErrorEscaped>("errors", saleProductOfferResponseV1422Error.errors, serializeErrorEscaped);
    writer.writeAdditionalData(saleProductOfferResponseV1422Error.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const ProductOffersRequestBuilderUriTemplate = "{+baseurl}/sale/product-offers";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ProductOffersRequestBuilderNavigationMetadata: Record<Exclude<keyof ProductOffersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byOfferId: {
        requestsMetadata: WithOfferItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithOfferItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["offerId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ProductOffersRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ProductOffersRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            400: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAuthErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createSaleProductOfferResponseV1422ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSaleProductOfferResponseV1FromDiscriminatorValue,
        requestBodyContentType: "application/vnd.allegro.public.v1+json",
        requestBodySerializer: serializeSaleProductOfferRequestV1,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
