/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Recurrings}
 */
// @ts-ignore
export function createRecurringsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRecurrings;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RecurringsPostRequestBody_recurring}
 */
// @ts-ignore
export function createRecurringsPostRequestBody_recurringFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRecurringsPostRequestBody_recurring;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RecurringsPostRequestBody}
 */
// @ts-ignore
export function createRecurringsPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRecurringsPostRequestBody;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RecurringsPostResponse}
 */
// @ts-ignore
export function createRecurringsPostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRecurringsPostResponse;
}
/**
 * The deserialization information for the current model
 * @param Recurrings The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRecurrings(recurrings: Partial<Recurrings> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param RecurringsPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRecurringsPostRequestBody(recurringsPostRequestBody: Partial<RecurringsPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "recurring": n => { recurringsPostRequestBody.recurring = n.getObjectValue<RecurringsPostRequestBody_recurring>(createRecurringsPostRequestBody_recurringFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param RecurringsPostRequestBody_recurring The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRecurringsPostRequestBody_recurring(recurringsPostRequestBody_recurring: Partial<RecurringsPostRequestBody_recurring> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param RecurringsPostResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRecurringsPostResponse(recurringsPostResponse: Partial<RecurringsPostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
export interface Recurrings extends AdditionalDataHolder, Parsable {
}
/**
 * Builds and executes requests for operations under /recurrings.json
 */
export interface RecurringsJsonRequestBuilder extends BaseRequestBuilder<RecurringsJsonRequestBuilder> {
    /**
     * List recurring invoice definitions
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Recurrings[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Recurrings[] | undefined>;
    /**
     * Create recurring invoice definition
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RecurringsPostResponse>}
     */
     post(body: RecurringsPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RecurringsPostResponse | undefined>;
    /**
     * List recurring invoice definitions
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Create recurring invoice definition
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RecurringsPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface RecurringsPostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The recurring property
     */
    recurring?: RecurringsPostRequestBody_recurring | null;
}
export interface RecurringsPostRequestBody_recurring extends AdditionalDataHolder, Parsable {
}
export interface RecurringsPostResponse extends AdditionalDataHolder, Parsable {
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Recurrings The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRecurrings(writer: SerializationWriter, recurrings: Partial<Recurrings> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!recurrings || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(recurrings.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RecurringsPostRequestBody The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRecurringsPostRequestBody(writer: SerializationWriter, recurringsPostRequestBody: Partial<RecurringsPostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!recurringsPostRequestBody || isSerializingDerivedType) { return; }
    writer.writeObjectValue<RecurringsPostRequestBody_recurring>("recurring", recurringsPostRequestBody.recurring, serializeRecurringsPostRequestBody_recurring);
    writer.writeAdditionalData(recurringsPostRequestBody.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RecurringsPostRequestBody_recurring The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRecurringsPostRequestBody_recurring(writer: SerializationWriter, recurringsPostRequestBody_recurring: Partial<RecurringsPostRequestBody_recurring> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!recurringsPostRequestBody_recurring || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(recurringsPostRequestBody_recurring.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RecurringsPostResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRecurringsPostResponse(writer: SerializationWriter, recurringsPostResponse: Partial<RecurringsPostResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!recurringsPostResponse || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(recurringsPostResponse.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const RecurringsJsonRequestBuilderUriTemplate = "{+baseurl}/recurrings.json";
/**
 * Metadata for all the requests in the request builder.
 */
export const RecurringsJsonRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: RecurringsJsonRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createRecurringsFromDiscriminatorValue,
    },
    post: {
        uriTemplate: RecurringsJsonRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createRecurringsPostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRecurringsPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
