/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createReturnPolicyResponseV1FromDiscriminatorValue, createReturnPolicyResponseV2FromDiscriminatorValue, serializeReturnPolicyRequestV1, serializeReturnPolicyResponseV1, type ReturnPolicyRequestV1, type ReturnPolicyResponseV1, type ReturnPolicyResponseV2 } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /after-sales-service-conditions/return-policies/{returnPolicyId}
 */
export interface WithReturnPolicyItemRequestBuilder extends BaseRequestBuilder<WithReturnPolicyItemRequestBuilder> {
    /**
     * Use this resource to delete a return policy definition.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ReturnPolicyResponseV2>}
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ReturnPolicyResponseV2 | undefined>;
    /**
     * Use this resource to get a return policy details. Read more: <a href="../../tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-pobrac-warunki-zwrotow-przypisane-do-konta" target="_blank">PL</a> / <a href="../../tutorials/how-to-process-list-of-offers-m09BKA5v8H3#how-to-retrieve-return-policies-assigned-to-the-account" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ReturnPolicyResponseV1>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ReturnPolicyResponseV1 | undefined>;
    /**
     * Use this resource to modify the return policy details. Read more: <a href="../../tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-edytowac-informacje-o-warunkach-zwrotu" target="_blank">PL</a> / <a href="../../tutorials/how-to-process-list-of-offers-m09BKA5v8H3#how-to-update-return-policy-information" target="_blank">EN</a>.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ReturnPolicyResponseV1>}
     */
     put(body: ReturnPolicyRequestV1, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ReturnPolicyResponseV1 | undefined>;
    /**
     * Use this resource to delete a return policy definition.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Use this resource to get a return policy details. Read more: <a href="../../tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-pobrac-warunki-zwrotow-przypisane-do-konta" target="_blank">PL</a> / <a href="../../tutorials/how-to-process-list-of-offers-m09BKA5v8H3#how-to-retrieve-return-policies-assigned-to-the-account" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Use this resource to modify the return policy details. Read more: <a href="../../tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-edytowac-informacje-o-warunkach-zwrotu" target="_blank">PL</a> / <a href="../../tutorials/how-to-process-list-of-offers-m09BKA5v8H3#how-to-update-return-policy-information" target="_blank">EN</a>.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: ReturnPolicyRequestV1, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithReturnPolicyItemRequestBuilderUriTemplate = "{+baseurl}/after-sales-service-conditions/return-policies/{returnPolicyId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithReturnPolicyItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithReturnPolicyItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v2+json",
        adapterMethodName: "send",
        responseBodyFactory:  createReturnPolicyResponseV2FromDiscriminatorValue,
    },
    get: {
        uriTemplate: WithReturnPolicyItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        adapterMethodName: "send",
        responseBodyFactory:  createReturnPolicyResponseV1FromDiscriminatorValue,
    },
    put: {
        uriTemplate: WithReturnPolicyItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        adapterMethodName: "send",
        responseBodyFactory:  createReturnPolicyResponseV1FromDiscriminatorValue,
        requestBodyContentType: "application/vnd.allegro.public.v1+json",
        requestBodySerializer: serializeReturnPolicyRequestV1,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
