/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAuthErrorFromDiscriminatorValue, createErrorsHolderFromDiscriminatorValue, createResponsiblePersonResponseFromDiscriminatorValue, serializeCreateResponsiblePersonRequest, serializeResponsiblePersonResponse, type AuthError, type CreateResponsiblePersonRequest, type ErrorsHolder, type ResponsiblePersonResponse } from '../../models/index.js';
// @ts-ignore
import { ResponsiblePersonsItemRequestBuilderRequestsMetadata, type ResponsiblePersonsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ResponsiblePersonsGetResponse}
 */
// @ts-ignore
export function createResponsiblePersonsGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoResponsiblePersonsGetResponse;
}
/**
 * The deserialization information for the current model
 * @param ResponsiblePersonsGetResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoResponsiblePersonsGetResponse(responsiblePersonsGetResponse: Partial<ResponsiblePersonsGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "count": n => { responsiblePersonsGetResponse.count = n.getNumberValue(); },
        "responsiblePersons": n => { responsiblePersonsGetResponse.responsiblePersons = n.getCollectionOfObjectValues<ResponsiblePersonResponse>(createResponsiblePersonResponseFromDiscriminatorValue); },
        "totalCount": n => { responsiblePersonsGetResponse.totalCount = n.getNumberValue(); },
    }
}
export interface ResponsiblePersonsGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Number of responsible persons data returned in search result for the given parameters.
     */
    count?: number | null;
    /**
     * The responsiblePersons property
     */
    responsiblePersons?: ResponsiblePersonResponse[] | null;
    /**
     * Total number of available responsible persons data.
     */
    totalCount?: number | null;
}
/**
 * Builds and executes requests for operations under /sale/responsible-persons
 */
export interface ResponsiblePersonsRequestBuilder extends BaseRequestBuilder<ResponsiblePersonsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.sale.responsiblePersons.item collection
     * @param id Responsible person ID.
     * @returns {ResponsiblePersonsItemRequestBuilder}
     */
     byId(id: Guid) : ResponsiblePersonsItemRequestBuilder;
    /**
     * Use this resource to get a list of responsible persons for the compliance of the product with EU regulations. Read more: <a href="../../tutorials/jak-zarzadzac-kontem-danymi-uzytkownika-ZM9YAKgPgi2#osoba-odpowiedzialna-za-zgodnosc-produktu-z-przepisami-unijnymi" target="_blank">PL</a> / <a href="../../tutorials/account-and-user-data-management-jn9vBjqjnsw#responsible-persons-for-the-compliance-of-the-product-with-eu-regulations" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ResponsiblePersonsGetResponse>}
     * @throws {ErrorsHolder} error when the service returns a 400 status code
     * @throws {AuthError} error when the service returns a 401 status code
     * @throws {ErrorsHolder} error when the service returns a 403 status code
     * @throws {ErrorsHolder} error when the service returns a 422 status code
     */
     get(requestConfiguration?: RequestConfiguration<ResponsiblePersonsRequestBuilderGetQueryParameters> | undefined) : Promise<ResponsiblePersonsGetResponse | undefined>;
    /**
     * Use this resource to create a new responsible person for the compliance of the product with EU regulations. Read more: <a href="../../tutorials/jak-zarzadzac-kontem-danymi-uzytkownika-ZM9YAKgPgi2#osoba-odpowiedzialna-za-zgodnosc-produktu-z-przepisami-unijnymi" target="_blank">PL</a> / <a href="../../tutorials/account-and-user-data-management-jn9vBjqjnsw#responsible-persons-for-the-compliance-of-the-product-with-eu-regulations" target="_blank">EN</a>.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ResponsiblePersonResponse>}
     * @throws {ErrorsHolder} error when the service returns a 400 status code
     * @throws {AuthError} error when the service returns a 401 status code
     * @throws {ErrorsHolder} error when the service returns a 403 status code
     * @throws {ErrorsHolder} error when the service returns a 422 status code
     */
     post(body: CreateResponsiblePersonRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ResponsiblePersonResponse | undefined>;
    /**
     * Use this resource to get a list of responsible persons for the compliance of the product with EU regulations. Read more: <a href="../../tutorials/jak-zarzadzac-kontem-danymi-uzytkownika-ZM9YAKgPgi2#osoba-odpowiedzialna-za-zgodnosc-produktu-z-przepisami-unijnymi" target="_blank">PL</a> / <a href="../../tutorials/account-and-user-data-management-jn9vBjqjnsw#responsible-persons-for-the-compliance-of-the-product-with-eu-regulations" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<ResponsiblePersonsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Use this resource to create a new responsible person for the compliance of the product with EU regulations. Read more: <a href="../../tutorials/jak-zarzadzac-kontem-danymi-uzytkownika-ZM9YAKgPgi2#osoba-odpowiedzialna-za-zgodnosc-produktu-z-przepisami-unijnymi" target="_blank">PL</a> / <a href="../../tutorials/account-and-user-data-management-jn9vBjqjnsw#responsible-persons-for-the-compliance-of-the-product-with-eu-regulations" target="_blank">EN</a>.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateResponsiblePersonRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Use this resource to get a list of responsible persons for the compliance of the product with EU regulations. Read more: <a href="../../tutorials/jak-zarzadzac-kontem-danymi-uzytkownika-ZM9YAKgPgi2#osoba-odpowiedzialna-za-zgodnosc-produktu-z-przepisami-unijnymi" target="_blank">PL</a> / <a href="../../tutorials/account-and-user-data-management-jn9vBjqjnsw#responsible-persons-for-the-compliance-of-the-product-with-eu-regulations" target="_blank">EN</a>.
 */
export interface ResponsiblePersonsRequestBuilderGetQueryParameters {
    /**
     * Number of returned responsible persons data.
     */
    limit?: number;
    /**
     * Index of first returned responsible persons data from all search results.
     */
    offset?: number;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ResponsiblePersonsGetResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeResponsiblePersonsGetResponse(writer: SerializationWriter, responsiblePersonsGetResponse: Partial<ResponsiblePersonsGetResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!responsiblePersonsGetResponse || isSerializingDerivedType) { return; }
    writer.writeNumberValue("count", responsiblePersonsGetResponse.count);
    writer.writeCollectionOfObjectValues<ResponsiblePersonResponse>("responsiblePersons", responsiblePersonsGetResponse.responsiblePersons, serializeResponsiblePersonResponse);
    writer.writeNumberValue("totalCount", responsiblePersonsGetResponse.totalCount);
    writer.writeAdditionalData(responsiblePersonsGetResponse.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const ResponsiblePersonsRequestBuilderUriTemplate = "{+baseurl}/sale/responsible-persons{?limit*,offset*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ResponsiblePersonsRequestBuilderNavigationMetadata: Record<Exclude<keyof ResponsiblePersonsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: ResponsiblePersonsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ResponsiblePersonsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ResponsiblePersonsRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            400: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAuthErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createResponsiblePersonsGetResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: ResponsiblePersonsRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            400: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAuthErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createResponsiblePersonResponseFromDiscriminatorValue,
        requestBodyContentType: "application/vnd.allegro.public.v1+json",
        requestBodySerializer: serializeCreateResponsiblePersonRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
