/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CampaignsRequestBuilderNavigationMetadata, type CampaignsRequestBuilder } from './campaigns/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /sale/badges/offers/{offerId}
 */
export interface WithOfferItemRequestBuilder extends BaseRequestBuilder<WithOfferItemRequestBuilder> {
    /**
     * The campaigns property
     */
    get campaigns(): CampaignsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithOfferItemRequestBuilderUriTemplate = "{+baseurl}/sale/badges/offers/{offerId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithOfferItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithOfferItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    campaigns: {
        navigationMetadata: CampaignsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
