/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAvailableProductsListFromDiscriminatorValue, createErrorsHolderFromDiscriminatorValue, type AvailableProductsList, type ErrorsHolder } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /fulfillment/available-products
 */
export interface AvailableProductsRequestBuilder extends BaseRequestBuilder<AvailableProductsRequestBuilder> {
    /**
     * Use this resource to get a list of products that can be added to Advance Ship Notice. The list contains products for which the seller has created offers and is ordered by product's name. Read more: <a href="../../tutorials/one-fulfillment-by-allegro-0ADwgOLqWSw#sprawdz-dostepne-produkty-do-awizacji" target="_blank">PL</a> / <a href="../../tutorials/one-fulfillment-by-allegro-4R9dXyMPlc9#check-available-products-for-asn" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AvailableProductsList>}
     * @throws {ErrorsHolder} error when the service returns a 422 status code
     */
     get(requestConfiguration?: RequestConfiguration<AvailableProductsRequestBuilderGetQueryParameters> | undefined) : Promise<AvailableProductsList | undefined>;
    /**
     * Use this resource to get a list of products that can be added to Advance Ship Notice. The list contains products for which the seller has created offers and is ordered by product's name. Read more: <a href="../../tutorials/one-fulfillment-by-allegro-0ADwgOLqWSw#sprawdz-dostepne-produkty-do-awizacji" target="_blank">PL</a> / <a href="../../tutorials/one-fulfillment-by-allegro-4R9dXyMPlc9#check-available-products-for-asn" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<AvailableProductsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Use this resource to get a list of products that can be added to Advance Ship Notice. The list contains products for which the seller has created offers and is ordered by product's name. Read more: <a href="../../tutorials/one-fulfillment-by-allegro-0ADwgOLqWSw#sprawdz-dostepne-produkty-do-awizacji" target="_blank">PL</a> / <a href="../../tutorials/one-fulfillment-by-allegro-4R9dXyMPlc9#check-available-products-for-asn" target="_blank">EN</a>.
 */
export interface AvailableProductsRequestBuilderGetQueryParameters {
    /**
     * Maximum number of elements in response.
     */
    limit?: number;
    /**
     * The offset of elements in the response.
     */
    offset?: number;
}
/**
 * Uri template for the request builder.
 */
export const AvailableProductsRequestBuilderUriTemplate = "{+baseurl}/fulfillment/available-products{?limit*,offset*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const AvailableProductsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AvailableProductsRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            422: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAvailableProductsListFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
