/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBadRequestResponseFromDiscriminatorValue, createCheckDataResponseFromDiscriminatorValue, createErrorApiResponseFromDiscriminatorValue, serializeCheckDataResponse, serializeOrderBody, type BadRequestResponse, type CheckDataResponse, type ErrorApiResponse, type OrderBody } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/order/check-data
 */
export interface CheckDataRequestBuilder extends BaseRequestBuilder<CheckDataRequestBuilder> {
    /**
     * Metoda służy do sprawdzenia poprawności wprowadzonych danych zamówienia, w celu zwrócenia wyceny przesyłki wraz cenami usług dodatkowych.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CheckDataResponse>}
     * @throws {BadRequestResponse} error when the service returns a 400 status code
     * @throws {ErrorApiResponse} error when the service returns a 403 status code
     * @throws {ErrorApiResponse} error when the service returns a 422 status code
     */
     post(body: OrderBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CheckDataResponse | undefined>;
    /**
     * Metoda służy do sprawdzenia poprawności wprowadzonych danych zamówienia, w celu zwrócenia wyceny przesyłki wraz cenami usług dodatkowych.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: OrderBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CheckDataRequestBuilderUriTemplate = "{+baseurl}/v1/order/check-data";
/**
 * Metadata for all the requests in the request builder.
 */
export const CheckDataRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: CheckDataRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBadRequestResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCheckDataResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeOrderBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
