/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAuthErrorFromDiscriminatorValue, createErrorsHolderFromDiscriminatorValue, createResponsibleProducerResponseFromDiscriminatorValue, serializeCreateResponsibleProducerRequest, serializeResponsibleProducerResponse, type AuthError, type CreateResponsibleProducerRequest, type ErrorsHolder, type ResponsibleProducerResponse } from '../../models/index.js';
// @ts-ignore
import { ResponsibleProducersItemRequestBuilderRequestsMetadata, type ResponsibleProducersItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ResponsibleProducersGetResponse}
 */
// @ts-ignore
export function createResponsibleProducersGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoResponsibleProducersGetResponse;
}
/**
 * The deserialization information for the current model
 * @param ResponsibleProducersGetResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoResponsibleProducersGetResponse(responsibleProducersGetResponse: Partial<ResponsibleProducersGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "count": n => { responsibleProducersGetResponse.count = n.getNumberValue(); },
        "responsibleProducers": n => { responsibleProducersGetResponse.responsibleProducers = n.getCollectionOfObjectValues<ResponsibleProducerResponse>(createResponsibleProducerResponseFromDiscriminatorValue); },
        "totalCount": n => { responsibleProducersGetResponse.totalCount = n.getNumberValue(); },
    }
}
export interface ResponsibleProducersGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Number of responsible producers data returned in search result for the given parameters.
     */
    count?: number | null;
    /**
     * The responsibleProducers property
     */
    responsibleProducers?: ResponsibleProducerResponse[] | null;
    /**
     * Total number of available responsible producers data.
     */
    totalCount?: number | null;
}
/**
 * Builds and executes requests for operations under /sale/responsible-producers
 */
export interface ResponsibleProducersRequestBuilder extends BaseRequestBuilder<ResponsibleProducersRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.sale.responsibleProducers.item collection
     * @param id Responsible producer ID.
     * @returns {ResponsibleProducersItemRequestBuilder}
     */
     byId(id: Guid) : ResponsibleProducersItemRequestBuilder;
    /**
     * Use this resource to get a list of responsible producers for the compliance of the product with EU regulations. Read more: <a href="../../tutorials/jak-zarzadzac-kontem-danymi-uzytkownika-ZM9YAKgPgi2#dane-teleadresowe-producenta" target="_blank">PL</a> / <a href="../../tutorials/account-and-user-data-management-jn9vBjqjnsw#responsible-producers-contact-information" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ResponsibleProducersGetResponse>}
     * @throws {ErrorsHolder} error when the service returns a 400 status code
     * @throws {AuthError} error when the service returns a 401 status code
     * @throws {ErrorsHolder} error when the service returns a 403 status code
     * @throws {ErrorsHolder} error when the service returns a 422 status code
     */
     get(requestConfiguration?: RequestConfiguration<ResponsibleProducersRequestBuilderGetQueryParameters> | undefined) : Promise<ResponsibleProducersGetResponse | undefined>;
    /**
     * Use this resource to create a new responsible producer for the compliance of the product with EU regulations. Read more: <a href="../../tutorials/jak-zarzadzac-kontem-danymi-uzytkownika-ZM9YAKgPgi2#dane-teleadresowe-producenta" target="_blank">PL</a> / <a href="../../tutorials/account-and-user-data-management-jn9vBjqjnsw#responsible-producers-contact-information" target="_blank">EN</a>.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ResponsibleProducerResponse>}
     * @throws {ErrorsHolder} error when the service returns a 400 status code
     * @throws {AuthError} error when the service returns a 401 status code
     * @throws {ErrorsHolder} error when the service returns a 403 status code
     * @throws {ErrorsHolder} error when the service returns a 422 status code
     */
     post(body: CreateResponsibleProducerRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ResponsibleProducerResponse | undefined>;
    /**
     * Use this resource to get a list of responsible producers for the compliance of the product with EU regulations. Read more: <a href="../../tutorials/jak-zarzadzac-kontem-danymi-uzytkownika-ZM9YAKgPgi2#dane-teleadresowe-producenta" target="_blank">PL</a> / <a href="../../tutorials/account-and-user-data-management-jn9vBjqjnsw#responsible-producers-contact-information" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<ResponsibleProducersRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Use this resource to create a new responsible producer for the compliance of the product with EU regulations. Read more: <a href="../../tutorials/jak-zarzadzac-kontem-danymi-uzytkownika-ZM9YAKgPgi2#dane-teleadresowe-producenta" target="_blank">PL</a> / <a href="../../tutorials/account-and-user-data-management-jn9vBjqjnsw#responsible-producers-contact-information" target="_blank">EN</a>.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateResponsibleProducerRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Use this resource to get a list of responsible producers for the compliance of the product with EU regulations. Read more: <a href="../../tutorials/jak-zarzadzac-kontem-danymi-uzytkownika-ZM9YAKgPgi2#dane-teleadresowe-producenta" target="_blank">PL</a> / <a href="../../tutorials/account-and-user-data-management-jn9vBjqjnsw#responsible-producers-contact-information" target="_blank">EN</a>.
 */
export interface ResponsibleProducersRequestBuilderGetQueryParameters {
    /**
     * Number of returned responsible producers data.
     */
    limit?: number;
    /**
     * Index of first returned responsible producers data from all search results.
     */
    offset?: number;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ResponsibleProducersGetResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeResponsibleProducersGetResponse(writer: SerializationWriter, responsibleProducersGetResponse: Partial<ResponsibleProducersGetResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!responsibleProducersGetResponse || isSerializingDerivedType) { return; }
    writer.writeNumberValue("count", responsibleProducersGetResponse.count);
    writer.writeCollectionOfObjectValues<ResponsibleProducerResponse>("responsibleProducers", responsibleProducersGetResponse.responsibleProducers, serializeResponsibleProducerResponse);
    writer.writeNumberValue("totalCount", responsibleProducersGetResponse.totalCount);
    writer.writeAdditionalData(responsibleProducersGetResponse.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const ResponsibleProducersRequestBuilderUriTemplate = "{+baseurl}/sale/responsible-producers{?limit*,offset*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ResponsibleProducersRequestBuilderNavigationMetadata: Record<Exclude<keyof ResponsibleProducersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: ResponsibleProducersItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ResponsibleProducersRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ResponsibleProducersRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            400: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAuthErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createResponsibleProducersGetResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: ResponsibleProducersRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            400: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createAuthErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createErrorsHolderFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createResponsibleProducerResponseFromDiscriminatorValue,
        requestBodyContentType: "application/vnd.allegro.public.v1+json",
        requestBodySerializer: serializeCreateResponsibleProducerRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
