/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAuthErrorFromDiscriminatorValue, createDeliveryServicesDtoFromDiscriminatorValue, createError403FromDiscriminatorValue, createError504FromDiscriminatorValue, serializeError403, serializeError504, type AuthError, type DeliveryServicesDto, type Error403, type Error504 } from '../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DeliveryServicesDto403Error}
 */
// @ts-ignore
export function createDeliveryServicesDto403ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDeliveryServicesDto403Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DeliveryServicesDto504Error}
 */
// @ts-ignore
export function createDeliveryServicesDto504ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDeliveryServicesDto504Error;
}
export interface DeliveryServicesDto403Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Array of errors.
     */
    errors?: Error403[] | null;
}
export interface DeliveryServicesDto504Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Array of errors.
     */
    errors?: Error504[] | null;
}
/**
 * Builds and executes requests for operations under /shipment-management/delivery-services
 */
export interface DeliveryServicesRequestBuilder extends BaseRequestBuilder<DeliveryServicesRequestBuilder> {
    /**
     * Use this resource to get delivery services available for user. It returns services provided by Allegro and contracts with carriers owned by user and configured by GUI. Read more: <a href="../../tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-pobrac-liste-uslug-dostawy" target="_blank">PL</a> / <a href="../../tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV#how-to-retrieve-a-list-of-delivery-services" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DeliveryServicesDto>}
     * @throws {AuthError} error when the service returns a 401 status code
     * @throws {DeliveryServicesDto403Error} error when the service returns a 403 status code
     * @throws {DeliveryServicesDto504Error} error when the service returns a 504 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<DeliveryServicesDto | undefined>;
    /**
     * Use this resource to get delivery services available for user. It returns services provided by Allegro and contracts with carriers owned by user and configured by GUI. Read more: <a href="../../tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-pobrac-liste-uslug-dostawy" target="_blank">PL</a> / <a href="../../tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV#how-to-retrieve-a-list-of-delivery-services" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * The deserialization information for the current model
 * @param DeliveryServicesDto403Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDeliveryServicesDto403Error(deliveryServicesDto403Error: Partial<DeliveryServicesDto403Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "errors": n => { deliveryServicesDto403Error.errors = n.getCollectionOfObjectValues<Error403>(createError403FromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param DeliveryServicesDto504Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDeliveryServicesDto504Error(deliveryServicesDto504Error: Partial<DeliveryServicesDto504Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "errors": n => { deliveryServicesDto504Error.errors = n.getCollectionOfObjectValues<Error504>(createError504FromDiscriminatorValue); },
    }
}
/**
 * Serializes information the current object
 * @param DeliveryServicesDto403Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDeliveryServicesDto403Error(writer: SerializationWriter, deliveryServicesDto403Error: Partial<DeliveryServicesDto403Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!deliveryServicesDto403Error || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<Error403>("errors", deliveryServicesDto403Error.errors, serializeError403);
    writer.writeAdditionalData(deliveryServicesDto403Error.additionalData);
}
/**
 * Serializes information the current object
 * @param DeliveryServicesDto504Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDeliveryServicesDto504Error(writer: SerializationWriter, deliveryServicesDto504Error: Partial<DeliveryServicesDto504Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!deliveryServicesDto504Error || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<Error504>("errors", deliveryServicesDto504Error.errors, serializeError504);
    writer.writeAdditionalData(deliveryServicesDto504Error.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const DeliveryServicesRequestBuilderUriTemplate = "{+baseurl}/shipment-management/delivery-services";
/**
 * Metadata for all the requests in the request builder.
 */
export const DeliveryServicesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DeliveryServicesRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        errorMappings: {
            401: createAuthErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createDeliveryServicesDto403ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            504: createDeliveryServicesDto504ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createDeliveryServicesDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
