/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAddressBookResponseFromDiscriminatorValue, createErrorApiResponseFromDiscriminatorValue, serializeAddressBookDataPayload, type AddressBookDataPayload, type AddressBookResponse, type ErrorApiResponse } from '../../../models/index.js';
// @ts-ignore
import { AddressBookItemRequestBuilderRequestsMetadata, type AddressBookItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/user/address-book
 */
export interface AddressBookRequestBuilder extends BaseRequestBuilder<AddressBookRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.v1.user.addressBook.item collection
     * @param id Identyfikator adresu w systemie epaka.pl
     * @returns {AddressBookItemRequestBuilder}
     */
     byId(id: number) : AddressBookItemRequestBuilder;
    /**
     * Pobieranie listy adresów z książki adresowej
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AddressBookResponse>}
     * @throws {ErrorApiResponse} error when the service returns a 403 status code
     */
     get(requestConfiguration?: RequestConfiguration<AddressBookRequestBuilderGetQueryParameters> | undefined) : Promise<AddressBookResponse | undefined>;
    /**
     * Dodawanie nowego adresu
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ErrorApiResponse} error when the service returns a 403 status code
     */
     post(body: AddressBookDataPayload, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Pobieranie listy adresów z książki adresowej
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<AddressBookRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Dodawanie nowego adresu
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: AddressBookDataPayload, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Pobieranie listy adresów z książki adresowej
 */
export interface AddressBookRequestBuilderGetQueryParameters {
    /**
     * Miasto
     */
    city?: string;
    /**
     * Limit zwracanych zamówień
     */
    limit?: number;
    /**
     * Offset do paginacji
     */
    offset?: number;
    /**
     * Numer telefonu
     */
    phone?: string;
    /**
     * Tekst do do wyszukania
     */
    query?: string;
    /**
     * Ulica
     */
    street?: string;
}
/**
 * Uri template for the request builder.
 */
export const AddressBookRequestBuilderUriTemplate = "{+baseurl}/v1/user/address-book{?city*,limit*,offset*,phone*,query*,street*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AddressBookRequestBuilderNavigationMetadata: Record<Exclude<keyof AddressBookRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: AddressBookItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const AddressBookRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AddressBookRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            403: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAddressBookResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: AddressBookRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            403: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeAddressBookDataPayload,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
