/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createThreadFromDiscriminatorValue, type Thread } from '../../../models/index.js';
// @ts-ignore
import { MessagesRequestBuilderRequestsMetadata, type MessagesRequestBuilder } from './messages/index.js';
// @ts-ignore
import { ReadRequestBuilderRequestsMetadata, type ReadRequestBuilder } from './read/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /messaging/threads/{threadId}
 */
export interface WithThreadItemRequestBuilder extends BaseRequestBuilder<WithThreadItemRequestBuilder> {
    /**
     * The messages property
     */
    get messages(): MessagesRequestBuilder;
    /**
     * The read property
     */
    get read(): ReadRequestBuilder;
    /**
     * Use this resource to get thread with provided identifier. Read more: <a href="../../tutorials/jak-zarzadzac-centrum-wiadomosci-XxWm2K890Fk#szczegolowe-informacje-o-danym-watku" target="_blank">PL</a> / <a href="../../tutorials/how-to-manage-the-message-center-g05avyGlZUW#information-about-a-particular-thread" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Thread>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Thread | undefined>;
    /**
     * Use this resource to get thread with provided identifier. Read more: <a href="../../tutorials/jak-zarzadzac-centrum-wiadomosci-XxWm2K890Fk#szczegolowe-informacje-o-danym-watku" target="_blank">PL</a> / <a href="../../tutorials/how-to-manage-the-message-center-g05avyGlZUW#information-about-a-particular-thread" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithThreadItemRequestBuilderUriTemplate = "{+baseurl}/messaging/threads/{threadId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithThreadItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithThreadItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    messages: {
        requestsMetadata: MessagesRequestBuilderRequestsMetadata,
    },
    read: {
        requestsMetadata: ReadRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithThreadItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithThreadItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        adapterMethodName: "send",
        responseBodyFactory:  createThreadFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
