/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AttachmentsRequestBuilderNavigationMetadata, AttachmentsRequestBuilderRequestsMetadata, type AttachmentsRequestBuilder } from './attachments/index.js';
// @ts-ignore
import { ImpliedWarrantiesRequestBuilderNavigationMetadata, ImpliedWarrantiesRequestBuilderRequestsMetadata, type ImpliedWarrantiesRequestBuilder } from './impliedWarranties/index.js';
// @ts-ignore
import { ReturnPoliciesRequestBuilderNavigationMetadata, ReturnPoliciesRequestBuilderRequestsMetadata, type ReturnPoliciesRequestBuilder } from './returnPolicies/index.js';
// @ts-ignore
import { type WarrantiesRequestBuilder, WarrantiesRequestBuilderNavigationMetadata, WarrantiesRequestBuilderRequestsMetadata } from './warranties/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /after-sales-service-conditions
 */
export interface AfterSalesServiceConditionsRequestBuilder extends BaseRequestBuilder<AfterSalesServiceConditionsRequestBuilder> {
    /**
     * The attachments property
     */
    get attachments(): AttachmentsRequestBuilder;
    /**
     * The impliedWarranties property
     */
    get impliedWarranties(): ImpliedWarrantiesRequestBuilder;
    /**
     * The returnPolicies property
     */
    get returnPolicies(): ReturnPoliciesRequestBuilder;
    /**
     * The warranties property
     */
    get warranties(): WarrantiesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AfterSalesServiceConditionsRequestBuilderUriTemplate = "{+baseurl}/after-sales-service-conditions";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AfterSalesServiceConditionsRequestBuilderNavigationMetadata: Record<Exclude<keyof AfterSalesServiceConditionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    attachments: {
        requestsMetadata: AttachmentsRequestBuilderRequestsMetadata,
        navigationMetadata: AttachmentsRequestBuilderNavigationMetadata,
    },
    impliedWarranties: {
        requestsMetadata: ImpliedWarrantiesRequestBuilderRequestsMetadata,
        navigationMetadata: ImpliedWarrantiesRequestBuilderNavigationMetadata,
    },
    returnPolicies: {
        requestsMetadata: ReturnPoliciesRequestBuilderRequestsMetadata,
        navigationMetadata: ReturnPoliciesRequestBuilderNavigationMetadata,
    },
    warranties: {
        requestsMetadata: WarrantiesRequestBuilderRequestsMetadata,
        navigationMetadata: WarrantiesRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
