/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { PriceRequestBuilderRequestsMetadata, type PriceRequestBuilder } from './price/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/order/services/insurance
 */
export interface InsuranceRequestBuilder extends BaseRequestBuilder<InsuranceRequestBuilder> {
    /**
     * The price property
     */
    get price(): PriceRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const InsuranceRequestBuilderUriTemplate = "{+baseurl}/v1/order/services/insurance";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const InsuranceRequestBuilderNavigationMetadata: Record<Exclude<keyof InsuranceRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    price: {
        requestsMetadata: PriceRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
