/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBadRequestResponseFromDiscriminatorValue, createErrorApiResponseFromDiscriminatorValue, createPaymentDataFromDiscriminatorValue, serializeCreateCollectivePaymentBody, serializePaymentData, type BadRequestResponse, type CreateCollectivePaymentBody, type ErrorApiResponse, type PaymentData } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/user/payments/create-collective
 */
export interface CreateCollectiveRequestBuilder extends BaseRequestBuilder<CreateCollectiveRequestBuilder> {
    /**
     * Metoda służy do utworzenia płatności zbiorczej, dla podanych identyfikatorów płatności.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PaymentData>}
     * @throws {BadRequestResponse} error when the service returns a 400 status code
     * @throws {ErrorApiResponse} error when the service returns a 403 status code
     * @throws {ErrorApiResponse} error when the service returns a 404 status code
     * @throws {ErrorApiResponse} error when the service returns a 409 status code
     */
     post(body: CreateCollectivePaymentBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PaymentData | undefined>;
    /**
     * Metoda służy do utworzenia płatności zbiorczej, dla podanych identyfikatorów płatności.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateCollectivePaymentBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CreateCollectiveRequestBuilderUriTemplate = "{+baseurl}/v1/user/payments/create-collective";
/**
 * Metadata for all the requests in the request builder.
 */
export const CreateCollectiveRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: CreateCollectiveRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBadRequestResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPaymentDataFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateCollectivePaymentBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
