/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createInvoiceFromDiscriminatorValue, serializeInvoice, type Invoice } from '../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /invoices/cancel.json
 */
export interface CancelJsonRequestBuilder extends BaseRequestBuilder<CancelJsonRequestBuilder> {
    /**
     * Cancel invoice
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Invoice>}
     */
     post(body: CancelPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Invoice | undefined>;
    /**
     * Cancel invoice
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CancelPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface CancelPostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The cancel_invoice_id property
     */
    cancelInvoiceId?: number | null;
    /**
     * The cancel_reason property
     */
    cancelReason?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CancelPostRequestBody}
 */
// @ts-ignore
export function createCancelPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCancelPostRequestBody;
}
/**
 * The deserialization information for the current model
 * @param CancelPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCancelPostRequestBody(cancelPostRequestBody: Partial<CancelPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "cancel_invoice_id": n => { cancelPostRequestBody.cancelInvoiceId = n.getNumberValue(); },
        "cancel_reason": n => { cancelPostRequestBody.cancelReason = n.getStringValue(); },
    }
}
/**
 * Serializes information the current object
 * @param CancelPostRequestBody The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCancelPostRequestBody(writer: SerializationWriter, cancelPostRequestBody: Partial<CancelPostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!cancelPostRequestBody || isSerializingDerivedType) { return; }
    writer.writeNumberValue("cancel_invoice_id", cancelPostRequestBody.cancelInvoiceId);
    writer.writeStringValue("cancel_reason", cancelPostRequestBody.cancelReason);
    writer.writeAdditionalData(cancelPostRequestBody.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const CancelJsonRequestBuilderUriTemplate = "{+baseurl}/invoices/cancel.json";
/**
 * Metadata for all the requests in the request builder.
 */
export const CancelJsonRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: CancelJsonRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createInvoiceFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCancelPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
