/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AllegroCarrier, createAllegroPickupDropOffPointsResponseFromDiscriminatorValue, type AllegroPickupDropOffPointsResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /order/carriers/ALLEGRO/points
 */
export interface PointsRequestBuilder extends BaseRequestBuilder<PointsRequestBuilder> {
    /**
     * Get a list of Allegro pickup drop off points. Read more: <a href="../../tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-pobrac-liste-punktow-allegro" target="_blank">PL</a> / <a href="../../tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV#how-to-retrieve-list-of-allegro-pickup-drop-off-points" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AllegroPickupDropOffPointsResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<PointsRequestBuilderGetQueryParameters> | undefined) : Promise<AllegroPickupDropOffPointsResponse | undefined>;
    /**
     * Get a list of Allegro pickup drop off points. Read more: <a href="../../tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-pobrac-liste-punktow-allegro" target="_blank">PL</a> / <a href="../../tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV#how-to-retrieve-list-of-allegro-pickup-drop-off-points" target="_blank">EN</a>.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<PointsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Get a list of Allegro pickup drop off points. Read more: <a href="../../tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-pobrac-liste-punktow-allegro" target="_blank">PL</a> / <a href="../../tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV#how-to-retrieve-list-of-allegro-pickup-drop-off-points" target="_blank">EN</a>.
 */
export interface PointsRequestBuilderGetQueryParameters {
    /**
     * List of carrier ids to filter the drop off/pick up points to only the ones where any of the listed carriers operate. In case of an empty list, all points are returned.
     */
    carriers?: AllegroCarrier[];
}
/**
 * Uri template for the request builder.
 */
export const PointsRequestBuilderUriTemplate = "{+baseurl}/order/carriers/ALLEGRO/points{?carriers*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const PointsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PointsRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        adapterMethodName: "send",
        responseBodyFactory:  createAllegroPickupDropOffPointsResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
