/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBadRequestResponseFromDiscriminatorValue, createErrorApiResponseFromDiscriminatorValue, createOrderListResponseFromDiscriminatorValue, type BadRequestResponse, type ErrorApiResponse, type OrderListResponse } from '../../../models/index.js';
// @ts-ignore
import { OrdersItemRequestBuilderNavigationMetadata, OrdersItemRequestBuilderRequestsMetadata, type OrdersItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

export type GetOrderStatusQueryParameterType = (typeof GetOrderStatusQueryParameterTypeObject)[keyof typeof GetOrderStatusQueryParameterTypeObject];
export type GetPackageStatusQueryParameterType = (typeof GetPackageStatusQueryParameterTypeObject)[keyof typeof GetPackageStatusQueryParameterTypeObject];
export type GetShippingTypeQueryParameterType = (typeof GetShippingTypeQueryParameterTypeObject)[keyof typeof GetShippingTypeQueryParameterTypeObject];
/**
 * Builds and executes requests for operations under /v1/user/orders
 */
export interface OrdersRequestBuilder extends BaseRequestBuilder<OrdersRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.v1.user.orders.item collection
     * @param id Identyfikator zamówienia w systemie epaka.pl
     * @returns {OrdersItemRequestBuilder}
     */
     byId(id: number) : OrdersItemRequestBuilder;
    /**
     * Metoda służy do zwracania listy zamówień, złożonych przez użytkownika.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<OrderListResponse>}
     * @throws {BadRequestResponse} error when the service returns a 400 status code
     * @throws {ErrorApiResponse} error when the service returns a 403 status code
     */
     get(requestConfiguration?: RequestConfiguration<OrdersRequestBuilderGetQueryParameters> | undefined) : Promise<OrderListResponse | undefined>;
    /**
     * Metoda służy do zwracania listy zamówień, złożonych przez użytkownika.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<OrdersRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Metoda służy do zwracania listy zamówień, złożonych przez użytkownika.
 */
export interface OrdersRequestBuilderGetQueryParameters {
    /**
     * Zamówienia z pobraniem
     */
    cod?: boolean;
    /**
     * Identyfikator kuriera
     */
    courierId?: number;
    /**
     * Data zwrotu pobrania od, w standardzie ISO 8601
     */
    dateCodFrom?: string;
    /**
     * Data zwrotu pobrania do, w standardzie ISO 8601
     */
    dateCodTo?: string;
    /**
     * Data zamówienia od, w standardzie ISO 8601
     */
    dateFrom?: string;
    /**
     * Data zamówienia do, w standardzie ISO 8601
     */
    dateTo?: string;
    /**
     * Zamówienia doręczone
     */
    delivered?: boolean;
    /**
     * Identyfikator zamówienia
     */
    id?: number;
    /**
     * Limit zwracanych zamówień
     */
    limit?: number;
    /**
     * Offset do paginacji
     */
    offset?: number;
    /**
     * Status zamówienia
     */
    orderStatus?: GetOrderStatusQueryParameterType;
    /**
     * Status przesyłki
     */
    packageStatus?: GetPackageStatusQueryParameterType;
    /**
     * Tekst do do wyszukania w zamówieniu
     */
    query?: string;
    /**
     * Rodzaj wysyłki:<br/><strong>envelope</strong> - Koperta<br/><strong>package</strong> - Paczka<br/><strong>pallet</strong> - Paleta<br/>
     */
    shippingType?: GetShippingTypeQueryParameterType;
}
/**
 * Uri template for the request builder.
 */
export const OrdersRequestBuilderUriTemplate = "{+baseurl}/v1/user/orders{?cod*,courierId*,dateCodFrom*,dateCodTo*,dateFrom*,dateTo*,delivered*,id*,limit*,offset*,orderStatus*,packageStatus*,query*,shippingType*}";
export const GetOrderStatusQueryParameterTypeObject = {
    Waiting_for_payment: "waiting_for_payment",
    In_progress: "in_progress",
    Ended: "ended",
    Errors: "errors",
    Canceled: "canceled",
    Paid: "paid",
} as const;
export const GetPackageStatusQueryParameterTypeObject = {
    Package_no_send: "package_no_send",
    Package_received_from_sender: "package_received_from_sender",
    Package_on_transit: "package_on_transit",
    Package_in_delivery: "package_in_delivery",
    Package_delivered: "package_delivered",
    Package_delivery_problem: "package_delivery_problem",
    Package_damaged: "package_damaged",
    Wrong_address: "wrong_address",
    Return_to_sender: "return_to_sender",
    Package_sending_in_point: "package_sending_in_point",
    Package_waiting_in_point: "package_waiting_in_point",
    Package_sending_in_paczkomat: "package_sending_in_paczkomat",
    Package_waiting_in_paczkomat: "package_waiting_in_paczkomat",
} as const;
export const GetShippingTypeQueryParameterTypeObject = {
    Envelope: "envelope",
    PackageEscaped: "package",
    Pallet: "pallet",
} as const;
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OrdersRequestBuilderNavigationMetadata: Record<Exclude<keyof OrdersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: OrdersItemRequestBuilderRequestsMetadata,
        navigationMetadata: OrdersItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const OrdersRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: OrdersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBadRequestResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createOrderListResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
