/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAfterSalesServicesAttachmentFromDiscriminatorValue, type AfterSalesServicesAttachment } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /after-sales-service-conditions/attachments/{attachmentId}
 */
export interface WithAttachmentItemRequestBuilder extends BaseRequestBuilder<WithAttachmentItemRequestBuilder> {
    /**
     * Upload an after sale services attachment.This operation should be used after creating an offer attachment with *POST /sale/offer-attachments***Important!** You can find the URL address to upload the file to our server in the *Location* response header of *POST /after-sales-service-conditions/attachments*. The URL is unique and one-time. As its format may change in time, you should always use the address from the header. Do not compose the address on your own. Read more: <a href="../../tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-dodac-zalacznik-do-informacji-o-gwarancjach" target="_blank">PL</a> / <a href="../../tutorials/how-to-process-list-of-offers-m09BKA5v8H3#how-to-add-attachment-to-warranty-information" target="_blank">EN</a>.
     * @param body Binary request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AfterSalesServicesAttachment>}
     */
     put(body: ArrayBuffer | undefined, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AfterSalesServicesAttachment | undefined>;
    /**
     * Upload an after sale services attachment.This operation should be used after creating an offer attachment with *POST /sale/offer-attachments***Important!** You can find the URL address to upload the file to our server in the *Location* response header of *POST /after-sales-service-conditions/attachments*. The URL is unique and one-time. As its format may change in time, you should always use the address from the header. Do not compose the address on your own. Read more: <a href="../../tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-dodac-zalacznik-do-informacji-o-gwarancjach" target="_blank">PL</a> / <a href="../../tutorials/how-to-process-list-of-offers-m09BKA5v8H3#how-to-add-attachment-to-warranty-information" target="_blank">EN</a>.
     * @param body Binary request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: ArrayBuffer | undefined, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithAttachmentItemRequestBuilderUriTemplate = "{+baseurl}/after-sales-service-conditions/attachments/{attachmentId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithAttachmentItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: WithAttachmentItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.allegro.public.v1+json",
        adapterMethodName: "send",
        responseBodyFactory:  createAfterSalesServicesAttachmentFromDiscriminatorValue,
        requestBodyContentType: "application/pdf",
        requestInformationContentSetMethod: "setStreamContent",
    },
};
/* tslint:enable */
/* eslint-enable */
