/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBadRequestResponseFromDiscriminatorValue, createPickupHoursResponseFromDiscriminatorValue, type BadRequestResponse, type PickupHoursResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

export type GetServiceTypeQueryParameterType = (typeof GetServiceTypeQueryParameterTypeObject)[keyof typeof GetServiceTypeQueryParameterTypeObject];
export type GetTypeQueryParameterType = (typeof GetTypeQueryParameterTypeObject)[keyof typeof GetTypeQueryParameterTypeObject];
/**
 * Builds and executes requests for operations under /v1/order/pickup-hours
 */
export interface PickupHoursRequestBuilder extends BaseRequestBuilder<PickupHoursRequestBuilder> {
    /**
     * Metoda służy do pobrania godzin nadania przesyłki, dla wybranego kuriera oraz dnia.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PickupHoursResponse>}
     * @throws {BadRequestResponse} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<PickupHoursRequestBuilderGetQueryParameters> | undefined) : Promise<PickupHoursResponse | undefined>;
    /**
     * Metoda służy do pobrania godzin nadania przesyłki, dla wybranego kuriera oraz dnia.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<PickupHoursRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Metoda służy do pobrania godzin nadania przesyłki, dla wybranego kuriera oraz dnia.
 */
export interface PickupHoursRequestBuilderGetQueryParameters {
    /**
     * Id kuriera
     */
    courierId?: number;
    /**
     * Data nadania w standardzie ISO 8601
     */
    date?: string;
    /**
     * Parametr dostępny dla kuriera DPD<br/>Etykieta:<br/><strong>false</strong> - Etykietę drukuję nadawca<br/><strong>true</strong> - Etykietę przywiezie kurier
     */
    label?: boolean;
    /**
     * Parametr dostępny dla kuriera UPS<br/>Liczba opakowań
     */
    packagesNumber?: number;
    /**
     * Kod pocztowy nadawcy
     */
    postCode?: string;
    /**
     * Kod kraj nadawcy
     */
    senderCountry?: string;
    /**
     * Parametr dostępny dla kuriera UPS<br/>Rodzaj serwisu:<br/>UPS Standard (usługa drogowa)<br/>UPS Express Saver<br/>UPS Express (doręczenie do godz. 12)<br/>UPS Express Plus (doręczenie do godz. 9)
     */
    serviceType?: GetServiceTypeQueryParameterType;
    /**
     * Parametr dostępny dla kuriera DHL<br/>Typ przesyłki:<br/>ex – paczki do 31,5 kg i koperty<br/>dr – paczki powyżej 31,5 kg i palety<br/>express - dla DHL Express
     */
    type?: GetTypeQueryParameterType;
    /**
     * Parametr dostępny dla kuriera UPS<br/>Łączna waga przesyłki
     */
    weight?: number;
}
/**
 * Uri template for the request builder.
 */
export const PickupHoursRequestBuilderUriTemplate = "{+baseurl}/v1/order/pickup-hours?courierId={courierId}&date={date}&postCode={postCode}&senderCountry={senderCountry}{&label*,packagesNumber*,serviceType*,type*,weight*}";
export const GetServiceTypeQueryParameterTypeObject = {
    UPSStandard: "UPS Standard",
    UPSExpressSaver: "UPS Express Saver",
    UPSExpress: "UPS Express",
    UPSExpressPlus: "UPS Express Plus",
} as const;
export const GetTypeQueryParameterTypeObject = {
    Ex: "ex",
    Dr: "dr",
    Express: "express",
} as const;
/**
 * Metadata for all the requests in the request builder.
 */
export const PickupHoursRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PickupHoursRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBadRequestResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPickupHoursResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
