/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBadRequestResponseFromDiscriminatorValue, createErrorApiResponseFromDiscriminatorValue, type BadRequestResponse, type ErrorApiResponse } from '../../../../models/index.js';
// @ts-ignore
import { MultipartBody, serializeMultipartBody, type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/order/{id}/add-package-photos
 */
export interface AddPackagePhotosRequestBuilder extends BaseRequestBuilder<AddPackagePhotosRequestBuilder> {
    /**
     * Metoda umożliwia przesłanie 5 zdjęc dokumentujących parametry przesyłki: Dodaj zdjęcia dokumentujące parametry przesyłki:<ol><li>Zdjęcia z taśmą mierniczą na każdym boku i wskazaniem wyniku pomiaru.</li><li>Zdjęcia kształtu całej przesyłki i formy jej opakowania.</li><li>Zdjęcia na wadze ze wskazaniem wyniku pomiaru(powinna być to waga legalizowana)</li></ol></br>Możliwe jest przesłanie maksymalnie 5 zdjęć w formacie .png lub .jpg w rozmiarze do 5MB każde.</br>WAŻNE: Zdjęcia mogą posłużyć jako dowód w sprawie przy ewentualnej reklamacji u przewoźnika. Firma epaka.pl S.A. nie odpowiada za skutek prawny i stanowisko przewoźnika.</br></br><strong>WAŻNE. Możliwe jest jednorazowe wykonanie endpointu w ciągu 24 godzin od złożenia zamówienia.</strong>
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {BadRequestResponse} error when the service returns a 400 status code
     * @throws {ErrorApiResponse} error when the service returns a 403 status code
     * @throws {ErrorApiResponse} error when the service returns a 422 status code
     */
     post(body: MultipartBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Metoda umożliwia przesłanie 5 zdjęc dokumentujących parametry przesyłki: Dodaj zdjęcia dokumentujące parametry przesyłki:<ol><li>Zdjęcia z taśmą mierniczą na każdym boku i wskazaniem wyniku pomiaru.</li><li>Zdjęcia kształtu całej przesyłki i formy jej opakowania.</li><li>Zdjęcia na wadze ze wskazaniem wyniku pomiaru(powinna być to waga legalizowana)</li></ol></br>Możliwe jest przesłanie maksymalnie 5 zdjęć w formacie .png lub .jpg w rozmiarze do 5MB każde.</br>WAŻNE: Zdjęcia mogą posłużyć jako dowód w sprawie przy ewentualnej reklamacji u przewoźnika. Firma epaka.pl S.A. nie odpowiada za skutek prawny i stanowisko przewoźnika.</br></br><strong>WAŻNE. Możliwe jest jednorazowe wykonanie endpointu w ciągu 24 godzin od złożenia zamówienia.</strong>
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MultipartBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ImagesPayloadPostRequestBody}
 */
// @ts-ignore
export function createImagesPayloadPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoImagesPayloadPostRequestBody;
}
/**
 * The deserialization information for the current model
 * @param ImagesPayloadPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoImagesPayloadPostRequestBody(imagesPayloadPostRequestBody: Partial<ImagesPayloadPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "file": n => { imagesPayloadPostRequestBody.file = n.getByteArrayValue(); },
    }
}
/**
 * Tablica ze zdjęciami paczki.
 */
export interface ImagesPayloadPostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The file property
     */
    file?: ArrayBuffer | null;
}
/**
 * Serializes information the current object
 * @param ImagesPayloadPostRequestBody The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeImagesPayloadPostRequestBody(writer: SerializationWriter, imagesPayloadPostRequestBody: Partial<ImagesPayloadPostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!imagesPayloadPostRequestBody || isSerializingDerivedType) { return; }
    writer.writeByteArrayValue("file", imagesPayloadPostRequestBody.file);
    writer.writeAdditionalData(imagesPayloadPostRequestBody.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const AddPackagePhotosRequestBuilderUriTemplate = "{+baseurl}/v1/order/{id}/add-package-photos";
/**
 * Metadata for all the requests in the request builder.
 */
export const AddPackagePhotosRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: AddPackagePhotosRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBadRequestResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createErrorApiResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "multipart/form-data",
        requestBodySerializer: serializeMultipartBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
