/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBadRequestResponseFromDiscriminatorValue, createPickupDateResponseFromDiscriminatorValue, type BadRequestResponse, type PickupDateResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/order/pickup-date
 */
export interface PickupDateRequestBuilder extends BaseRequestBuilder<PickupDateRequestBuilder> {
    /**
     * Metoda służy do pobrania listy dostępnych dni nadania, dla wybranego kuriera.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PickupDateResponse>}
     * @throws {BadRequestResponse} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<PickupDateRequestBuilderGetQueryParameters> | undefined) : Promise<PickupDateResponse | undefined>;
    /**
     * Metoda służy do pobrania listy dostępnych dni nadania, dla wybranego kuriera.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<PickupDateRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Metoda służy do pobrania listy dostępnych dni nadania, dla wybranego kuriera.
 */
export interface PickupDateRequestBuilderGetQueryParameters {
    /**
     * Id kurierów.
     */
    couriers?: number[];
    /**
     * Kod pocztowy nadawcy
     */
    postCode?: string;
}
/**
 * Uri template for the request builder.
 */
export const PickupDateRequestBuilderUriTemplate = "{+baseurl}/v1/order/pickup-date{?couriers*,postCode*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const PickupDateRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PickupDateRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBadRequestResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPickupDateResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
