/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAvailableCarriersEnvelopeFromDiscriminatorValue, createCancelOrderEnvelopeFromDiscriminatorValue, createCreateOrderEnvelopeFromDiscriminatorValue, createGetCourierPickupTimeEnvelopeFromDiscriminatorValue, createGetCourierPointEnvelopeFromDiscriminatorValue, createGetLabelEnvelopeFromDiscriminatorValue, createGetOrdersEnvelopeFromDiscriminatorValue, createGetProtocolEnvelopeFromDiscriminatorValue, createGetStatusEnvelopeFromDiscriminatorValue, createOrderValuationEnvelopeFromDiscriminatorValue, createOrderValuationV2EnvelopeFromDiscriminatorValue, createPolkurierApiResponseFromDiscriminatorValue, deserializeIntoAvailableCarriersEnvelope, deserializeIntoCancelOrderEnvelope, deserializeIntoCreateOrderEnvelope, deserializeIntoGetCourierPickupTimeEnvelope, deserializeIntoGetCourierPointEnvelope, deserializeIntoGetLabelEnvelope, deserializeIntoGetOrdersEnvelope, deserializeIntoGetProtocolEnvelope, deserializeIntoGetStatusEnvelope, deserializeIntoOrderValuationEnvelope, deserializeIntoOrderValuationV2Envelope, serializeAvailableCarriersEnvelope, serializeCancelOrderEnvelope, serializeCreateOrderEnvelope, serializeGetCourierPickupTimeEnvelope, serializeGetCourierPointEnvelope, serializeGetLabelEnvelope, serializeGetOrdersEnvelope, serializeGetProtocolEnvelope, serializeGetStatusEnvelope, serializeOrderValuationEnvelope, serializeOrderValuationV2Envelope, serializePolkurierApiResponse, type AvailableCarriersEnvelope, type CancelOrderEnvelope, type CreateOrderEnvelope, type GetCourierPickupTimeEnvelope, type GetCourierPointEnvelope, type GetLabelEnvelope, type GetOrdersEnvelope, type GetProtocolEnvelope, type GetStatusEnvelope, type OrderValuationEnvelope, type OrderValuationV2Envelope, type PolkurierApiResponse } from './models/index.js';
// @ts-ignore
import { apiClientProxifier, ParseNodeFactoryRegistry, SerializationWriterFactoryRegistry, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestAdapter, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';
// @ts-ignore
import { FormParseNodeFactory, FormSerializationWriterFactory } from '@microsoft/kiota-serialization-form';
// @ts-ignore
import { JsonParseNodeFactory, JsonSerializationWriterFactory } from '@microsoft/kiota-serialization-json';
// @ts-ignore
import { MultipartSerializationWriterFactory } from '@microsoft/kiota-serialization-multipart';
// @ts-ignore
import { TextParseNodeFactory, TextSerializationWriterFactory } from '@microsoft/kiota-serialization-text';

/**
 * Instantiates a new {@link PolkurierClient} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
export function createPolkurierClient(requestAdapter: RequestAdapter) {
    if (requestAdapter === undefined) {
        throw new Error("requestAdapter cannot be undefined");
    }
    const serializationWriterFactory = requestAdapter.getSerializationWriterFactory() as SerializationWriterFactoryRegistry;
    const parseNodeFactoryRegistry = requestAdapter.getParseNodeFactory() as ParseNodeFactoryRegistry;
    const backingStoreFactory = requestAdapter.getBackingStoreFactory();
    
    if (parseNodeFactoryRegistry.registerDefaultDeserializer) {
        parseNodeFactoryRegistry.registerDefaultDeserializer(JsonParseNodeFactory, backingStoreFactory);
        parseNodeFactoryRegistry.registerDefaultDeserializer(TextParseNodeFactory, backingStoreFactory);
        parseNodeFactoryRegistry.registerDefaultDeserializer(FormParseNodeFactory, backingStoreFactory);
    }
    
    if (serializationWriterFactory.registerDefaultSerializer) {
        serializationWriterFactory.registerDefaultSerializer(JsonSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(TextSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(FormSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(MultipartSerializationWriterFactory);
    }
    
    if (requestAdapter.baseUrl === undefined || requestAdapter.baseUrl === null || requestAdapter.baseUrl === "") {
        requestAdapter.baseUrl = "https://api.polkurier.pl";
    }
    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    return apiClientProxifier<PolkurierClient>(requestAdapter, pathParameters, undefined, PolkurierClientRequestsMetadata);
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AvailableCarriersEnvelope | CancelOrderEnvelope | CreateOrderEnvelope | GetCourierPickupTimeEnvelope | GetCourierPointEnvelope | GetLabelEnvelope | GetOrdersEnvelope | GetProtocolEnvelope | GetStatusEnvelope | OrderValuationEnvelope | OrderValuationV2Envelope}
 */
// @ts-ignore
export function createPolkurierMethodRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPolkurierMethodRequest;
}
/**
 * The deserialization information for the current model
 * @param PolkurierMethodRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPolkurierMethodRequest(polkurierMethodRequest: Partial<AvailableCarriersEnvelope | CancelOrderEnvelope | CreateOrderEnvelope | GetCourierPickupTimeEnvelope | GetCourierPointEnvelope | GetLabelEnvelope | GetOrdersEnvelope | GetProtocolEnvelope | GetStatusEnvelope | OrderValuationEnvelope | OrderValuationV2Envelope> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoAvailableCarriersEnvelope(polkurierMethodRequest as AvailableCarriersEnvelope),
        ...deserializeIntoCancelOrderEnvelope(polkurierMethodRequest as CancelOrderEnvelope),
        ...deserializeIntoCreateOrderEnvelope(polkurierMethodRequest as CreateOrderEnvelope),
        ...deserializeIntoGetCourierPickupTimeEnvelope(polkurierMethodRequest as GetCourierPickupTimeEnvelope),
        ...deserializeIntoGetCourierPointEnvelope(polkurierMethodRequest as GetCourierPointEnvelope),
        ...deserializeIntoGetLabelEnvelope(polkurierMethodRequest as GetLabelEnvelope),
        ...deserializeIntoGetOrdersEnvelope(polkurierMethodRequest as GetOrdersEnvelope),
        ...deserializeIntoGetProtocolEnvelope(polkurierMethodRequest as GetProtocolEnvelope),
        ...deserializeIntoGetStatusEnvelope(polkurierMethodRequest as GetStatusEnvelope),
        ...deserializeIntoOrderValuationEnvelope(polkurierMethodRequest as OrderValuationEnvelope),
        ...deserializeIntoOrderValuationV2Envelope(polkurierMethodRequest as OrderValuationV2Envelope),
    }
}
/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface PolkurierClient extends BaseRequestBuilder<PolkurierClient> {
    /**
     * Single RPC endpoint for Polkurier WebService API. Select the concrete request shape by setting `apimethod`.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PolkurierApiResponse>}
     */
     post(body: AvailableCarriersEnvelope | CancelOrderEnvelope | CreateOrderEnvelope | GetCourierPickupTimeEnvelope | GetCourierPointEnvelope | GetLabelEnvelope | GetOrdersEnvelope | GetProtocolEnvelope | GetStatusEnvelope | OrderValuationEnvelope | OrderValuationV2Envelope, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PolkurierApiResponse | undefined>;
    /**
     * Single RPC endpoint for Polkurier WebService API. Select the concrete request shape by setting `apimethod`.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: AvailableCarriersEnvelope | CancelOrderEnvelope | CreateOrderEnvelope | GetCourierPickupTimeEnvelope | GetCourierPointEnvelope | GetLabelEnvelope | GetOrdersEnvelope | GetProtocolEnvelope | GetStatusEnvelope | OrderValuationEnvelope | OrderValuationV2Envelope, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export type PolkurierMethodRequest = AvailableCarriersEnvelope | CancelOrderEnvelope | CreateOrderEnvelope | GetCourierPickupTimeEnvelope | GetCourierPointEnvelope | GetLabelEnvelope | GetOrdersEnvelope | GetProtocolEnvelope | GetStatusEnvelope | OrderValuationEnvelope | OrderValuationV2Envelope;
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PolkurierMethodRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePolkurierMethodRequest(writer: SerializationWriter, polkurierMethodRequest: Partial<AvailableCarriersEnvelope | CancelOrderEnvelope | CreateOrderEnvelope | GetCourierPickupTimeEnvelope | GetCourierPointEnvelope | GetLabelEnvelope | GetOrdersEnvelope | GetProtocolEnvelope | GetStatusEnvelope | OrderValuationEnvelope | OrderValuationV2Envelope> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    serializeAvailableCarriersEnvelope(writer, polkurierMethodRequest as AvailableCarriersEnvelope);
    serializeCancelOrderEnvelope(writer, polkurierMethodRequest as CancelOrderEnvelope);
    serializeCreateOrderEnvelope(writer, polkurierMethodRequest as CreateOrderEnvelope);
    serializeGetCourierPickupTimeEnvelope(writer, polkurierMethodRequest as GetCourierPickupTimeEnvelope);
    serializeGetCourierPointEnvelope(writer, polkurierMethodRequest as GetCourierPointEnvelope);
    serializeGetLabelEnvelope(writer, polkurierMethodRequest as GetLabelEnvelope);
    serializeGetOrdersEnvelope(writer, polkurierMethodRequest as GetOrdersEnvelope);
    serializeGetProtocolEnvelope(writer, polkurierMethodRequest as GetProtocolEnvelope);
    serializeGetStatusEnvelope(writer, polkurierMethodRequest as GetStatusEnvelope);
    serializeOrderValuationEnvelope(writer, polkurierMethodRequest as OrderValuationEnvelope);
    serializeOrderValuationV2Envelope(writer, polkurierMethodRequest as OrderValuationV2Envelope);
}
/**
 * Uri template for the request builder.
 */
export const PolkurierClientUriTemplate = "{+baseurl}";
/**
 * Metadata for all the requests in the request builder.
 */
export const PolkurierClientRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: PolkurierClientUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createPolkurierApiResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializePolkurierMethodRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
