/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { FileRequestBuilderRequestsMetadata, type FileRequestBuilder } from './file/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /order/checkout-forms/{id}/invoices/{invoiceId}
 */
export interface WithInvoiceItemRequestBuilder extends BaseRequestBuilder<WithInvoiceItemRequestBuilder> {
    /**
     * The file property
     */
    get file(): FileRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithInvoiceItemRequestBuilderUriTemplate = "{+baseurl}/order/checkout-forms/{id}/invoices/{invoiceId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithInvoiceItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithInvoiceItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    file: {
        requestsMetadata: FileRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
