/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AccountRequestBuilderNavigationMetadata, type AccountRequestBuilder } from './account/index.js';
// @ts-ignore
import { AccountJsonRequestBuilderRequestsMetadata, type AccountJsonRequestBuilder } from './accountJson/index.js';
// @ts-ignore
import { BankingRequestBuilderNavigationMetadata, type BankingRequestBuilder } from './banking/index.js';
// @ts-ignore
import { CategoriesRequestBuilderNavigationMetadata, type CategoriesRequestBuilder } from './categories/index.js';
// @ts-ignore
import { CategoriesJsonRequestBuilderRequestsMetadata, type CategoriesJsonRequestBuilder } from './categoriesJson/index.js';
// @ts-ignore
import { ClientsRequestBuilderNavigationMetadata, type ClientsRequestBuilder } from './clients/index.js';
// @ts-ignore
import { ClientsJsonRequestBuilderRequestsMetadata, type ClientsJsonRequestBuilder } from './clientsJson/index.js';
// @ts-ignore
import { DepartmentsRequestBuilderNavigationMetadata, type DepartmentsRequestBuilder } from './departments/index.js';
// @ts-ignore
import { DepartmentsJsonRequestBuilderRequestsMetadata, type DepartmentsJsonRequestBuilder } from './departmentsJson/index.js';
// @ts-ignore
import { InvoicesRequestBuilderNavigationMetadata, type InvoicesRequestBuilder } from './invoices/index.js';
// @ts-ignore
import { InvoicesJsonRequestBuilderRequestsMetadata, type InvoicesJsonRequestBuilder } from './invoicesJson/index.js';
// @ts-ignore
import { IssuersRequestBuilderNavigationMetadata, type IssuersRequestBuilder } from './issuers/index.js';
// @ts-ignore
import { IssuersJsonRequestBuilderRequestsMetadata, type IssuersJsonRequestBuilder } from './issuersJson/index.js';
// @ts-ignore
import { LoginJsonRequestBuilderRequestsMetadata, type LoginJsonRequestBuilder } from './loginJson/index.js';
// @ts-ignore
import { Price_listsRequestBuilderNavigationMetadata, type Price_listsRequestBuilder } from './price_lists/index.js';
// @ts-ignore
import { Price_listsJsonRequestBuilderRequestsMetadata, type Price_listsJsonRequestBuilder } from './price_listsJson/index.js';
// @ts-ignore
import { PrintersJsonRequestBuilderRequestsMetadata, type PrintersJsonRequestBuilder } from './printersJson/index.js';
// @ts-ignore
import { ProductsRequestBuilderNavigationMetadata, type ProductsRequestBuilder } from './products/index.js';
// @ts-ignore
import { ProductsJsonRequestBuilderRequestsMetadata, type ProductsJsonRequestBuilder } from './productsJson/index.js';
// @ts-ignore
import { RecurringsRequestBuilderNavigationMetadata, type RecurringsRequestBuilder } from './recurrings/index.js';
// @ts-ignore
import { RecurringsJsonRequestBuilderRequestsMetadata, type RecurringsJsonRequestBuilder } from './recurringsJson/index.js';
// @ts-ignore
import { type Warehouse_actionsJsonRequestBuilder, Warehouse_actionsJsonRequestBuilderRequestsMetadata } from './warehouse_actionsJson/index.js';
// @ts-ignore
import { type Warehouse_documentsRequestBuilder, Warehouse_documentsRequestBuilderNavigationMetadata } from './warehouse_documents/index.js';
// @ts-ignore
import { type Warehouse_documentsJsonRequestBuilder, Warehouse_documentsJsonRequestBuilderRequestsMetadata } from './warehouse_documentsJson/index.js';
// @ts-ignore
import { type WarehousesRequestBuilder, WarehousesRequestBuilderNavigationMetadata } from './warehouses/index.js';
// @ts-ignore
import { type WarehousesJsonRequestBuilder, WarehousesJsonRequestBuilderRequestsMetadata } from './warehousesJson/index.js';
// @ts-ignore
import { type WebhooksRequestBuilder, WebhooksRequestBuilderNavigationMetadata } from './webhooks/index.js';
// @ts-ignore
import { type WebhooksJsonRequestBuilder, WebhooksJsonRequestBuilderRequestsMetadata } from './webhooksJson/index.js';
// @ts-ignore
import { apiClientProxifier, ParseNodeFactoryRegistry, SerializationWriterFactoryRegistry, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type RequestAdapter } from '@microsoft/kiota-abstractions';
// @ts-ignore
import { FormParseNodeFactory, FormSerializationWriterFactory } from '@microsoft/kiota-serialization-form';
// @ts-ignore
import { JsonParseNodeFactory, JsonSerializationWriterFactory } from '@microsoft/kiota-serialization-json';
// @ts-ignore
import { MultipartSerializationWriterFactory } from '@microsoft/kiota-serialization-multipart';
// @ts-ignore
import { TextParseNodeFactory, TextSerializationWriterFactory } from '@microsoft/kiota-serialization-text';

/**
 * Instantiates a new {@link FakturowniaClient} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
export function createFakturowniaClient(requestAdapter: RequestAdapter) {
    if (requestAdapter === undefined) {
        throw new Error("requestAdapter cannot be undefined");
    }
    const serializationWriterFactory = requestAdapter.getSerializationWriterFactory() as SerializationWriterFactoryRegistry;
    const parseNodeFactoryRegistry = requestAdapter.getParseNodeFactory() as ParseNodeFactoryRegistry;
    const backingStoreFactory = requestAdapter.getBackingStoreFactory();
    
    if (parseNodeFactoryRegistry.registerDefaultDeserializer) {
        parseNodeFactoryRegistry.registerDefaultDeserializer(JsonParseNodeFactory, backingStoreFactory);
        parseNodeFactoryRegistry.registerDefaultDeserializer(TextParseNodeFactory, backingStoreFactory);
        parseNodeFactoryRegistry.registerDefaultDeserializer(FormParseNodeFactory, backingStoreFactory);
    }
    
    if (serializationWriterFactory.registerDefaultSerializer) {
        serializationWriterFactory.registerDefaultSerializer(JsonSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(TextSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(FormSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(MultipartSerializationWriterFactory);
    }
    
    if (requestAdapter.baseUrl === undefined || requestAdapter.baseUrl === null || requestAdapter.baseUrl === "") {
        requestAdapter.baseUrl = "https://{prefix}.fakturownia.pl";
    }
    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    return apiClientProxifier<FakturowniaClient>(requestAdapter, pathParameters, FakturowniaClientNavigationMetadata, undefined);
}
/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface FakturowniaClient extends BaseRequestBuilder<FakturowniaClient> {
    /**
     * The account property
     */
    get account(): AccountRequestBuilder;
    /**
     * The accountJson property
     */
    get accountJson(): AccountJsonRequestBuilder;
    /**
     * The banking property
     */
    get banking(): BankingRequestBuilder;
    /**
     * The categories property
     */
    get categories(): CategoriesRequestBuilder;
    /**
     * The categoriesJson property
     */
    get categoriesJson(): CategoriesJsonRequestBuilder;
    /**
     * The clients property
     */
    get clients(): ClientsRequestBuilder;
    /**
     * The clientsJson property
     */
    get clientsJson(): ClientsJsonRequestBuilder;
    /**
     * The departments property
     */
    get departments(): DepartmentsRequestBuilder;
    /**
     * The departmentsJson property
     */
    get departmentsJson(): DepartmentsJsonRequestBuilder;
    /**
     * The invoices property
     */
    get invoices(): InvoicesRequestBuilder;
    /**
     * The invoicesJson property
     */
    get invoicesJson(): InvoicesJsonRequestBuilder;
    /**
     * The issuers property
     */
    get issuers(): IssuersRequestBuilder;
    /**
     * The issuersJson property
     */
    get issuersJson(): IssuersJsonRequestBuilder;
    /**
     * The loginJson property
     */
    get loginJson(): LoginJsonRequestBuilder;
    /**
     * The price_lists property
     */
    get price_lists(): Price_listsRequestBuilder;
    /**
     * The price_listsJson property
     */
    get price_listsJson(): Price_listsJsonRequestBuilder;
    /**
     * The printersJson property
     */
    get printersJson(): PrintersJsonRequestBuilder;
    /**
     * The products property
     */
    get products(): ProductsRequestBuilder;
    /**
     * The productsJson property
     */
    get productsJson(): ProductsJsonRequestBuilder;
    /**
     * The recurrings property
     */
    get recurrings(): RecurringsRequestBuilder;
    /**
     * The recurringsJson property
     */
    get recurringsJson(): RecurringsJsonRequestBuilder;
    /**
     * The warehouse_actionsJson property
     */
    get warehouse_actionsJson(): Warehouse_actionsJsonRequestBuilder;
    /**
     * The warehouse_documents property
     */
    get warehouse_documents(): Warehouse_documentsRequestBuilder;
    /**
     * The warehouse_documentsJson property
     */
    get warehouse_documentsJson(): Warehouse_documentsJsonRequestBuilder;
    /**
     * The warehouses property
     */
    get warehouses(): WarehousesRequestBuilder;
    /**
     * The warehousesJson property
     */
    get warehousesJson(): WarehousesJsonRequestBuilder;
    /**
     * The webhooks property
     */
    get webhooks(): WebhooksRequestBuilder;
    /**
     * The webhooksJson property
     */
    get webhooksJson(): WebhooksJsonRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const FakturowniaClientUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const FakturowniaClientNavigationMetadata: Record<Exclude<keyof FakturowniaClient, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    account: {
        navigationMetadata: AccountRequestBuilderNavigationMetadata,
    },
    accountJson: {
        requestsMetadata: AccountJsonRequestBuilderRequestsMetadata,
    },
    banking: {
        navigationMetadata: BankingRequestBuilderNavigationMetadata,
    },
    categories: {
        navigationMetadata: CategoriesRequestBuilderNavigationMetadata,
    },
    categoriesJson: {
        requestsMetadata: CategoriesJsonRequestBuilderRequestsMetadata,
    },
    clients: {
        navigationMetadata: ClientsRequestBuilderNavigationMetadata,
    },
    clientsJson: {
        requestsMetadata: ClientsJsonRequestBuilderRequestsMetadata,
    },
    departments: {
        navigationMetadata: DepartmentsRequestBuilderNavigationMetadata,
    },
    departmentsJson: {
        requestsMetadata: DepartmentsJsonRequestBuilderRequestsMetadata,
    },
    invoices: {
        navigationMetadata: InvoicesRequestBuilderNavigationMetadata,
    },
    invoicesJson: {
        requestsMetadata: InvoicesJsonRequestBuilderRequestsMetadata,
    },
    issuers: {
        navigationMetadata: IssuersRequestBuilderNavigationMetadata,
    },
    issuersJson: {
        requestsMetadata: IssuersJsonRequestBuilderRequestsMetadata,
    },
    loginJson: {
        requestsMetadata: LoginJsonRequestBuilderRequestsMetadata,
    },
    price_lists: {
        navigationMetadata: Price_listsRequestBuilderNavigationMetadata,
    },
    price_listsJson: {
        requestsMetadata: Price_listsJsonRequestBuilderRequestsMetadata,
    },
    printersJson: {
        requestsMetadata: PrintersJsonRequestBuilderRequestsMetadata,
    },
    products: {
        navigationMetadata: ProductsRequestBuilderNavigationMetadata,
    },
    productsJson: {
        requestsMetadata: ProductsJsonRequestBuilderRequestsMetadata,
    },
    recurrings: {
        navigationMetadata: RecurringsRequestBuilderNavigationMetadata,
    },
    recurringsJson: {
        requestsMetadata: RecurringsJsonRequestBuilderRequestsMetadata,
    },
    warehouses: {
        navigationMetadata: WarehousesRequestBuilderNavigationMetadata,
    },
    warehousesJson: {
        requestsMetadata: WarehousesJsonRequestBuilderRequestsMetadata,
    },
    warehouse_actionsJson: {
        requestsMetadata: Warehouse_actionsJsonRequestBuilderRequestsMetadata,
    },
    warehouse_documents: {
        navigationMetadata: Warehouse_documentsRequestBuilderNavigationMetadata,
    },
    warehouse_documentsJson: {
        requestsMetadata: Warehouse_documentsJsonRequestBuilderRequestsMetadata,
    },
    webhooks: {
        navigationMetadata: WebhooksRequestBuilderNavigationMetadata,
    },
    webhooksJson: {
        requestsMetadata: WebhooksJsonRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
